### ISSUE TITLE
Duplicate page descriptions

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#101]
Remove redundant <meta description> tags from the page source, so that only one <meta description> tag exists.

As a best practice, there should only be a single meta description per page, contained in the <head> section of the page source.

* [x] https://geo.ca/home/index.html
* [x] https://www.geo.ca/fr/accueil/index.html
* [x] https://www.geo.ca/fr/galerie-de-cartes/index.html
* [x] https://geo.ca/geo-in-the-news/index.html
* [x] https://www.geo.ca/fr/environnement/index.html
* [x] https://geo.ca/
* [x] https://geo.ca/CA/fr/index.html

**Comment by jaredkinger** [comment]
This is a conflict between the Phlox theme's supporting plugins and the Yoast SEO plugin. Yoast should take priority.

**Comment by jaredkinger** [comment]
Duplicate meta description has been removed on the WordPress dev.
- Disabled Phlox Built-In SEO under Appearance > Customize > General > Google API Keys & SEO
- Updated Yoast Meta Description template to `Excerpt` instead of `Title Separator Site Title`
