### ISSUE TITLE
Page description is too short or too long

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#102]
Change the description in the <meta description> tag in the page source to be between 25 and 160 characters in length.

Search engine crawlers only show the first 150-160 characters of the description in the search results page, so if a description is too long, searchers may not see all of the text. If a description is too short, the search engines may add text found elsewhere on the page. Note that search engines may show a different description from the one you have authored if they feel it may be more relevant to a user's search.

We can ignore for pages that we don't need/want indexed.

* [x] https://geo.ca/geo-in-the-news/index.html
* [x] https://www.geo.ca/fr/environnement/index.html
* [x] https://www.geo.ca/fr/accueil/index.html
* [x] https://geo.ca/home/index.html
* [ ] ~~https://datacube.services.geo.ca/en/viewer/elevation/index.html~~

**Comment by jaredkinger** [comment]
This should be resolved with the work done on issue #101. Meta descriptions were set to match the page title which were too short, updating to the excerpt fixes that and Yoast takes care of truncating the excerpt to keep it under 160 characters.

The fix above only affects the https://geo.ca URLs and will not have an effect on the datacube.services.geo.ca URL

**Comment by jaredkinger** [comment]
I've passed the issue concerning https://datacube.services.geo.ca/en/viewer/elevation/index.html onto Jean-Francois over at the datacube team.
