### ISSUE TITLE
Page contains multiple titles

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#103]
Remove redundant <title> tags from the page source, so that only one <title> tag exists.

As a rule, you should only have a single <title> per page on your website.

* [ ] https://datacube.services.geo.ca/en/viewer/elevation/index.html

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/103?planning-poker) with Zenhub @jvanulde @jaredkinger

**Comment by jvanulde** [comment]
This is for the datacube team in Sherbrooke.

**Comment by jaredkinger** [comment]
I've passed this issue on to Jean Francois over at the datacube team. @jvanulde please close the issue when you have a moment.
