### ISSUE TITLE
Pages missing H1 tag

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#104]
Add a header to the page by using a `<h1>` tag and place it within the <body> of the page source.
Example:
```
<body>
    <h1>A precise and descriptive headline for the page</h1>
    ...
</body>
```

The `<h1>` tag is an indicator to Bingbot and web visitors of what the body copy's primary theme or topic is. The `<h1>` tag reinforces the core keyword(s) found in the title, description, and the body copy. We recommend that the `<h1>` tag includes keywords that reflect the contents of the page and that it is not longer than approximately 150 characters in length.

* [x] https://geo.ca/
* [x] https://geo.ca/CA/fr/index.html

**Comment by jaredkinger** [comment]
https://geo.ca/CA/fr/index.html should be a 404 page so we can likely ignore that.

https://geo.ca/ functions as a language selector. We don't currently have a French translation setup for this page which would ended up being https://geo.ca/fr/. My suggestion here would be to add an h1 on the English version with *Choose Your Language* and then create a French translation of that page.

**Comment by jvanulde** [comment]
The splash page at https://geo.ca is in both official languages. It doesn't need to be translated.

**Comment by jaredkinger** [comment]
The page's content is in both official languages but the document's language `<html lang="en-CA">` is set to English and the French alternate link `<link rel="alternate" href="./fr/index.html" hreflang="fr">` in the head tag doesn't exist. Having the French alternative exist would be good as search engines will try to serve that if they know the searchers language is French.

If we are looking to resolve the issue of a missing H1 tag then we should add an H1 tag that has a relevant heading. This would likely be beneficial for accessibility as well as it would add some context above the buttons for screen readers. 

To further illustrate my suggestion:

### English splash at https://geo.ca/index.html
![english-splash](https://user-images.githubusercontent.com/24461497/214860230-b44f6dcb-0f81-4a0d-8a98-1db3114ae8ad.jpg)

### French splash at https://geo.ca/fr/index.html (doesn't currently exist)
![french-splash](https://user-images.githubusercontent.com/24461497/214860459-86bf66f2-0611-4077-bc71-6d7e1637df67.jpg)

Alternatively we could do 2 things:

1. Wrap the image in an H1 tag. Not a best practice and we would need to make sure the logo has an alt text in both English and French which is currently missing. I do have a request to get the logo's alt text translated. The current English alt text may not make for the best heading though as it is: **GEO.CA logo, blue and green globe**
2. Get rid of the splash page and move https://geo.ca/home/index.html to https://geo.ca/index.html. Then when we can use a popup overlay to allow a user to select their language. The popup could save a cookie on close with the user's language selection for future visits.

@jvanulde Let me know your thoughts.

**Comment by jvanulde** [comment]
The splash page is part of the GC standard as defined by: https://wet-boew.github.io/wet-boew/index-en.html

**Comment by jvanulde** [comment]
Is it materially different than what is at: https://www.canada.ca/?

**Comment by jaredkinger** [comment]
@jvanulde Thanks for sharing that. https://www.canada.ca/ is using a visually hidden H1 tag `<h1 property="name" class="wb-inv">Canada.ca</h1>`. The H1 tag while visually hidden is still readable by screen readers. I can implement this same technique here and just swap Canada.ca for Geo.ca. 

They also have two visually hidden H2 tags before each language button with Government of Canada / Gouvernement du Canada respectively. Geo.ca also has the H2 tags before the language buttons but contains *GEO.CAa* so I will fix that typo.

It might read a bit weird on a screen reader with the H1 containing GEO.CA and then followed by an h2 with GEO.CA but if that conforms to the GC standards then I guess that is what we need to do. Does that work for you?

**Comment by jaredkinger** [comment]
I've added `<h1>GEO.CA</h1>` to the splash page beneath the that is visually hidden but still accessible to screen readers above the GEO.CA logo. I fixed the typo in the H2 tags as well.
