### ISSUE TITLE
Redirect www to non www to prevent duplicate content

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#110]
www.geo.ca should redirect to geo.ca to prevent google from indexing both versions and creating duplicate content errors as well as splitting ranking authority between the two versions.

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/110?planning-poker) with Zenhub @indiciumx

**Comment by jaredkinger** [comment]
One more thing to note is that this should be a wildcard redirect if possible, e.g. https://www.geo.ca/example-page/ should redirect to https://geo.ca/example-page/

**Comment by jaredkinger** [comment]
I found this document: [Use S3 and CloudFront to host Static Single Page Apps (SPAs) with HTTPs and www-redirects](https://gist.github.com/bradwestfall/b5b0e450015dbc9b4e56e5f398df48ff)

It looks like we can use the DNS to accomplish this. There are instructions for pointing the A record of the `www` to handle the redirect under [Route 53](https://gist.github.com/bradwestfall/b5b0e450015dbc9b4e56e5f398df48ff#route-53)

@PVautour @indiciumx @arashmalekz 

Let me know your thoughts and if this is possible. Thanks.

**Comment by pvautour** [comment]
So i followed [these instructions](https://docs.aws.amazon.com/AmazonS3/latest/userguide/website-hosting-custom-domain-walkthrough.html) to setup a bucket that redirects to geo.ca:

```
Step 4: Configure your subdomain bucket for website redirect

After you configure your root domain bucket for website hosting, you can configure your subdomain bucket to redirect all requests to the domain. In this example, all requests for www.example.com are redirected to example.com.
To configure a redirect request

    On the Amazon S3 console, in the Buckets list, choose your subdomain bucket name (www.example.com in this example).

    Choose Properties.

    Under Static website hosting, choose Edit.

    Choose Redirect requests for an object.

    In the Target bucket box, enter your root domain, for example, example.com.

    For Protocol, choose http.

    Choose Save changes.
```
This is the resulting url in dev:

`http://redirect-test-pvautour.s3-website.ca-central-1.amazonaws.com`

We can then point a cloudfront entry to the bucket.

@indiciumx @jaredkinger @arashmalekz This was quick and easy. Is it a reasonable solution to your eyes? If so i will bring it to staging and prod.

**Comment by pvautour** [comment]
Ok this is now up in staging.

www.stage.geo.ca

**Comment by pvautour** [comment]
Update: I need to find the cloudformation for next release and add it to it.

**Comment by pvautour** [comment]
this has been merged into the dev branch of our cloudformations. i will close the issue once it makes it to prod.

**Comment by bo-lu** [comment]
@PVautour I think this ticket can be closed now correct?

**Comment by pvautour** [comment]
yes it's in prod.
