### ISSUE TITLE
Clean up wordpress.dev.geo.ca WP install

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#111]
The WordPress install for dev is quite large at around 4.7 GB. There are lots of folders containing old files that should be removed to reduce the size of the install. Some are leftovers from an Updraft restore and others are migrations from AIOWP. The debug.log file has grown to 390MB which is unnecessary.

There is over 400+ pages currently and most of them are set to private so they are creating clutter. It needs to be determined if we can remove these pages or if we should create an archive status for unused content. @sean-eagles to follow up with the content team for clarification.

Content does not appear to be in sync with what's currently on production. Example: The logo on the contact page here: https://www.geo.ca/fr/contactez-nous/index.html does not match here: https://wordpress.geo.dev.ca/wordpress/contact/

Translations are out of sync for some pages and some french pages have incorrect page parents. Example: https://wordpress.dev.geo.ca/wordpress/administration/ has it's French translation pointing here: https://wordpress.dev.geo.ca/wordpress/fr/themes-2/administration-fr/ instead of here: 

Images have been duplicated to support alt-text translations but Polylang has a module to support media translations that should be used instead. An exception to this would be images that display text which will require separate images for each language.

- [x] Delete *-old directories, AIOWP backups
- [x] Clear out debug.log and resolve notices/warnings to prevent future bloat
- [x] Uninstall unused plugins
- [x] Fix Admin Edit Pages view. Currently lists 5 pages instead of the default 20. 
- [x] Archive or remove unused pages
- [x] Synchronize changes made to build html files with WordPress install content
- [x] Synchronize page translations and fix incorrect page parents
- [x] Activate [Polylang media translations](https://polylang.pro/doc/working-with-media/) and dedupe/translate images
- [x] Update out of date plugins

**Comment by sean-eagles** [comment]
Hi @jaredkinger , I sat down with Steve and had a chat about our responsibilities at keeping content.  It is our responsability to archive content.  Steve is going to do some checking if a backup using Updraft Plus would suffice.When I have more news I will post it here.

**Comment by jaredkinger** [comment]
- Old directories cleared out for ~2.5 GB savings. The majority were leftovers from an Updraft plus rollback. When rolling back please remember to clear the old folders using the "Delete Old Directories" button on Updraft plugin page.
- Phlox theme was adding theme support for `html5` resulting in PHP notices on every page load. I've removed `html5` from the theme supports via the `auxin_theme_support` filter
- Removed the following inactive plugins: 
   - Aspose.Words
   - Ele Custom Skin
   - Elementor Addon Elements
   - ElementsKit Lite
   - OAuth Single Sign On - SSO (OAuth Client) version 6.19.6 & 38.0.0
   - Unlimited Elements for Elementor
- _À propos de nous_ page was breaking the Admin Edit Pages view because it had it's `page_parent` sent to it's own ID causing an infinite loop that would eventually time out. Updating the page reset the `page_parent` to 0.
- Installed and activated the classic editor
- Implemented a new `Archive` status. All private/draft pages and all posts have been set to `Archive`. 303 Pages and 81 Posts in total.
- Updated Contact Page logos for EN/FR. **French logo needs french alt text**
- Archived an additional 53 pages so the only remaining published pages match what is currently available on https://geo.ca or are pages that are in active development
- Fixed several broken translation links that were a result of pages being duplicated using the EA Duplicator which carried over the translation link to the newly created page breaking the link on the original page. Installed the Yoast Duplicate Post plugin which provides that same functionality but does not conflict with the Polylang translations
- Several pages had their page parents set to pages they should not be a child of. Updated these page to not have a parent.
- Synchronized content changes that were made on the fly to build files
- Enabled Polylang media translations, translated existing media, discovered missing French translations
- All out of date plugins have been updated. Elementor CGP Widgets plugin has been updated to remove Elementor deprecated notices
