### ISSUE TITLE
Missing French Translations

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#115]
## Image Alt Text

[**Site Logo**]( https://geo.ca/wp-content/uploads/2020/02/logo_geo_164x70.png)
**Alt Text:** GEO.CA logo, blue and green globe

[**Women's Banner Credit**](https://geo.ca/wp-content/uploads/2021/08/womens-banner-credit.jpg)
**Alt Text:** From left, Thérèse Casgrain, Lucy Maud Montgomery, Gabrielle Roy, Emily Carr, Saint Kateri, Agnes Macphail

[**Map Gallery**](https://geo.ca/wp-content/uploads/elementor/thumbs/in-the-spotlight-map-16-9-cr-pxh843apy2c844o6w2cm5rplmeen5reiqq2eyuqsno.jpg)
**Alt Text:** Image of a map
**Notes:** Consider revising alt text to be more descriptive such as "A map of Canada". A new image with the map legend in French is required

[**COVID-19**](https://geo.ca/wp-content/uploads/elementor/thumbs/COVID-19-pxh841f1ke9ngwqx71jd0s6ofmnwqd722grg0atl04.jpg)
**Alt Text:** Coronavirus Disease (COVID-19) Update
**Notes** Consider revising by dropping "Update" as it is not descriptive of the image

[**Canada Flag**](https://geo.ca/wp-content/uploads/elementor/thumbs/canada-27003-pxh842cn3uy0s4jc53pb158suttqeuluonvi3smbn8.png)
**Alt Text:** Canada Flag

[**Alberta Flag**](https://geo.ca/wp-content/uploads/2020/05/alberta-flag.jpg)
**Alt Text:** Alberta Flag

[**British Columbia Flag**](https://geo.ca/wp-content/uploads/2020/05/british-columbia-flag.jpg)
**Alt Text:** British Columbia Flag

[**Manitoba Flag**](https://geo.ca/wp-content/uploads/2020/05/manitoba-flag.jpg)
**Alt Text:** Manitoba Flag

[**New Brunswick Flag**](https://geo.ca/wp-content/uploads/2020/05/new-brunswick-flag.jpg)
**Alt Text:** New Brunswick Flag

[**Newfoundland and Labrador Flag**](https://geo.ca/wp-content/uploads/2020/05/newfoundland-labrador-flag.jpg)
**Alt Text:** Newfoundland and Labrador Flag

[**Northwest Territories Flag**](https://geo.ca/wp-content/uploads/2020/05/northwest-territories-flag.jpg)
**Alt Text:** Northwest Territories Flag

[**Nova Scotia Flag**](https://geo.ca/wp-content/uploads/2020/05/nova-scotia-flag.jpg)
**Alt Text:** Nova Scotia Flag

[**Nunavut Flag**](https://geo.ca/wp-content/uploads/2020/05/nunavut-flag.jpg)
**Alt Text:** Nunavut flag

[**Ontario Flag**](https://geo.ca/wp-content/uploads/2020/05/ontario-flag.jpg)
**Alt Text:** Ontario Flag

[**Province of Prince Edward Island Flag**](https://geo.ca/wp-content/uploads/2020/05/prince-edward-island-flag.jpg)
**Alt Text:** Province of Prince Edward Island Flag

[**Quebec Flag**](https://geo.ca/wp-content/uploads/2020/05/quebec-flag.jpg)
**Alt Text:** Quebec Flag

[**Quebec Flag**](https://geo.ca/wp-content/uploads/2020/05/quebec-flag.jpg)
**Alt Text:** Quebec Flag

[**Saskatchewan Flag**](https://geo.ca/wp-content/uploads/2020/05/saskatchewan-flag.jpg)
**Alt Text:** Saskatchewan Flag

[**Yukon Flag**](https://geo.ca/wp-content/uploads/2020/05/yukon-flag.jpg)
**Alt Text:** Yukon Flag

[**Downtown Vancouver Buildings**](https://geo.ca/wp-content/uploads/elementor/thumbs/Open-Database-of-Buildings-and-Automatically-Extracted-Buildings-pxh841f1ke9ngwqx71jd0s6ofmnwqd722grg0atl04.jpg)
**Alt Text:** The downtown buildings of Vancouver, British Columbia at dusk with a body of water and mountains in the background

[**Aerial View**](https://geo.ca/wp-content/uploads/elementor/thumbs/FL-22-cded-pxh840h7dk8d5asacj4qgaf7u8sjio3bqc3yj0uz6c.jpg)
**Alt Text:** An sepia-toned aerial view of Canadian elevation features using slope, shaded relief and colour shaded relief maps

[**Hand Reaching**](https://geo.ca/wp-content/uploads/elementor/thumbs/marc-olivier-jodoin-TStNU7H4UEE-unsplash-scaled-e1638908395595-pxh842cvr8axsipk1jxzl9y510j9y2aselexhks6tw.jpg)
**Alt Text:** Hand reaching towards sunset

[**Celebrate Canada**](https://geo.ca/wp-content/uploads/elementor/thumbs/celebrate-canada-1100-1-pxh842cvr8axsipk1jxzl9y510j9y2aselexhks6tw.jpg)
**Alt Text:** People waving Canadian Flags at sunset

[**Elections Canada Vote**](https://geo.ca/wp-content/uploads/elementor/thumbs/ele1-cr-scaled-pxh843apy2c844o6w2cm5rplmeen5reiqq2eyuqsno.jpg)
**Alt Text:** An Elections Canada 'vote' sign outside of a polling place
**Notes:** This image contains text so an image with the French text would be ideal in addition to the translated alt text

[**Wakefield**](https://geo.ca/wp-content/uploads/elementor/thumbs/DSM-DTM_Wakefield-cr-pxh843apy2c844o6w2cm5rplmeen5reiqq2eyuqsno.jpg)
**Alt Text:** 3-D shaded relief of digital surface model of Gatineau Highway near Wakefield QC

[**Red River**](https://geo.ca/wp-content/uploads/elementor/thumbs/brydon-mccluskey-Ozo27HdqtT0-unsplash-cr-pxh843apy2c844o6w2cm5rplmeen5reiqq2eyuqsno.jpg)
**Alt Text:** Aerial shot of some trees along the Red River in Maple Grove Park, Winnipeg, MB, Canada

### Government of Canada
English Link: https://geo.ca/government-of-canada/index.html
French Link: https://geo.ca/fr/gouvernement-du-canada/index.html

There are 3 agencies/departments missing from the French version of this page. Translations are needed for the following:

**Health Canada (HC)**
HC is responsible for helping Canadians maintain and improve their health. It ensures that high‑quality health services are accessible, and works to reduce health risks.

**Indigenous Services Canada (ISC)**
ISC works collaboratively with partners to improve access to high‑quality services for First Nations, Inuit and Métis.

**Natural Resources Canada (NRCAN)**
NRCan seeks to enhance the responsible development and use of Canada’s natural resources and the competitiveness of Canada’s natural resources products.

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/115?planning-poker) with Zenhub @Andrea-Merry @jaredkinger

**Comment by Andrea-Merry** [comment]
Sending this to translation. Hopefully, back next week.

**Comment by elatsis** [comment]
@Andrea-Merry will this be complete before Feb release (Feb 15)?

**Comment by Andrea-Merry** [comment]
@elatsis I requested to have the translation back by February 14th.

**Comment by Andrea-Merry** [comment]
@elatsis @jaredkinger Please see attached file with the translations for GEO.ca. Let me know if you have any questions.
[10735651_001_FR_2023-02-06 Translation_misc_text_for_geoca.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10734577/10735651_001_FR_2023-02-06.Translation_misc_text_for_geoca.docx)
