### ISSUE TITLE
Add announcement bar

### ISSUE THREAD

**Issue by ehfounder** [Canadian-Geospatial-Platform/geo.ca#119]
On GEO.CA wordpress instance there is a green bar at the top of the header. This is the announcement bar location. We need to create a widget that dynamically pulls an announcement from an API in English or French based on language on page. 

API is {API Endpoint}/announcements and the only variable is "lang" in either en or fr.

This fetches the latest announcement from the system and displays it.

**Comment by jaredkinger** [comment]
A custom elementor widget has been created and added to the header for the announcement bar. If the API returns `n/a` the announcement area will remain empty. This is active on https://wordpress.dev.geo.ca

**Comment by jvanulde** [comment]
Demo'd on February 6.
