### ISSUE TITLE
Replacement of nrcan.gc.ca and rncan.gc.ca links

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#125]
NRCan just transitioned to new links for their nrcan.gc.ca and rncan.gc.ca links to canada.ca links.  All existing links on the site must be changed to redirect to the proper pages.

**Comment by jaredkinger** [comment]
I did a find and replace on the database. I also checked the theme for any URLs

863 occurrences of https://www.nrcan.gc.ca/ have been updated to https://natural-resources.canada.ca/
80 occurrences of https://www.rncan.gc.ca/ have been updated to https://ressources-naturelles.canada.ca/

0 occurrences of https://www.nrcan-rncan.gc.ca were found.

If anyone knows of any additional variations of the domains or subdomains that need to be updated please let me know.

**Comment by jaredkinger** [comment]
5 occurrences of http://www.nrcan.gc.ca/ have been updated to https://natural-resources.canada.ca/

I found some additional subdomains that are referenced such as:

- https://cwfis.cfs.nrcan.gc.ca/
- https://proxyinternet.nrcan.gc.ca/
- https://geoappext.nrcan.gc.ca/
- https://www.earthquakescanada.nrcan.gc.ca/
- https://geoscan.nrcan.gc.ca

These subdomains do not appear to have been moved over yet.

**Comment by sean-eagles** [comment]
Message sent off to Andria King for verification of which domains/subdomains we have to change.

**Comment by sean-eagles** [comment]
From Andria King:
Okay… so it looks like you are working on replacing the old English and French links to the new domain. That’s great! And given that the redirects are in place so you’ve oodles of time, you’re well ahead of the curve (i.e. on Canada.ca/NRCan.ca it’s going to be an agonizingly slow process as we have to fix each page one by one). 

I don’t think you have any others other than possibly Vanity URLS. Those are going to be slowly replaced, but again will be fully functional old or new via the redirect. I was going to be asking about that more directly. I’ll let you know what I find out and/or when they change.

Re: the following

I found some additional subdomains that are referenced such as:
•	[https://cwfis.cfs.nrcan.gc.ca/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fcwfis.cfs.nrcan.gc.ca%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C22fe65ef2afe4835024f08db150a1567%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126905275120778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YcC6NdjBcBwA7QYlQ45SF%2BSrcTHHj3f%2BD9IqFiW93Cw%3D&reserved=0)
•	[https://proxyinternet.nrcan.gc.ca/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fproxyinternet.nrcan.gc.ca%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C22fe65ef2afe4835024f08db150a1567%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126905275120778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B2Qz17ULrsGIvRLBKay64y59pc7PWKhhnoiAFvKD8yk%3D&reserved=0)
•	[https://geoappext.nrcan.gc.ca/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeoappext.nrcan.gc.ca%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C22fe65ef2afe4835024f08db150a1567%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126905275120778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GxfH%2B4wwGT4fGf2JaWJdoD2T2aYhzoLrkZtnhu34k1g%3D&reserved=0)
•	[https://www.earthquakescanada.nrcan.gc.ca/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.earthquakescanada.nrcan.gc.ca%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C22fe65ef2afe4835024f08db150a1567%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126905275120778%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=n1Pj4YmVugZQmh9fda70T6ugBmyOXpiTQ9fq4HOuxM0%3D&reserved=0)
•	[https://geoscan.nrcan.gc.ca](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeoscan.nrcan.gc.ca%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C22fe65ef2afe4835024f08db150a1567%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126905275276828%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4eaq5Of321uq0GN1%2B6nv3uCFjwuNoxRlvxisX3NDuV8%3D&reserved=0)
These subdomains do not appear to have been moved over yet.
“ 

Do we have to change those also, I was figuring that they were apps that were not moved yet but was looking to confirm.

Good flagging those. This is what I know:

@jaredkinger This part came by email, can't be posted here.
 
So essentially, yes. Apps that have not been moved as yet. 

Some of them ours – note that on the ones that are ours we need to update the Theme/skin as well (if it’s public – some of these may not be).  

Do you want me to add you to my notice lists as a matter of course? Can add Jared (King??) too, if that helps. Can ignore that doesn’t apply. I don’t send out too many notices. 😉 

Andria
