### ISSUE TITLE
Proposed EIF CCMEO Web Presence workplan: CCMEO on the Source

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#13]
CCMEO web content published within NRCan Source to highlight services offerings and key activities relevant to NRCan.

This will be assigned to Steven Dunning's team.

**Comment by Andrea-Merry** [comment]
@heamart We can add this issue to our content plan.

**Comment by sean-eagles** [comment]
Something to be worked on in the future, not set to priorities yet. @Andrea-Merry @heamart
