### ISSUE TITLE
Initial load of theme page returns no results

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#131]
In Safari on MacOS and iOS, sometimes when clicking on the "VIEW ALL <theme> DATA" link there are no results. When refreshed, the page loads as expected with results. Can't be replicated consistently.

Example URL: https://app.geo.ca/?theme=emergency&lang=en

**Comment by jaredkinger** [comment]
@jvanulde Should this issue be in the repo over here: https://github.com/Canadian-Geospatial-Platform/app.geo.ca?

**Comment by bo-lu** [comment]
The API call should be fixed with the increase in memory which affected cold starts (hence intermittent problems). Fix has been applied but let's wait until Monday to see if the issues goes away permanently.
