### ISSUE TITLE
User Story: Spatial and temporal filters on app.geo.ca

### ISSUE THREAD

**Issue by xinli-cai** [Canadian-Geospatial-Platform/geo.ca#133]
As a user, I would like  to be able to search for records that fall within a specific time period and / or geographical location, by using a bounding box. For example, the[ STAC Broswer spatial and temporal search filter ](https://radiantearth.github.io/stac-browser/#/search/external/datacube.services.geo.ca/api/). 

An example mock up is shown below:  
![Mockup-spatial_and_temporal_filter](https://user-images.githubusercontent.com/103012417/219709767-561cf3ac-d480-4e2d-bbd5-f0e0f1f1a921.png)

**Comment by xinli-cai** [comment]
@bo-lu @johnweng001 FYI

**Comment by bo-lu** [comment]
Parent issue is: #70

**Comment by bo-lu** [comment]
New mockup for the spatial extent search:

![spatial-mockup](https://user-images.githubusercontent.com/18405829/226366464-862aeff3-f476-496b-91d6-171123091e22.png)

**Comment by bo-lu** [comment]
1) A dropdown with provinces and territories. Selecting this would set the bbox to the extent of the area of interest
2) A extent search bar where users can search for extents using the geolocator api
3) A freeze spatial filtering checkbox on the main map which when selected will prevent search by extent when the user pans or zooms on the main map

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/133?planning-poker) with Zenhub @johnweng001 @bo-lu
