### ISSUE TITLE
Streamline Content Release

### ISSUE THREAD

**Issue by ehfounder** [Canadian-Geospatial-Platform/geo.ca#135]
Streamline Content Release with GitHub actions allowing Knowledge workers to publish updated content.

**Comment by bo-lu** [comment]
Explore GitHub Actions that will:

- [ ] Create the Lambda deployment zip file upon any change to the source code.
- [ ] (optional) Action to upload the Lambda zip to S3.
- [ ] Submit a PR to alter the CloudFormation script to replace the old lambda zip filename with the new zip filename.
