### ISSUE TITLE
Photos for gallery - Geobase single page design

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#136]
@vgulyy found photos to update the page.

Photos are licensed appropriately, and fulfill the criteria of being taken by a Canadian, and/or are a photo of Canada.

Next step is for @jaredkinger to implement photos in media and on site.

**Comment by sean-eagles** [comment]
Hello Team,

I was able to find Canadian images that can be used for free for commercial and non-commercial purposes, and no permission needed from the authors. 

I labeled each image with a corresponding thumbnail label, the actual link to the source file and also the author and the confirmation for the free license (you may want to keep a copy/screenshot of the free license label for each image somewhere just incase for the future)

I am also attaching an example with each image cropped into our GeoBase thumbnail to give an idea of how it would look like.


Thumbnail: Aboriginal Lands  
•      Image Source: [https://unsplash.com/photos/dzMGBH88ZOA](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FdzMGBH88ZOA&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276356894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Yoc4vlzwMJ1ljrTMjU%2FmvEnJeL9am1ICacH82zSb6vg%3D&reserved=0) 
•      Author: [https://unsplash.com/@galen_crout](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40galen_crout&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276356894%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=V8uwXsSKpwlF7NxPBnHeoEHhMQIUB21anEGgXSf%2BNNI%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCRnRBWGZvyP%2BfrRL3a0aBL0ECbyw6D5TQ%2BGhAMX4Ak%3D&reserved=0)
 
Thumbnail: Administrative Boundaries
•      Image Source: [https://unsplash.com/photos/mluSdDeOksc](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FmluSdDeOksc&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=iAUCLGui0LDQxdpCDuTy%2BWM9CWEoEktYu2QetSRMkJQ%3D&reserved=0) 
•      Author: [https://unsplash.com/@iliketobike](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40iliketobike&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hJkKrH93dNG0jruwsbtDCoiHJDFd2LgyVw5fTVa8O2M%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCRnRBWGZvyP%2BfrRL3a0aBL0ECbyw6D5TQ%2BGhAMX4Ak%3D&reserved=0)
 
Thumbnail: Automatically Extracted Buildings
•      Image Source: [https://unsplash.com/photos/NqOInJ-ttqM](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FNqOInJ-ttqM&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0j7f18odiNmt1acr2WMt1TIqUcI3GtxiZ2M8QbzTCjY%3D&reserved=0) 
•      Author: [https://unsplash.com/@marcojodoin](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40marcojodoin&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=y%2FOXeb7tFbcwLU%2FWZcxKnggsdTDFoAwTPP%2Bg8TvHiBI%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCRnRBWGZvyP%2BfrRL3a0aBL0ECbyw6D5TQ%2BGhAMX4Ak%3D&reserved=0)
 
 
Thumbnail: Automatically Extracted Features
•      Image Source: [https://unsplash.com/photos/DLmED-Rpp-k](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FDLmED-Rpp-k&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=XkZmb7wFw7S1i9%2BoY6tu3cQ1QwAZXx4Ng0ekQwxsIDE%3D&reserved=0) 
•      Author: [https://unsplash.com/@scottwebb](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40scottwebb&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hZV6ZZuruqRha80ytq8B7%2FbNs3rBircCSiBhCDSO5JI%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCRnRBWGZvyP%2BfrRL3a0aBL0ECbyw6D5TQ%2BGhAMX4Ak%3D&reserved=0)
 
Thumbnail: Canadian Hydrospatial Network
•      Image Source: [https://unsplash.com/photos/CPjkWSD0RM0](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FCPjkWSD0RM0&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ogqSAaNbpvdLCS7CsbyU1s9eI92gikMD%2BSrMixiDXiM%3D&reserved=0) 
•      Author: [https://unsplash.com/@kevincaptures](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40kevincaptures&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=C9YsaPmbOH3XvPjvfhRkVrhHV81Klzeu3viuZy8NYck%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCRnRBWGZvyP%2BfrRL3a0aBL0ECbyw6D5TQ%2BGhAMX4Ak%3D&reserved=0)
 
Thumbnail: Canadian Digital Elevation Model
•      Image Source: [https://unsplash.com/photos/X6jFJfQNFtM](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FX6jFJfQNFtM&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2B%2FaMc4gOKtk4H9mVSQ%2BmhhpSbP6l06WtJraPWRhGVsg%3D&reserved=0) 
•      Author: [https://unsplash.com/@smnzhu](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40smnzhu&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=GIVBFrxB1mkSuVknEV6CQf%2Fj2Zwcy7sNE4%2FZ3P96KBU%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCRnRBWGZvyP%2BfrRL3a0aBL0ECbyw6D5TQ%2BGhAMX4Ak%3D&reserved=0)
 
Thumbnail: Federal Electoral Districts
•      Image Source: [https://unsplash.com/photos/C2keINMOhIE](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FC2keINMOhIE&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=qhMsJUSErBq50UL1ukjosgG%2FPtT3EoQq65%2BNWJWQio8%3D&reserved=0) 
•      Author: [https://unsplash.com/@jasonhafso](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40jasonhafso&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=axqrXCSttgiLNQfSMOj6Fe3oFCtRmruURxoCfbgnjRA%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=TCRnRBWGZvyP%2BfrRL3a0aBL0ECbyw6D5TQ%2BGhAMX4Ak%3D&reserved=0)
 
Thumbnail: High Resolution Digital Elevation Model
•      Image Source: [https://unsplash.com/photos/AAmDpozA61A](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FAAmDpozA61A&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276513124%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=HaYLolOosnC69o3g4c2Kw%2FPUpUiKonUPXR6E2bEuB2M%3D&reserved=0) 
•      Author: [https://unsplash.com/@usgs](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40usgs&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=bnF3e9kCPE1kb9bSwaC%2BDVL8w5QlUfIruxqJ7XdQGuY%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aQCE2egE3aLnRTVGxkJR6kbcXpTx7I0HIpltDoIr5VQ%3D&reserved=0)
 
Thumbnail: Land Cover Of Canada
•      Image Source: [https://unsplash.com/photos/I4xW51VZ5TI](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FI4xW51VZ5TI&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AwqFyJm4QoiwpCmnKMvtXQ%2Fs1MVXeL8nJFBAv6lTWqk%3D&reserved=0) 
•      Author: [https://unsplash.com/@edwardkoorey](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40edwardkoorey&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=lwHxMnDwyBblaCoJdHa6hTN2oFh%2FtZWsQ%2BlVdOTtzNw%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aQCE2egE3aLnRTVGxkJR6kbcXpTx7I0HIpltDoIr5VQ%3D&reserved=0)
 
Thumbnail: National Hydro Network (NHN)
•      Image Source: https://unsplash.com/photos/LGBQnOdlgfw
•      Author: https://unsplash.com/@sigmund
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aQCE2egE3aLnRTVGxkJR6kbcXpTx7I0HIpltDoIr5VQ%3D&reserved=0)
 
Thumbnail: National Road Network
•      Image Source: [https://unsplash.com/photos/LGBQnOdlgfw](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FLGBQnOdlgfw&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=17Pf5nOGrRqM6fPa1aL3mUCoL6bz6ZCKtKwG%2FPvbig8%3D&reserved=0) 
•      Author: [https://unsplash.com/@sigmund](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40sigmund&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X9BXDAQSX0eqpysu1l5VVTPuYBwVjV%2FgE4oeY%2FSiZ2E%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aQCE2egE3aLnRTVGxkJR6kbcXpTx7I0HIpltDoIr5VQ%3D&reserved=0)
 
Thumbnail: National Railway Network
•      Image Source: [https://unsplash.com/photos/zPa514Lj7GA](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Fphotos%2FzPa514Lj7GA&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oWmqn1X2AASqOYAsyzmpy8mBK9elIakQxmwTqgiy3yo%3D&reserved=0) 
•      Author: [https://unsplash.com/@juanrojas](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2F%40juanrojas&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=j4QKPs2urc1kZE5NaFxjuEtd0nkmZ9J1jRAmsDNOYF8%3D&reserved=0) 
•      License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aQCE2egE3aLnRTVGxkJR6kbcXpTx7I0HIpltDoIr5VQ%3D&reserved=0)

**Comment by sean-eagles** [comment]
![Example](https://user-images.githubusercontent.com/112004392/220721952-db96adf0-a9f7-48eb-a3e2-e2e6ab9466fd.png)
Attached here is an example from Vlad.

**Comment by jaredkinger** [comment]
The link provided for the National Road Network is the same as the National Hydro Network. Is there a separate image for the National Road Network?

I'd like to suggest we use an image of a body of water for the Canadian Hydrospatial Network. Something like this: https://unsplash.com/photos/aY16vd7hNgk or this: https://unsplash.com/photos/5U2EWg04k48

**Comment by vgulyy** [comment]
@jaredkinger here is the source 
Thumbnail: National Road Network
• Image Source: https://unsplash.com/photos/0mTYg5UZVRc 
• Author: https://unsplash.com/@benjeeeman 
• License: Free to use under the [Unsplash License](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Funsplash.com%2Flicense&data=05%7C01%7Csean.eagles%40nrcan-rncan.gc.ca%7C4ed586a73e624b31d8c708db14fb6943%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638126842276669350%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aQCE2egE3aLnRTVGxkJR6kbcXpTx7I0HIpltDoIr5VQ%3D&reserved=0)

**Comment by vgulyy** [comment]
@jaredkinger, yep, these works too https://unsplash.com/photos/aY16vd7hNgk or this: https://unsplash.com/photos/5U2EWg04k48

**Comment by jaredkinger** [comment]
Images have been updated. @sean-eagles for ALT text should I rely on the descriptions from unsplash or do we have the content team write those?

**Comment by vgulyy** [comment]
@jaredkinger Yep, thats actually a very good question. I think theoretically speaking you can re-use the descriptions from the free images, but I don't think its actually states anywhere that the descriptions are also free to use. Maybe we should slightly change the verbiage to be sure. 

@sean-eagles please let us know your thoughts

**Comment by sean-eagles** [comment]
@jaredkinger @vgulyy I think it would be best to go through the content team for descriptions.  Maybe send them the descriptions as they stand and ask them what they prefer.  @heamart @Andrea-Merry Do we get the content team to write alt text?

**Comment by heamart** [comment]
@jaredkinger @vgulyy in this case, you can email the descriptions as they are to us and we'll see if we want to adjust them Note that links directly to the images on unsplash can't be accessed on my end as the website is blocked.

@sean-eagles what has been the standard on alt-text so far on geo.ca with decorative images? has consistent alt-text been done for all images no matter the purpose?

**Comment by sean-eagles** [comment]
@indiciumx Chris are there standards for Alt Text that we should follow on GEO.ca?  We're looking to add some alt-text to photos for GeoBase's photos in their data gallery.

**Comment by jaredkinger** [comment]
@sean-eagles Does GeoBase need to approve the images? I wouldn't want to send the alt text over to the content team if there is a chance we could end up changing images and thus having to request alt text again.

**Comment by sean-eagles** [comment]
@heamart I sent you an email for this Heather.  Do we need content approval for images we are to use on the site?

**Comment by heamart** [comment]
@sean-eagles responded to your email. I think sending to geobase to get their feedback first is the way to go. Then send to content. If there is a major issue with any of the images with respect to having them on the site we'll source another image to propose

**Comment by heamart** [comment]
@vgulyy @sean-eagles Could the images for Canadian Hydrospatial Network and Canadian Hydrographic Network be changed first before sending to geobase? They should probably be water base (lakes, rivers etc.)

**Comment by jaredkinger** [comment]
@heamart I updated the image for the Canadian Hydrospatial Network this morning to include a picture with of the Wapta Falls in BC. Looking closer I see the National Hydro Network isn't about electricity generation but also about water. I will source a new one for that. I will follow up shortly.

**Comment by jaredkinger** [comment]
Thumbnail: National Hydro Network
- Image Source: https://unsplash.com/photos/xofvJ26aBFo
- Author: https://unsplash.com/@d21_gallery
- License: Free to use under the [Unsplash License](https://unsplash.com/license)

Thumbnail: Canadian Hydrospatial Network
- Image Source: https://unsplash.com/photos/aY16vd7hNgk
- Author: https://unsplash.com/@benjeeeman
- License: Free to use under the [Unsplash License](https://unsplash.com/license)

@heamart You can view the updated GeoBase page here: https://wordpress.dev.geo.ca/wordpress/communities/geobase/

**Comment by sean-eagles** [comment]
complete, pushing to STAG
