### ISSUE TITLE
Metadata 2.0 - Search results (keyword)

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#139]
Coming up with the search results based on keywords, new look and feel.

**Comment by vgulyy** [comment]
This is complete and will be reviewed today with @Saean and @indiciumx

**Comment by vgulyy** [comment]
![Search Results](https://user-images.githubusercontent.com/121049163/226374512-d5dcb119-c03f-412d-a2dc-f9b03f27e9c3.png)

CC: @sean-eagles

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/139?planning-poker) with Zenhub @vgulyy

**Comment by vgulyy** [comment]
@elatsis I have added the planning poker estimate, please let me know if you see on your end

**Comment by sean-eagles** [comment]
Issue presented to Joost and GeoDiscovery team.  Demo created by Vlad, also presented to Chris.  Issue is now closed.
