### ISSUE TITLE
Proposed EIF CCMEO Web Presence workplan: CCMEO on GEO.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#14]
CCMEO product integration within the GEO.ca catalogue and GEO.ca search filters.
1. Atlas products
2. Current basemap products offerings
3. CGDI Harvester data integrated within GEO.ca

* Output of CCMEO Atlas-We Presence Task team
* This work is part of the original EIF ask
* Currently no work is planned for atlas.ca for 2022-2023

**Comment by sean-eagles** [comment]
Closed for now.
