### ISSUE TITLE
Province and Territories Lists Update

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#142]
Update needed on two pages on GEO.ca that list P/Ts with available data in the catalogue:

- https://geo.ca/provinces-and-territories/
- https://geo.ca/contributors/

The Provinces and Territories that need to be added to the lists are:

- Government of Manitoba
- Government of Newfoundland and Labrador
- Government of Northwest Territories
- Government of Nova Scotia
- Government of Prince Edward Island
- Government of Saskatchewan

Attached are the drafts, with the hyperlinks to be added for each page, french and english.
[Contributors_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11040228/Contributors_EN.docx)
[Contributeurs_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11040230/Contributeurs_FR.docx)
[Provinces and Territories_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11040233/Provinces.and.Territories_EN.docx)
[Provinces et territoires_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11040236/Provinces.et.territoires_FR.docx)

**Comment by jaredkinger** [comment]
I've applied these updates on dev.

- [Contributors - EN](https://wordpress.dev.geo.ca/wordpress/contributors/)
- [Contributeurs - FR](https://wordpress.dev.geo.ca/wordpress/fr/contributeurs/)
- [Provinces and Territories - EN](https://wordpress.dev.geo.ca/wordpress/provinces-and-territories/)
- [Provinces et Territoires - FR](https://wordpress.dev.geo.ca/wordpress/fr/provinces-et-territoires/)

The link for Newfoundland on the French Province and Territories page wasn't properly filtering the results. It looks like app.geo.ca has Newfoundland translated to [Gouvernement de Terre-Neuve et du Labrador](https://app.geo.ca/?org=Gouvernement%20de%20Terre-Neuve%20et%20du%20Labrador&lang=fr) vs [Gouvernement de Terre-Neuve-et-Labrador](https://app.geo.ca/?org=Gouvernement%20de%20Terre-Neuve-et-Labrador&lang=fr) as was listed in the document. When filtering by Newfoundland on the French version there are zero results returned. Do these records not exist or is there a bug?

The link for Yukon on the French Province and Territories page was also incorrect so I've also updated that. If you look closely at the old link: https://app.geo.ca/?org=Gouvernement%20du%20Yukonk&lang=fr there is a "k" after Yukon in the query string. The correct URL is: https://app.geo.ca/?org=Gouvernement%20du%20Yukon&lang=fr

**Comment by jaredkinger** [comment]
I just saw this issue #143 that's addressing Newfoundland for the French version. I've reset the link there back to https://app.geo.ca/?org=Gouvernement%20de%20Terre-Neuve-et-Labrador&lang=fr
