### ISSUE TITLE
Search Filter Issue: Newfoundland and Labrador (French)

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#143]
There is an issue with the organization filter for Newfoundland and Labrador in the french search.

The filter is set as "Gouvernement de Terre-Neuve et du Labrador" however this returns 0 results, which is incorrect. It is likely suppose to be "Gouvernement de Terre-Neuve-et-Labrador" to match the metadata.

**Comment by bo-lu** [comment]
It is now fixed. Here is the commit:
https://github.com/Canadian-Geospatial-Platform/app.geo.ca/commit/a6a0548b6a9c23827cacadd3396fd66bbfcadc31

**Comment by jaredkinger** [comment]
@bo-lu I'm seeing the organizational filter being applied for the updated name now but it is still returning 0 results. https://app-dev.geo.ca/?org=Gouvernement%20de%20Terre-Neuve-et-Labrador&lang=fr Do the translated versions of those records exist?

Update: @bo-lu ignore this. I just saw your comment in slack about syncing the records.
