### ISSUE TITLE
Check French hardcoded content in API calls

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#154]
Get translations if needed.  Some of the API calls hardcode strings for French translations.  These do not always match up with the English translations and are sometimes not dynamic compared to their English translations.

**Comment by jaredkinger** [comment]
On theme pages like the [Society Theme](https://geo.ca/society/) there are some strings that are dynamic in the English version but not in the French version. The French versions use the same text regardless of what Theme is being viewed. Was this done on purpose or should we be updating the French translations to be dynamic to more closely match the English version?

Screenshots with the strings highlighted below:

![theme-most-accessed-data](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/24461497/14b59e47-1f2b-4b58-bda8-c9f8632b0805)

![theme-most-accessed-data-fr](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/24461497/a2fb5773-7ca1-4473-bb62-9be825b0e6cb)

**Comment by jaredkinger** [comment]
@Andrea-Merry Can you take a look at my last comment and let me know if these French translations are correct or if they need to be updated?

**Comment by Andrea-Merry** [comment]
@jaredkinger I sent my francophone colleague the screenshot. I will let you know.
