### ISSUE TITLE
Proposed EIF CCMEO Web Presence workplan: Provinces/Territories prototype webpage 

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#16]
Build 2 provinces and territories sponsor pages.

This is very strategic to highlight the capacity to build communities while integrating the contribution made by other jurisdictions (GEO.ca).

* This work was not part of the original EIF ask

**Comment by sean-eagles** [comment]
Hey @Andrea-Merry 

Is this a priority for end of fiscal?

**Comment by Andrea-Merry** [comment]
@sean-eagles I believe Steve wants a web page done for BC by the end of fiscal. We are currently working with a BC representative.

**Comment by sean-eagles** [comment]
Okay, thanks @Andrea-Merry!

**Comment by Andrea-Merry** [comment]
A meeting was held with John Antill, a representative of the British Columbia provincial government. A meeting will be held next week between OAT and the web content team to work on the design of a template for the provinces and territories.

**Comment by sean-eagles** [comment]
@Andrea-Merry for GIY #16, where do we stand for releasing this this fiscal year?

**Comment by Andrea-Merry** [comment]
Verifying with Steve. @sean-eagles

**Comment by Andrea-Merry** [comment]
@sean-eagles After a conversation with Steve, I do not think it will be done by the end of this fiscal year.

**Comment by sean-eagles** [comment]
Okay thank you Andrea.

**Comment by vgulyy** [comment]
The first set of mockups have been approved by content team. The next step is to communicate the visuals to the BC partner and see if they have any input or would like to discuss further. I am also attaching the approved visuals in PDF format here just incase.

[git16-Contributors-Page-Design.pdf](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10872880/git16-Contributors-Page-Design.pdf)

CC: @sean-eagles @heamart

**Comment by sean-eagles** [comment]
@Andrea-Merry This has been presented to the content team a while back, Andrea if we can close this could you please close it on your end.

**Comment by Andrea-Merry** [comment]
I will close it. I have emailed the BC partner a few times with no response. Allison will be in contact with CCOG to see if there are other reps that want to work with us.
