### ISSUE TITLE
Proposed EIF CCMEO Web Presence workplan: User needs analysis

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#17]
CCMEO web presence positioned in terms of NRCan priorities (short, medium, long term)
Must build on ArcticSDI findings and endorsement of target audiences.

 * Output of CCMEO Atlas-Web Presence Task team

**Comment by sean-eagles** [comment]
* Atlas:
- public opinion research completed
- workshops in progress
- analytics from Atlas website
