### ISSUE TITLE
User Story: add EODMS Sentinal data records into Geo.ca

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#176]
As a public user, I would like to search, discover and view EODMS Sentinal data in GEO.ca, so that I don't have to go to multiple portals to access the data that I need.

Requirements:
* [x] bilingual records (not available in EODMS) - possible fees
* [x] harvesting of large catalogues (e.g. paging, search infrastructure)
* [x] search, filter, and discovery optimization for EO datasets
* [x] support pre-visualization (e.g. thumbnails) #134 
* [x] EODMS STAC endpoint (currently Sentinal 1 is available - subset for Canada from Jan-2023)

**Comment by xinli-cai** [comment]
@willmacs @keballantyne. We are currently focused on the task of harvesting the Sentinel-1 STAC collection. During our work, we noticed an issue with the [search API endpoint](https://www.eodms-sgdot.nrcan-rncan.gc.ca/stac/search?collections=sentinel-1): the 'Context' -'Matched' sub-element, appears to be missing (see attached example for reference). 

The 'Matched' is vital as it indicates the total number of available items within the collection. It is required for the functioning of the existing paginator within our STAC harvesting workflow. Would it be possible for you to address this issue on your end? Thank you. 

![MicrosoftTeams-image (2)](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/103012417/a9cc2846-6a1a-416c-846f-1c6c6be498dd)

**Comment by keballantyne** [comment]
The EODMS STAC API now has the `context` - `matched` field for searches and collection items results.

**Comment by xinli-cai** [comment]
The existing paginator workflow has been tested with the EODMS STAC API, and it can successfully paging through all 24,740 items in the Sentinel-1 collection.

**Comment by xinli-cai** [comment]
Dependencies for adding Sentinel-1 Data on geo.ca, June 2024 Release:
1.  #354 
2. #355 
3. #356 
4. #134 
5. #357 
6. #358
