### ISSUE TITLE
Home Page content update

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#184]
@jaredkinger @Andrea-Merry
changes to the home pages. see attached files
1. removing "Popular Maps and Dataset" section
2. Under In the Spotlight:
- change "GEO in the News" to GEO News, new text as well
- remove "Discover the Value" of GEO and add GeoBase Initiative
3. Map Gallery moved to the front page, under Foundational Data, and formatted similarly. Will have first three maps from the map gallery page in the cards on the home page then a link to [Map Gallery](https://geo.ca/map-gallery/)

Last, no changes to the "GEO News" page right now, but if we could apply the name change: https://geo.ca/geo-in-the-news/
and change the header text to match that on the "GEO News" home page card (let me know if that doesn't make sense)

[GEO Home Page_FR DRAFT.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11691027/GEO.Home.Page_FR.DRAFT.docx)
[GEO Home Page_EN DRAFT.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11691028/GEO.Home.Page_EN.DRAFT.docx)

**Comment by jaredkinger** [comment]
@heamart I've added these changes to the WordPress install. You can view the changes by following the links below:

- [Home](https://wordpress.dev.geo.ca/home/)
- [Geo News](https://wordpress.dev.geo.ca/geo-in-the-news/)
- [Accueil](https://wordpress.dev.geo.ca/fr/accueil/)
- [Actualités de GEO](https://wordpress.dev.geo.ca/fr/geo-dans-actualite/)

Please review them and let me know if I have missed anything or if there are any other changes.

One thing to note is that I did not update the URL for the GEO News pages as I am waiting to hear back about how to properly redirect it on production.

**Comment by heamart** [comment]
@jaredkinger all good to go with the homepage. Thank you!

**Comment by sean-eagles** [comment]
Issue is now closed
