### ISSUE TITLE
Add content to NRCan page (s) EN FR

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#187]
@jaredkinger @sean-eagles @heamart 
Hi.
1-Please change the title NRCan Featured Geospatial Initiatives to read NRCan Featured Geospatial Programs and Initiatives and Programmes et initiatives géospatiales en vedette on the French page. Initiatives is currently spelled wrong on the French page.
2- Please add the title Flood mapping hyperlinked to the flood mapping page here - https://geo.ca/flood-mapping/ above the Open Science and data to inform cumulative effects title.
3- Under the Flood Mapping title please add the following text: 
Flooding is Canada’s most costly natural disaster. Each year, it causes an average of over $1 billion in direct damage to homes, property, and infrastructure. Natural disasters are increasing in frequency and severity. Canadian federal, provincial and territorial geospatial data providers are collaborating to provide tools and resources to help Canadians plan and prepare for floods.
4- Please add the title Cartographie des inondations hyperlinked to the flood mapping page here - https://geo.ca/fr/cartographie-inondations/ above the Sciences et données ouvertes pour étayer les effets cumulatifs title.
5- Under the Cartographie des inondations title please add the following text: 
Les inondations sont la catastrophe naturelle la plus coûteuse au Canada. Chaque année, elles causent en moyenne plus d’un milliard de dollars de dommages directs aux habitations, aux biens et aux infrastructures. Les catastrophes naturelles sont de plus en plus fréquentes et de plus en plus graves.
Les fournisseurs canadiens de données géospatiales fédérales, provinciales et territoriales collaborent pour fournir des outils et des ressources en vue d’aider la population canadienne à prévoir les inondations et à s’y préparer.
https://geo.ca/about-us/nrcan/
https://geo.ca/fr/a-propos-de-nous/ressources-naturelles-canada/
Thank you,
Andrea

**Comment by jaredkinger** [comment]
@Andrea-Merry @heamart @jennywilsonsewell Would anyone be available and willing to implement these changes today on https://wordpress.dev.geo.ca? If we can get these changes done today they can be included in the upcoming release.

Login would be here: https://wordpress.dev.geo.ca/wp-login.php

**Comment by heamart** [comment]
@jaredkinger will do

**Comment by heamart** [comment]
Done

**Comment by Andrea-Merry** [comment]
Completed and checked on EN and FR
