### ISSUE TITLE
Old logo on Getting Started Page

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#189]
@sean-eagles @jaredkinger @heamart 
Hi.
On the Getting Started page (https://geo.ca/getting-started/) below the Explore GEO.ca’s Discover tab title there is an old GEO.ca logo in the screenshot. A new screenshot with the new logo needs to be added.

Same on the French page https://geo.ca/fr/pour-commencer/
Thank you,
Andrea

**Comment by jaredkinger** [comment]
Screenshots for English and French have both been updated. Links to dev are below:

- [Getting Started EN](https://wordpress.dev.geo.ca/getting-started/)
- [Getting Started FR](https://wordpress.dev.geo.ca/fr/pour-commencer/)

**Comment by Andrea-Merry** [comment]
Looks great. Will this be included in the release this week?

**Comment by jaredkinger** [comment]
@Andrea-Merry Yes, this will be included in the release this week.

**Comment by Andrea-Merry** [comment]
Completed and checked on EN and FR
