### ISSUE TITLE
GeoAI page (GeoBase project)

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#195]
New dataset and project to be released in the fall as part of GeoBase Initiative

- Would like a page to describe the work and show maps with use-case examples

**Comment by heamart** [comment]
Draft is available in wordpress. @jaredkinger please check it if possible, I can then provide a link to the owner to review. It also needs to link from the GeoBase initiative page. On the GeoBase initiative page the following update needs to be done as well:

In the Dataset Gallery, there is a placeholder for "Automatically Extracted Features". This will be updated to:
Title: GeoAI
Description: Learn about and download the time-enabled automatically extracted feature series, GeoAI, and stay up to date on new releases.

Thanks!

**Comment by jaredkinger** [comment]
@heamart The draft looks good to me. I've set the status to published so it can be shared. Link here: https://wordpress.dev.geo.ca/initiatives/geobase/geoai/

I updated the GeoBase page for this too. I've made a note that we may need to reverse this for the upcoming release.

**Comment by heamart** [comment]
A few more text edits are to come. Will update github when ready

**Comment by jaredkinger** [comment]
This page has been updated with the latest content on dev.

EN: https://wordpress.dev.geo.ca/initiatives/geobase/geoai/
FR: https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/geoia/

A link to the metadata is still needed.

**Comment by heamart** [comment]
Yes, last thing we are waiting on is the metadata link. It should nearly be ready.
There is also one small change to the text on the english page, in the header can "time-enable" be updated to "time-enabled"?

**Comment by jaredkinger** [comment]
> Yes, last thing we are waiting on is the metadata link. It should nearly be ready. There is also one small change to the text on the english page, in the header can "time-enable" be updated to "time-enabled"?

This has been updated.

**Comment by Andrea-Merry** [comment]
QC and QA completed in EN and FR for this page. Great work! No mistakes found.

**Comment by heamart** [comment]
@jaredkinger the GeoAI metadata link now available to add to that placeholder on the page under Map and Dataset gallery:

ENG: https://app.geo.ca/result/en/geoai---geobase-series?id=74738ff5-5367-5958-9aee-98fffdcd1876&lang=en
FRE: https://app.geo.ca/result/fr/g%C3%A9oia---s%C3%A9rie-g%C3%A9obase?id=74738ff5-5367-5958-9aee-98fffdcd1876&lang=fr

**Comment by jaredkinger** [comment]
@heamart I've updated the links on the GeoAI page for the Feature Series and also updated the button on the Data Index Map page. These updates have been pushed over to staging.

**English**
https://stage.geo.ca/initiatives/geobase/geoai/
https://stage.geo.ca/initiatives/geobase/geoai/data-index-map/

**French**
https://stage.geo.ca/fr/initiatives-fr/geobase/geoia/
https://stage.geo.ca/fr/initiatives-fr/geobase/geoia/carte-index-des-donnees/

**Comment by heamart** [comment]
@jaredkinger just realized the french map (carte-index-des-donnees) is using the english basemap. Is there still time to correct it?

**Comment by jaredkinger** [comment]
@heamart I updated the basemap and pushed this change to staging.
