### ISSUE TITLE
Update schema.org Publisher URL

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#197]
_Natural Resources Canada - Ressources Naturelles Canada_ is listed as the name of the publisher but the URL currently points to https://geo.ca. The URL should be updated to https://natural-resources.canada.ca/ and https://ressources-naturelles.canada.ca/ for the French version.

**Comment by jvanulde** [comment]
Hopefully, this change doesn't trigger a "phishing" warning 🤞

**Comment by jaredkinger** [comment]
> Hopefully, this change doesn't trigger a "phishing" warning 🤞

It shouldn't. The schema data isn't something a user interacts with directly and it's not tricking a user into anything either. It's more like citing the source/owner of the content.
