### ISSUE TITLE
Menu items to be removed

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#199]
@bo-lu @jvanulde @heamart @jaredkinger @sean-eagles 
Good morning,
As discussed at our last meeting, the following mega menu items under Discover/By Content Type should be removed: Datasets (Inaccurate. Shows 2348 records when there are over 6000 records), Community (There are no communities to be filtered. 0 results. Communities can be found under Collaborate in the menu), and Services (not useful).
Thank you,
Andrea

**Comment by jaredkinger** [comment]
This has been updated on https://wordpress.dev.geo.ca. The requested items have been removed the mega menu as well as the footer links for both English and French.

**Comment by Andrea-Merry** [comment]
Looks good. Thank you Jared.

**Comment by Andrea-Merry** [comment]
Completed and checked on EN and FR.
