### ISSUE TITLE
MapML Project 

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#202]
The MapML team has approached us to initiate setting up an initiative web presence.  Contact has already been initiated, and contacts are Peter Rushforth and Aliyan.

Deliverables:
- [ ] MapML Initiative web presence on GEO.ca

@Andrea-Merry @heamart .

**Comment by sean-eagles** [comment]
Map ML - July 11, 2023
Attendees: Heather Martin, Andrea Merry, Peter Rushforth, Aliyan Haz, Jared King, Sean Eagles
Timeline?
•	2021 started working on a presence.
•	Last July site was developed and sent through to staging.
•	At this point there is a need to start over
What is MapML working on?
•	Maybe begin with a static page (bilingual project summary possible)
•	Map review site (using GeoServer – connects to all different types of content)
•	MapML is an extension of HTML that supports spatial data.
•	Similar to a WMS being served out.
•	CGDI – harvesting external content (eventually hook these up and serve out as MapML)
•	https://mapml-dev.services.geo.ca/ (page of served up services, geoserver)
Requirements
•	Approvals for content owners in the hands of content owners (Director level)
•	Translation in the hands of content owners
•	Need to get content from DEV to STAG to PROD
•	Links to live examples would be great.
•	Link off to w3c examples (try to get more people involved in this effort)
•	Keep the webpage and content user friendly.
•	Link off to documentation website (already bilingual)
•	Fine tuning the page (Content Team)
•	Tutorial to be kept from NRCan page (link off)
•	Design work with Vlad/content team

**Comment by sean-eagles** [comment]
* look and feel of mapml-dev.services.geo.ca is a bit out of date.  We should / can update the logo easily at this time, but the headers and footers should wait on an update to the main site navigation
* “mapml.geo.ca” could have a similar relationship to the main site as does app.geo.ca today. That is, the MapML services will still need to run in their own AWS environment surrounding GeoServer.  The main geo.ca generated site can link out to the dynamic MapML GeoServer services, treating the MapML geo.ca resources like the GeoBase “initiative”, potentially with its own landing page on geo.ca, which would link out to mapml.geo.ca.
* we will still need to work through the CIOSB security folks to get “mapml.geo.ca” up and running in AWS production.
* we should start a regular weekly telecon to try to get the project on track

**Comment by sean-eagles** [comment]
MAPML Community Meeting Notes

•	Great content for a GEO.ca Initiative rather than a Community page (see GeoBase initiative example: [https://geo.ca/initiatives/geobase/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeo.ca%2Finitiatives%2Fgeobase%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C8c765b702c4043e1901308db7d7bd58f%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638241743034329945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tWQcRLWG3ZuvflCLxCZ36%2FcmschGCV3yQW%2FJkS7vva8%3D&reserved=0))
•	GEO.ca page would link to interactive community space here: W3C MapML Community - [https://www.w3.org/community/maps4html/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.w3.org%2Fcommunity%2Fmaps4html%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C8c765b702c4043e1901308db7d7bd58f%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638241743034329945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FDb%2BMbcJsk8kjvTyGmgJ1cWsxJR7fyTpfoOY03iV%2FGM%3D&reserved=0)
•	Dev site content created: [https://mapml-dev.services.geo.ca/mapml/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmapml-dev.services.geo.ca%2Fmapml%2F&data=05%7C01%7Csean.eagles%40NRCan-RNCan.gc.ca%7C8c765b702c4043e1901308db7d7bd58f%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638241743034329945%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nd1E8jCGxJW2m0Y9s71RKK6coY9UwLAyleRKJ%2Fg2Xc0%3D&reserved=0)
•	Parts of MapML are backed by GeoServer
•	Replace current site geogratis.ca/mapml/en (using GeoServer, MapML Dev) with new page on GEO.ca
•	System documentation is available (GitHub)
•	GeoServer (forked NRCan GitHub)
•	CloudFormation stack, Amazon S3
•	Improve GeoServer module to proxy any web map service as MapML nexus for CGDI
•	Content will go into WordPress (not a static site) to add content on a needed basis
•	Not really much static content, mainly dynamically generated based on system metadata
•	Embed as web app into GEO.ca as step #1,
•	GeoServer is Geospatial CMS, hooking regular CMS into it metadata is recorded in the data directory, XML specific to GeoServer to add/remove layers to service
Next steps:
•	Check if app integration is it technically feasible – Joost/Sean/Jared 
•	Create new Initiative landing page, based on dev: - Content and Engagement team (Jen, Gail, Andrea, Heather, Jenny)
•	WordPress content changes, request and have the content team edit (Jared)

**Comment by sean-eagles** [comment]
Map ML will be owned by CGDI.  a template for CGDI will used to prepare MapML's web presence.

**Comment by jaredkinger** [comment]
The current draft for the MapML project page is available on dev here: https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/mapml/

All images are currently placeholders. The MapML team will be providing layers to be used in the live demo.

**Comment by Andrea-Merry** [comment]
@sean-eagles @jaredkinger @heamart 
Hi, Heather and I met this morning to review what Aliyan had provided for the MapML page.  It is ready to go. Let me know if you have any questions. 
Thank you in advance.
Andrea and Heather
[GEO.CA MapML Content v.1.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12752601/GEO.CA.MapML.Content.v.1.docx)

**Comment by jaredkinger** [comment]
The [MapML page](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/mapml/) has been updated with the latest content.

**Comment by Andrea-Merry** [comment]
Thank you! Looks great.

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart 
Good morning,
Please see the attached approved content for the MapML page for the December release. Let me know if you have any questions. 
Thank you,
Andrea
[CGDI - MapML Splash Page EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13546726/CGDI.-.MapML.Splash.Page.EN.docx)
[CGDI - MapML Splash Page FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13546728/CGDI.-.MapML.Splash.Page.FR.docx)

**Comment by jennywilsonsewell** [comment]
@Andrea-Merry @jaredkinger @heamart

I've created a [French MapML page](https://wordpress.dev.geo.ca/fr/initiatives-fr/mapml-langage-de-balisage-de-carte/) and I've updated the [English](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/mapml/) content.

Thank you,
Jenny
