### ISSUE TITLE
Initial UX Review

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#203]

**Comment by vgulyy** [comment]
Overall Scope - Conduct a thorough review of GEO.ca to understand the structure, content, and any unique features of each from a UX perspective. Assess the current search functionality and accessibility according to WCAG guidelines to identify deficiencies on GEO.ca. 

Breakdown
Sub Ticket - GIT 204- Evaluating current user experience of GEO.ca 
Sub Ticket - GIT 205- Accessibility audit (WCAG compliance) 
Sub Ticket - GIT 206- Identifying pain points and areas for improvement

**Comment by sean-eagles** [comment]
Issue has been completed.

**Comment by sean-eagles** [comment]
Still two subtickets to complete.  Delivery is tentatively set for next week, mid October.

**Comment by sean-eagles** [comment]
Mid October delivery completed.
