### ISSUE TITLE
Caribou Ranges curated map - configuration file web service update

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#208]
There is a broken web service on the caribou ranges configuration file under Environment Theme: https://geo.ca/environment/

Data owner has notified that the caribou habitat ranges datasets can be updated to this one: https://open.canada.ca/data/en/dataset/c3d1771f-fa10-4a09-ba6e-dece0ceb5f37

Description text for the map will need to be slightly adjusted to:

Discover Canadian geographic ranges of the priority species identified under the Pan-Canadian Approach for Transforming Species at Risk Conservation in Canada. This features dataset displays caribou habitats, as well as four classifications of conservation areas in Canada.

**Comment by heamart** [comment]
@JeffreyAshtonNRCan emailed the updated config files and this will be the new title and text needed:

Title: Priority Species at Risk Ranges
Description: Discover Canadian geographic ranges of priority species identified under the Pan-Canadian Approach for Transforming Species at Risk Conservation in Canada. This features dataset displays the priority species' habitats, as well as four classifications of conservation areas in Canada.

**Comment by JeffreyAshtonNRCan** [comment]
Updated config files, title and text added for Priority Species at Risk Ranges map in the Environment theme.  Changes will be included in next release (late Ocotober).
