### ISSUE TITLE
GEO.ca homepage wrong background

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#209]
@jaredkinger @sean-eagles 

when language selection page loads an initial background image (some map) flashes briefly before changing to the tree video background.

Could this be fixed?

**Comment by jennywilsonsewell** [comment]
![video-poster](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/137412376/ae883000-82cc-4368-b711-20c19c19727d)

**Comment by jaredkinger** [comment]
@heamart Absolutely. What you're seeing is a placeholder image so that the screen isn't blank while the video loads. The placeholder should be the first frame of the video though so you don't get a weird flash. I will get this updated and it should look a lot smoother.

**Comment by jaredkinger** [comment]
The background image has been updated for the language selection page and the home page in both English and French.

**Comment by Andrea-Merry** [comment]
Completed and checked on EN and FR.
