### ISSUE TITLE
Earthquake Catalogue is not included in the Emergency Theme

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#21]
Offending record: https://app.geo.ca/result?id=085024ac-5a48-427a-a2ea-d62af73f2142&lang=en

I noticed a couple of things:

1. The datasets that are part of that collection are not linked
2. The record is not included in the emergency theme

**Comment by bo-lu** [comment]
Hi Joost,

The uuid has been added to the emergency theme on dev:

![image](https://user-images.githubusercontent.com/18405829/191314646-e6bcbcce-aab1-475c-83a1-fcbe5e9d881b.png)

**Comment by jvanulde** [comment]
Once this has been pushed to PROD we can close.

**Comment by bo-lu** [comment]
For #2, an API is ready to display child records. E.g., https://geocore-dev.api.geo.ca/collections?uuid=085024ac-5a48-427a-a2ea-d62af73f2142

And if the record is a child record, display its parent and siblings. E.g., https://geocore-dev.api.geo.ca/collections?uuid=26c57e53-2646-491b-b385-5813b23d8a96
