### ISSUE TITLE
Add pagination  with STAC harvesting workflow and on "Related Product" UI

### ISSUE THREAD

**Issue by xinli-cai** [Canadian-Geospatial-Platform/geo.ca#210]
Description from Jean-François Bourgon: 

We found out that some of the STAC content available from our production facing STAC API endpoint are now accessible through the geo.ca website. However only a partial coverage seems available for the HRDEM mosaic data as about 30 datasets are currently discoverable (out of ~400)  https://app.geo.ca/?keyword_only=&theme=&lang=en&foundational=&type=&keyword=hrdem 

Is there any particular reason behind this. I'm suspecting this could be a potential paging issue as our API returns only the first 30 records if no limit is set, however pagination through the next link is supported. We are asking because we would like to promote a direct access to the COG files for HRDEM for some specific users and geo.ca would offer a nice and direct way for that. Thank you!

Actions required for this issue: 
- [x] Investigate cause for the issues (an update failure on our side or pagination is no implemented)
- [x] Implement paginations in the harvesting flow for stac collection with 30+ items 
- [x] Update UI and add pagination in "Related Product" 

Additional requirment: 
- [x] Unique title for HRDEM items based on the STAC fields and timestamp

**Comment by xinli-cai** [comment]
Upon further investigation, I found that the issue stems from the STAC pagination, which restricts the return to 30 records per page (more details can be found [here](https://github.com/radiantearth/stac-api-spec/blob/main/ogcapi-features/README.md#item-pagination)). 

Pagination is now implemented on dev.geo.ca for the CCMEOSTAC records and the entire item list is retrievable. As an example, the HRDEM section now displays [397 datasets ](https://app-dev.geo.ca/result/en/collection---canada-wide-vegetation-biophysical-parameters-from-medium-resolution-satellite-imagery?id=ccmeo-root-Franklin-STAC-API&lang=en). Commits [here](https://github.com/Canadian-Geospatial-Platform/stac-to-geocore/commit/de022975772e1611083e58c6ee7a6b62b2f7984c). 

This also introduces a UI challenge to effectively linking multiple Parent/Child records for extensive data collections. To address this, we will need to make UI modifications in the 'RELATED PRODUCTS' section.
FYI @bo-lu @johnweng001

**Comment by bo-lu** [comment]
![mockup_210](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/18405829/899b4a96-eed7-4da1-885a-0d5af3d25d94)

Here is a mockup. I propose if there are >10 related items then this button is displayed. Once clicked, it will show the next 10 related items. Also give users the options to 'Show less'.

**Comment by johnweng001** [comment]
Discussed with @bo-lu , we will add a pagination if the records num >10 instead of 'view more/show less'

**Comment by bo-lu** [comment]
Pagination on UI "Related Product"

**Comment by xinli-cai** [comment]
Further improvement on CCMEO STAC to GeoCore mapping is suggested by the datacube team: 
- [x] Mapping STAC entity to GeoCore Data Resources' - 'Type' (currently is unknown) 
- [x] Mapping STAC entity to GeoCore Data Resources' - 'Format' (we will combine HNAP codelist and STAC media types)  
- [x] Unique title for HRDEM items based on the STAC item id. 
Create a new issue #245 for these requirements

**Comment by xinli-cai** [comment]
Changes deployed to dev and stage: https://app-stage.geo.ca/result/en/collection---mosaic-of-high-resolution-digital-elevation-model-(hrdem)-by-lidar-acquisition-project?id=ccmeo-hrdem-lidar&lang=en
