### ISSUE TITLE
Changes to the Footer on GEO.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#211]
@jaredkinger @heamart 
Hi Jared,
We have some requested changes to the footer of GEO.ca. Is the footer and header something that Heather or I can do easily or is that something you would rather control since it is across the entire site?
Let me know. 
Here are the changes:
•	Under Learn remove Discover the Value of GEO, and Flood Mapping
•	Remove GeoBase under Discover by Organization.
Thank you,
Andrea

**Comment by jaredkinger** [comment]
@Andrea-Merry I'll take care of this one. I have to run another generation at the end of the day so I will make this change quickly and get this on staging today to be included in the release.

**Comment by Andrea-Merry** [comment]
Completed and checked on both EN and FR.
