### ISSUE TITLE
GeoAI - Web Services to be set up on external server

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#220]
Web services need to be set up for curated maps that will be used for the GeoAI Web presence.

**Comment by heamart** [comment]
Content owner is working on getting a web service for the Index of Files published

**Comment by sean-eagles** [comment]
Piper is hopefull that the web services will be set up for the curated map by the end of the week.

**Comment by sean-eagles** [comment]
Checked with Piper for when the service will be set up, will put up answer when received.

**Comment by sean-eagles** [comment]
Web service has been successfully put up through the DDR.  Issue is now closed.
