### ISSUE TITLE
GeoAI - mockups

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#223]
mockups for GeoAI web presence which will be used for implementation.

**Comment by heamart** [comment]
Text content is nearly ready - I want to try my hand at wordpress so I'll attempt to do the draft for this page

**Comment by heamart** [comment]
draft to use:
[GeoAI_EN_DRAFT_v2.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12739182/GeoAI_EN_DRAFT_v2.docx)

**Comment by heamart** [comment]
Text available and translated for the map page: https://wordpress.dev.geo.ca/initiatives/geobase/geoai/projects-map/ - to be renamed from GeoAI Project Map to GeoAI Data Index Map
[GeoAI Data Index Map_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12871596/GeoAI.Data.Index.Map_EN.docx)
[Carte-index des données GéoIA_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12871602/Carte-index.des.donnees.GeoIA_FR.docx)

**Comment by heamart** [comment]
Main GeoAI page text is finalized and french translation done, including images. There are a few text edits in the english (track changes) to be implemented.
Last thing we are waiting on is the metadata record link to add under the Map and Dataset Gallery.
[GeoAI_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12872709/GeoAI_EN.docx)
[GéoIA_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12872711/GeoIA_FR.docx)
