### ISSUE TITLE
GeoAI Data Index Map Page

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#224]
Setting up curated maps with the viewer (GeoView or RAMP) on the GeoAI web presence.

**Comment by sean-eagles** [comment]
Still waiting on Map Service to be set up by GeoBase team.

**Comment by sean-eagles** [comment]
Piper sent the UUID and URLs for the services set up by DDR.  @jaredkinger could you please look at what was sent by email and see if you can load this on the proper page?

**Comment by jaredkinger** [comment]
This page has been updated with the latest content.

EN: https://wordpress.dev.geo.ca/initiatives/geobase/geoai/data-index-map/
FR: https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/geoia/carte-index-des-donnees/

All that is remaining is to update the dataset link.
