### ISSUE TITLE
Initiative: CGDI  

### ISSUE THREAD

**Issue by elatsis** [Canadian-Geospatial-Platform/geo.ca#226]

**Comment by jaredkinger** [comment]
A draft page has been created on dev here: https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/

The content team is currently reviewing the content submitted from CGDI. I will update the page once the content has been finalized.

**Comment by Andrea-Merry** [comment]
@jaredkinger @sean-eagles @heamart 
Hi, 
Heather and I met this morning to review a couple of edits made by the CDGI team for their landing page and the user needs assessment page. I forwarded you an email from Aliyan asking about the filter option for their page like the one done by GeoBase. I wasn't sure of the answer or how to implement. Both pages are ready, except there is a map on the CDGI page that will need to be replaced with an image or a bilingual map. I will send it to you once the CDGI team gets back to us. Let me know if you have any questions or if you want to meet to discuss. I also included the images for the user needs assessment page.
Thank you,
Andrea and Heather
[CDGI User Needs Assessment Wordpress content DRAFT v3.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12752639/CDGI.User.Needs.Assessment.Wordpress.content.DRAFT.v3.docx)
[CGDI wordpress content DRAFTv.3.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12752643/CGDI.wordpress.content.DRAFTv.3.docx)
![ClimateChange_starterkit](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112396545/da4d088a-d394-4474-ada9-d01b45032026)
![Hydro_starterkit](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112396545/2238ca5b-63f8-4a54-87ab-93817cce02c0)
![NWT_starterkit](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112396545/969e75a7-52f3-40fb-a462-a7a9234e2155)
![BC_starterkit](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112396545/789937d9-e6df-4c0f-a713-b2726ea132eb)

**Comment by jaredkinger** [comment]
I've added the [CGDI page](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/) and the [User Needs page](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/addressing-cgdi-needs/) to Dev.

**Comment by Andrea-Merry** [comment]
Looks great! Thank you Jared.

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart 
Good morning,
The CDGI content is approved and ready to be published. Please see attached documents for implementation. Let me know if you have any questions. I will add the MapML documents to the MapML issue.
Thank you,
Andrea
[CGDI Splash Page EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13546685/CGDI.Splash.Page.EN.docx)
[CGDI Splash Page FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13546686/CGDI.Splash.Page.FR.docx)

**Comment by jennywilsonsewell** [comment]
@Andrea-Merry @jaredkinger @heamart

I've created a [French CGDI page](https://wordpress.dev.geo.ca/fr/initiatives-fr/infrastructure-canadienne-de-donnees-geospatiales-icdg/) and I've updated the [English](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/) content.

Thank you,
Jenny

**Comment by Andrea-Merry** [comment]
@jaredkinger @jennywilsonsewell @heamart 
On the French page it says Maps for HTML. It will need to be changed to Cartes pour. Also it says 1 enregistrements. Enregistrements should be singular. Same on the English page. 1 records changed to 1 record.

**Comment by jennywilsonsewell** [comment]
@Andrea-Merry @heamart @jaredkinger 
"Maps for HTML" has been changed to "cartes pour HTML", as per Cameron Wilson's instruction. Will update if team requests to change.

**Comment by jaredkinger** [comment]
@Andrea-Merry @heamart @jaredkinger

I pushed an update to resolve the issue of singular/plural text for the number of records found.

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart 
QC Complete. However Maps for HTML needs to be changed to Cartes pour HTML on the FR page.
Thank you
Andrea

**Comment by jaredkinger** [comment]
@Andrea-Merry This has been updated on staging. https://stage.geo.ca/fr/initiatives-fr/infrastructure-canadienne-de-donnees-geospatiales-icdg/

**Comment by Andrea-Merry** [comment]
@jaredkinger Thank you. Checked and good to go.
