### ISSUE TITLE
Initiative Page

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#228]
@jaredkinger @Andrea-Merry @sean-eagles 

New landing page for initiatives. Attached is a draft for the english page.
Contemplating adding a section to pull out featured initiative tools/resources (will update if we go ahead with this)

Is it possible to add this to the mega-menu as well? under Discover > By Content Type > Initiatives
Then added to the footer as well.

[Initiatives_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12664120/Initiatives_EN.docx)

**Comment by jaredkinger** [comment]
### Requirements
- [x] Add Initiatives EN page
- [x] Add Initiatives link to EN mega menu
- [x] Add Initiatives link to EN footer menu
- [x] Add Initiatives FR page
- [x] Add Initiatives link to FR mega menu
- [x] Add Initiatives link to FR footer menu

**Comment by jaredkinger** [comment]
@heamart The initiatives pages is now available on dev here: https://wordpress.dev.geo.ca/initiatives/ Links have been added to the mega menu and the footer menu.

I've created the page for CGDI but will wait until the content is finalized before completing it.

**Comment by sean-eagles** [comment]
The new page looks good, keep up the good work everyone!

**Comment by heamart** [comment]
French translation for the initiatives page:
[Initiatives_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/12794576/Initiatives_FR.docx)

**Comment by jaredkinger** [comment]
I've added the French translations for the Initiatives page here: https://wordpress.dev.geo.ca/fr/initiatives-fr/ and updated both the mega menu and footer menu accordingly.

**Comment by jaredkinger** [comment]
The changes to the menus have been rolled back but will be reimplemented after the release.

**Comment by heamart** [comment]
We'll be good to go on this page for the release since CGDI has submitted their content. 

Updates to the initiative page, will get the French version of the updates soon.
There are some text edits to what was already created (see track changes). Then there is an added Tools section.
Thumbnails have all been used at some point for the pages they link to.
[Initiatives_EN (1).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13547872/Initiatives_EN.1.docx)

**Comment by jennywilsonsewell** [comment]
@heamart @Andrea-Merry @jaredkinger 
Alongside the text edits, I've added the "On This Page" section as well as the "Select Tools and Products" section with three new cards to the [English Initiatives page](https://wordpress.dev.geo.ca/initiatives/).

**Comment by heamart** [comment]
@jaredkinger 
The last section for tools, could we adjust so the headers line up? if it is an issue with the image used for the flood mapping inventory, this could be switched out to this one: (has been used on the flood mapping page)
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/107938467/373eb679-f571-45b1-ba38-570bbc725f45)

**Comment by heamart** [comment]
updated french page. Small text changes may come later today
[Initiatives_FR_v1.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13619296/Initiatives_FR_v1.docx)

**Comment by jaredkinger** [comment]
@heamart 
I've updated the [French Initiatives page](https://wordpress.dev.geo.ca/fr/initiatives-fr/) and swapped out the Flood Mapping icon for the image above to correct the alignment issues.

**Comment by heamart** [comment]
minor text edits to the french in track changes:
[Initiatives_FR_v1.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13620763/Initiatives_FR_v1.docx)

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart 
QC complete. On FR initiative page there should be a . After y contribuer in the MapML box. It was forgotten in the draft.

**Comment by jaredkinger** [comment]
@Andrea-Merry This has been updated on staging.

**Comment by Andrea-Merry** [comment]
@jaredkinger Awesome. Checked and good to go.
