### ISSUE TITLE
Internal review with the team and adjustments based on feedback

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#232]
Internal review with the team and adjustments based on the feedback (eg. development feasibility, SEO consideration etc.)

**Comment by vgulyy** [comment]
![Active Alerts Page](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/94e683c6-d678-4955-a8fb-69a0d1ee9dc9)
![Administration Theme](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/40bb5180-7f0c-4173-a789-6403a79976b6)
![Bookmarked Maps-Page](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/606be64f-3a00-433d-a53e-ee067c202888)
![Flood Mapping Page About](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/14acbecb-ed1f-44f6-9199-76371a613cba)
![Flood Mapping Page](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/a3ea6f07-9430-40f0-a469-914684f8bfef)
![Full Screen](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/b9b0ed92-983d-4be7-8bab-5120bad857ce)
![Geo ca-Wireframe](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/0a3305e0-1364-4ff0-a9ac-4619b3ac5669)
![GeoAI](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/c64ec98e-353a-40e8-a264-8328fe2d3718)
![Historical Flood Events](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/38eb8739-a074-4d47-a23a-dc661684fced)
![Home Page - Active Alert](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/a23a2864-a75e-4031-ba33-dbd7de11a365)
![Home Page](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/4a9b3ec8-311a-468a-9962-c83ec7e71dd9)
![Metada-Page-app geo ca](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/2f553364-7b89-4fd8-85b8-056f756374bf)
![Notifications Page](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/3fcd8936-497c-4924-9488-667c017a6c51)
![Search Results - NO RESULTS](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/910f5666-4720-4b06-97ac-dcaff30878ef)
![Search Results Map View](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/aa1a7d20-4bf5-4532-aa28-f6c0eb11c216)
![Serch Results](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/121049163/8c98630e-7a7e-4630-b89f-e49bc921ac23)

**Comment by sean-eagles** [comment]
Internal review is completed.  people can still use this ticket if needed, archive of screenshots.
