### ISSUE TITLE
Imagery Theme: HRDEM map server error

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#241]
The HRDEM map points to https://geoappext.nrcan.gc.ca/arcgis/rest/services/NRCAN/coverage_HRDEM_en/MapServer which causes a CORS policy issue. The map server should be updated to the redirect URL here: https://maps-cartes.services.geo.ca/server_serveur/rest/services/NRCan/coverage_HRDEM_en/MapServer

Is layer 4 the correct layer for the map?

**Comment by bo-lu** [comment]
I had some time today to play around and, yes, I believe layer 4 is correct. Here is what layer 4 looks like:
![4](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/18405829/14077f98-fe64-49bf-92de-262dafa5c21e)

**Comment by jaredkinger** [comment]
Map server for the HRDEM- CanElevation Series has been updated  on the English and French Imagery pages

https://wordpress.dev.geo.ca/imagery/
https://wordpress.dev.geo.ca/fr/imagerie/
