### ISSUE TITLE
Creating high fidelity wireframe/prototype

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#250]
creating a prototype that users can test.

**Comment by vgulyy** [comment]
[Part1.zip](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14607568/Part1.zip)

**Comment by vgulyy** [comment]
[Part2.zip](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14607571/Part2.zip)
