### ISSUE TITLE
Economy Leaflet map issues

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#26]
•	Theme Économie >> map: Ententes minières avec les Autochtones (actives) >> wrong preview map (first nation location)
•	Theme Economy >>  map: Indigenous Mining Agreements (Active)  >> wrong preview map (basemap?)

**Comment by indiciumx** [comment]
Fixed.

**Comment by sean-eagles** [comment]
Both French and English are showing the Indigenous Mining Agreements image properly, and load over to maps upon click fine.
