### ISSUE TITLE
GeoAI - update to GeoBase page

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#267]
@jaredkinger @sean-eagles @Andrea-Merry 
Text and link are available now to add to the existing placeholder "Automatically Extracted Features" under the GeoBase Gallery.
The thumbnail will remain the same. It will link to the GeoAI page

English:
Title: GeoAI
Description: Learn about and download GeoAI, the time-enabled data created using Artificial Intelligence (AI).

French:
Title: GéoIA 
Description: Découvrez et téléchargez GeoAI, les données temporelles créées à l'aide de l'intelligence artificielle (IA).

**Comment by jaredkinger** [comment]
Gallery has been updated on dev.

EN: https://wordpress.dev.geo.ca/initiatives/geobase/
FR: https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/

**Comment by Andrea-Merry** [comment]
Thanks Jared
