### ISSUE TITLE
Cartographie des Inondations Page Update

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#268]
https://geo.ca/fr/cartographie-inondations/
We need to change all the ' cartographie des inondations' wording for 'des zones inondables'

1. in the banner text and the link:
Cartographie des zones inondables
Les fournisseurs canadiens de données géospatiales fédérales, provinciales et territoriales collaborent pour fournir des outils et des ressources en vue d’aider la population canadienne à prévoir les inondations et à s’y préparer.
2. The text below: 
À propos de la cartographie des zones inondables au Canada
Les inondations sont la catastrophe naturelle la plus coûteuse au Canada. Chaque année, elles causent en moyenne plus d’un milliard de dollars de dommages directs aux habitations, aux biens et aux infrastructures. Les catastrophes naturelles sont de plus en plus fréquentes et de plus en plus graves.
3. (remove the last sentence):
Les fournisseurs canadiens de données géospatiales fédérales, provinciales et territoriales collaborent pour fournir des outils et des ressources en vue d’aider la population canadienne à prévoir les inondations et à s’y préparer.
4. first box new title text: En savoir plus sur la cartographie des zones inondables
5. first box new text: Les cartes des zones inondables montrent le territoire qui pourrait être recouvert par l'eau ou les zones atteintes lors d’une inondation passée.
6. second box new title text: La cartographie des zones inondables et le gouvernement du Canada
7. second box new text: Le gouvernement du Canada investit pour aider la population canadienne à mieux prévoir les inondations et à s’y préparer. Découvrez comment il contribue à la production des cartes des zones inondables.
8. third box new title text: Cartographie des zones inondables dans votre province ou territoire
9. third box new text: Les provinces et les territoires sont responsables de la cartographie des zones inondables et de la gestion des aléas d’inondation. Consulter les ressources en matière de cartographie des zones inondables propres à votre province ou à votre territoire.

Merci!!! If you need more info, please reach me or @laurasalisbury 

@laurasalisbury so you know

**Comment by jaredkinger** [comment]
This page has been updated on Dev here: https://wordpress.dev.geo.ca/fr/cartographie-inondations/

**Comment by Andrea-Merry** [comment]
QC Complete on staging
