### ISSUE TITLE
Emergency Theme Map issues

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#27]
•	Theme Emergency >> map: Earthquakes in Canada  >> both title and "Full Map" link to the Dataset page, not to the map directly
•	Same problem for the French version
•	Theme Emergency >> map: National Fire Database – Agency Provided Fire Perimeters  >> both title and "Full Map" link to a map with only basemap, no thematic layer displayed
•	Same problem for the French version

**Comment by indiciumx** [comment]
Earthquakes in Canada currently points to a record without a map. There are plenty of other "Earthquakes in Canada" but I'm not sure which one to choose. @Andrea-Merry

**Comment by indiciumx** [comment]
@jvanulde is Risk Profiler ready to rock, we could change it up with that

**Comment by Andrea-Merry** [comment]
@indiciumx I am not sure which map to use for Earthquakes. If you can replicate the full map that would be great.

**Comment by jvanulde** [comment]
OpenDRR has Earthquake scenarios: https://opendrr.github.io/earthquake-scenarios/ 

The service endpoints are not published on that site yet, but we do have them and they are available via the Earthquake Scenario Catalogue collection in the FGP.

For example: https://gcgeo.gc.ca/geonetwork/metadata/eng/9a1d59b4-da0b-4792-a645-44b4ef70a219

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/27?planning-poker) with Zenhub @indiciumx

**Comment by jvanulde** [comment]
@Andrea-Merry can you please provide new datasets to link to.

**Comment by Andrea-Merry** [comment]
@jvanulde Going to meet with Heather to look at options.

**Comment by Andrea-Merry** [comment]
@jvanulde @indiciumx Heather and I met and decided that you can switch the National Fire Database (currently links to nothing) for the Floods in Canada Archive - Inondations au Canada Archive. The Earthquake map is fine and the links work in both English and French.
https://app.geo.ca/map?rvKey=74144824-206e-4cea-9fb9-72925a128189 English
https://app.geo.ca/map?rvKey=74144824-206e-4cea-9fb9-72925a128189 French
Does this work?

**Comment by jaredkinger** [comment]
@Andrea-Merry I agree with switching out the National Fire Database for the Floods in Canada Archive. Can you provide a short description for the Floods in Canada Archive (EN and FR) that can use here?

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart No problem. I will do it most likely tomorrow. Meetings this afternoon.
Thank you.

**Comment by heamart** [comment]
@jaredkinger @Andrea-Merry here are title and descriptions we can use:

English:
Title: Floods in Canada - Archive
Description: View flood extent polygons and their footprints representing floods from previous years throughout Canada as monitored by Natural Resources Canada using satellite imagery for emergency response.

French: 
Title: Inondations au Canada – Archive
Description: Afficher les polygones d'étendue d'inondation et leurs empreintes représentant les inondations des années passées partout au Canada tel que cartographiées par Ressources naturelles Canada à partir d’imagerie satellitaire pour la gestion des urgences.

**Comment by jaredkinger** [comment]
@heamart @Andrea-Merry This has been updated on Dev.

English: https://wordpress.dev.geo.ca/emergency/

French: https://wordpress.dev.geo.ca/fr/urgences/

**Comment by heamart** [comment]
Looks good, Thank you!
