### ISSUE TITLE
Update to Homepage - In the Spotlight

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#272]
@jaredkinger @Andrea-Merry here are the updates to the homepage to squeeze in. 

Move GeoBase Initiative card to GEO New page, with date:
EN: April 20, 2023
FR: le 20 avril 2023

On the homepage replace the GeoBase card with GeoAI. Attached is the text, fr and en versions:

[GEO Home Page_EN (1).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13071634/GEO.Home.Page_EN.1.docx)
[GEO Home Page_FR (2).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13071635/GEO.Home.Page_FR.2.docx)

**Comment by jaredkinger** [comment]
Home page and the news page have both been updated for both English and French.

Home EN: https://wordpress.dev.geo.ca/home/
Home FR: https://wordpress.dev.geo.ca/fr/accueil/

News EN: https://wordpress.dev.geo.ca/geo-in-the-news/
News FR: https://wordpress.dev.geo.ca/fr/geo-dans-actualite/

**Comment by sean-eagles** [comment]
These look good Jared, good work!
