### ISSUE TITLE
Cartographie des inondations - Gouv Canada

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#274]
[https://geo.ca/fr/cartographie-inondations/gouvernement-canada/]

Change a couple of the inondations for zones inondables and couple of other text changes!

Header
OLD: La cartographie des inondations et le gouvernement du Canada
NEW: La cartographie des zones inondables et le gouvernement du Canada

Text under the header
OLD: Découvrez comment il contribue à la production des cartes d’inondation.
NEW: Découvrez comment il contribue à la production des cartes de zones inondables.

Title
OLD: Rôles du fédéral en matière de cartographie des inondations
NEW: Rôles du fédéral en matière de cartographie des zones inondables

Text under the title
OLD: Les provinces et les territoires sont responsables de la cartographie des inondations et des nombreux rôles liés à la gestion des risques d’inondation. Le gouvernement fédéral offre des ressources et du financement pour faire avancer la cartographie des inondations partout au Canada.
NEW: Les provinces et les territoires sont responsables de la cartographie des zones inondables et ont de nombreux rôles liés à la gestion des aléas d’inondation. Le gouvernement fédéral offre des ressources et du financement pour faire avancer la cartographie des zones inondables partout au Canada.

Top left box
OLD: Ressources naturelles Canada (RNCan) dirige les initiatives de cartographie des inondations et le Programme d’identification et de cartographie des aléas d’inondation (PICAI).
NEW: Ressources naturelles Canada (RNCan) dirige les initiatives de cartographie des zones inondables et le Programme d’identification et de cartographie des aléas d’inondation (PICAI).

Top right box and Bottom left box
No changes

Bottom right box
OLD: Relations Couronne-Autochtones et Affaires du Nord Canada (RCAANC) et Services aux Autochtones Canada (SAC) consacrent tous deux des fonds aux activités liées aux changements climatiques dans les collectivités des Premières Nations.
NEW:Relations Couronne-Autochtones et Affaires du Nord Canada (RCAANC) et Services aux Autochtones Canada (SAC) consacrent des fonds aux activités liées aux changements climatiques dans les communautés des Premières Nations.

Text under Sites connexes
OLD: Trouvez plus d’information sur les cartes d’inondation, les données connexes et les meilleures pratiques.
NEW: Trouvez plus d’information sur les cartes de zones inondables, les données connexes et les meilleures pratiques.

First box title
OLD: Guides d’orientation fédéraux sur la cartographie des zones inondables (Sécurité publique Canada)
NEW: Guides d’orientation fédéraux sur la cartographie des zones inondables

First box
OLD: Lisez la série des meilleures pratiques évolutives en cartographie des inondations qui fait avancer les activités de cartographie des zones inondables partout au Canada.
NEW: Lisez la série des guides d'orientation évolutifs en cartographie des zones inondables qui font avancer les activités de cartographie des zones inondables partout au Canada.

Text under Ailleurs sur Geo.ca
OLD: En savoir plus sur la cartographie des inondations
NEW: En savoir plus sur la cartographie des zones inondables

Text under En savoir plus sur la cartographie des inondations
OLD: Les cartes d’inondation montrent les zones qui peuvent être recouvertes par les eaux ou montrent les zones atteintes par les eaux lors d’une inondation spécifique.
NEW: Les cartes de zones inondables montrent les régions susceptibles d’être recouvertes par l’eau ou indiquent les zones atteintes lors d’inondations passées. Elles sont des outils essentiels qui peuvent nous aider à définir les risques et à atténuer l’incidence des inondations.

Text under Galerie de cartes et de données sur les inondations
OLD: Explorez les cartes d’inondations disponibles et les données techniques variées qui contribuent à la cartographie des inondations.
NEW: Explorez les cartes de zones inondables disponibles et les diverses données techniques qui contribuent à la cartographie des zones inondables.

**Comment by jaredkinger** [comment]
This page has been updated on Dev here: https://wordpress.dev.geo.ca/fr/cartographie-inondations/gouvernement-canada/

**Comment by Andrea-Merry** [comment]
QC Complete on staging
