### ISSUE TITLE
Cartographie des inondations - Province ou territoire

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#275]
Text changes

Header
OLD: Cartographie des inondations dans votre province ou territoire
NEW: Cartographie des zones inondables dans votre province ou votre territoire

Text under the Header
OLD: Renseignez-vous sur les activités de cartographie des inondations dans votre collectivité.
NEW: Renseignez-vous sur les activités de cartographie des zones inondables dans votre communauté.

First title
OLD: Rôles des provinces et des territoires en cartographie des inondations
NEW: Rôles des provinces et des territoires en cartographie des zones inondables

Text under first title
OLD: Les provinces et les territoires sont responsables de la cartographie des inondations et de nombreuses autres fonctions liées à la gestion des aléas d’inondation.

Certaines provinces ou certains territoires entreprennent eux-mêmes des études techniques et la cartographie des inondations, tandis que d’autres sous-traitent la cartographie des inondations au secteur privé. D’autres encore délèguent la cartographie des inondations à des entités comme les municipalités ou les offices de protection de la nature.

NEW: Les provinces et les territoires sont responsables de la cartographie des zones inondables et ont divers autres rôles dans la gestion des aléas d’inondation.

Certaines provinces ou certains territoires entreprennent des études techniques et la cartographie des zones inondables, tandis que d’autres sous-traitent la cartographie au secteur privé. D’autres encore délèguent cette cartographie à d'autres entités comme les municipalités ou les offices de protection de la nature.

Second title
OLD: Ressources de cartographie des inondations par province ou territoire
NEW: Ressources de cartographie des zones inondables par province ou territoire

Text under Sites connexes
First box title
OLD: En savoir plus sur la cartographie des inondations
NEW: En savoir plus sur la cartographie des zones inondables

First box text
OLD: Les cartes d’inondation montrent les zones qui peuvent être recouvertes d’eau ou que l’eau peut atteindre durant une inondation. Ce sont des outils essentiels qui peuvent nous aider à définir les risques et à atténuer l’incidence des inondations.
NEW: Les cartes de zones inondables montrent les régions susceptibles d’être recouvertes par l’eau ou indiquent les zones atteintes lors d’inondations passées. Elles sont des outils essentiels qui peuvent nous aider à définir les risques et à atténuer l’incidence des inondations.

Second box title
OLD: Galerie de cartes et de données sur les inondations
NEW: Galerie de cartes et de données sur les zones inondables

Second box text
OLD: Explorez les cartes d’inondations disponibles et les données techniques variées qui contribuent à la cartographie des inondations.
NEW: Explorez les cartes de zones inondables disponibles et les diverses données techniques qui contribuent à la cartographie des zones inondables.

**Comment by jaredkinger** [comment]
This page has been updated on Dev here: https://wordpress.dev.geo.ca/fr/cartographie-inondations/province-territoire/

**Comment by Andrea-Merry** [comment]
QC Complete
