### ISSUE TITLE
GeoAI Map Index page - web service not loading

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#276]
@jaredkinger @Andrea-Merry 
The web service is not loading in the viewer: https://geo.ca/initiatives/geobase/geoai/data-index-map/
It does not seem to be an issue with the service itself which does load on other sites.

**Comment by jaredkinger** [comment]
@heamart I am looking into this. It's quite strange as it was working when it was initially pushed to production. If you can share an example of it working on another site that may help me debug the issue. Thanks!

**Comment by heamart** [comment]
@jaredkinger here is an example on Open Maps: https://search.open.canada.ca/openmap/74738ff5-5367-5958-9aee-98fffdcd1876
Hopefully it can help.

**Comment by jaredkinger** [comment]
The webservice endpoint didn't changed but it looks like the layer type changed at some point after this was released to production. I updated the config and have the map displaying properly again on Dev.

EN: https://wordpress.dev.geo.ca/initiatives/geobase/geoai/data-index-map/
FR: https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/geoia/carte-index-des-donnees/

**Comment by jaredkinger** [comment]
This has been updated and resolved on production.

**Comment by Andrea-Merry** [comment]
QC complete on staging
