### ISSUE TITLE
Galerie de cartes et de données sur les inondations

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#287]
Text changes for https://geo.ca/fr/cartographie-inondations/galerie-cartes-inondations/

Old Title: Galerie de cartes et de données sur les inondations
New title: Galerie de cartes et de données sur les zones inondables

Old text below the title: 
Explorez la galerie des cartes d’inondation et des jeux de données pour connaître les données liées aux risques d’inondation, ainsi que d’autres informations qui approfondissent notre compréhension des inondations.
New text: 
Explorez la galerie des cartes et des jeux de données sur les zones inondables pour découvrir les données liées aux aléas d’inondation et les autres jeux de données qui approfondissent notre compréhension des inondations.

Under Sites connexes

Old text 1 box title: En savoir plus sur la cartographie des inondations
New text 1 box title: En savoir plus sur la cartographie des zones inondables

Old text 1 box :
Les cartes d’inondation montrent les zones qui peuvent être recouvertes par les eaux ou montrent les zones atteintes par les eaux lors d’une inondation spécifique. Ce sont des outils essentiels qui peuvent nous aider à définir les risques et à atténuer les conséquences des inondations.
New text 1 box :
Les cartes des zones inondables montrent le territoire qui pourrait être recouvert par l'eau ou les zones atteintes lors d’une inondation passée. Ce sont des outils essentiels qui peuvent nous aider à définir les risques et à atténuer les conséquences des inondations.

Old text 2 box title: Cartographie des zones inondables (Ressources naturelles Canada)
New text 2 box title: Cartographie des zones inondables

Old text 2 box : 
Le gouvernement du Canada investit pour aider les Canadiens à mieux planifier et se préparer aux futures inondations. Découvrez comment le gouvernement du Canada contribue à la production de cartes des inondations.
New text 2 box : 
Le gouvernement du Canada investit pour aider les Canadiens et les Canadiennes à mieux planifier et se préparer aux futures inondations. Découvrez comment le gouvernement du Canada contribue à la production de cartes des zones inondables.

@laurasalisbury

**Comment by Andrea-Merry** [comment]
QC complete on staging
