### ISSUE TITLE
Economy Theme: Targeted Investments in First Nations Community Infrastructure Map Server Moved

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#289]
The map server for the Targeted Investments in First Nations Community Infrastructure leaflet map server has been moved and the map is failing to load.

**Comment by jaredkinger** [comment]
I've updated the server on dev and this map is displaying again.

**Comment by Andrea-Merry** [comment]
QC completed on staging
