### ISSUE TITLE
Legal Map Issue

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#29]
•	Theme Legal >> map: Legislative Boundaries of Aboriginal Lands and Aboriginal Agreements >> “Full Map” links to an empty page: URL error (with extra ") [https://dev.geo.ca/wp-content/Viewer/config-int-LEGAL-iframe-map-en.html]

**Comment by indiciumx** [comment]
Extra quote at the end of URL

**Comment by jvanulde** [comment]
Fixed and available on DEV for review.

**Comment by sean-eagles** [comment]
Legislative Boundaries of Aboriginal Lands and Aboriginal Agreement;s title and full map when clicked go to the proper map.  Works in both languages.
