### ISSUE TITLE
Flood Mapping in your P/T - link updates

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#290]
Update to the [Flood Mapping in your P/T map](https://geo.ca/flood-mapping/province-territory/#yukon): new link to add under Yukon resources;
The change will be the addition for a link for their Flood Atlas:

English page:
Yukon Flood Resources
- Flooding Information
- Development of a tool for flood risk 
- [Flood Atlas](https://flood-atlas.service.yukon.ca/)

French page:
Ressources sur les inondations au Yukon
- [Information sur les inondations](https://yukon.ca/fr/floods)
- [Développement d'un outil pour l'évaluation des risques d'inondation au Yukon (anglais seulement)](https://www.yukonu.ca/research/projects/developing-tool-for-flood-risk-assessment)
- [Atlas des inondations](https://flood-atlas.service.yukon.ca/) (anglais seulement)

**Comment by jaredkinger** [comment]
@heamart I've updated this on Dev.

EN: https://wordpress.dev.geo.ca/flood-mapping/province-territory/#yukon
FR: https://wordpress.dev.geo.ca/fr/cartographie-inondations/province-territoire/#yukon

**Comment by Andrea-Merry** [comment]
QC completed on staging
