### ISSUE TITLE
ArcticSDI

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#292]
New page under the CGDI initiative.
Planned released by end of fiscal.

**Comment by heamart** [comment]
Here is the content for the english page:
[ArcticSDI_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13968660/ArcticSDI_EN.docx)

Here is the iframe code for the embedded map:
<iframe src="https://geoportal.arctic-sdi.org/?lang=en&uuid=092b5756-2054-4b57-b8ec-ec7b811435d8" allow="geolocation" style="border: none; width: 100%; height: 100%;"></iframe>

just fyi, some images may need to change. Just confirming a couple things.

**Comment by heamart** [comment]
on the CGDI landing page, Arctic SDI will also be added to the "explore CGDI higlights" section:

- For the image use the same that will be in the header on the arctic sdi page: [image url](https://unsplash.com/photos/white-and-brown-house-near-green-grass-field-and-mountain-under-blue-sky-during-daytime-Gr-ct5pXpj8)
- **Title:** Arctic Spatial Data Infrastructure (Arctic SDI)
- **Text:** Discover Arctic geographic data through this collaborative partner-based effort of the National Mapping Agencies of the Arctic.
- For the filters on that section:
     - add Data
     - Arctic SDI will be under both Data and Standards filters

**Comment by jaredkinger** [comment]
I've added a new page for [Arctic SDI](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/arctic-spatial-data-infrastructure/)

The [CGDI](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/) page has also been updated on dev.

**Comment by heamart** [comment]
small spelling update on the Arctic SDI page: Arctic is mispelled in #3 under On this page.

**Comment by jaredkinger** [comment]
@heamart The spelling was correct in the word doc so I must have typed this item out instead of copy/pasting. I've updated this to correct the typo. Thanks for catching this.

**Comment by heamart** [comment]
first set of changes from content owner:

- can the video be made smaller, maybe side by side with the intro paragraphs?
- Video url changed to:
   - EN: https://www.youtube.com/watch?v=RroKt2CbZyw
   - FR: https://www.youtube.com/watch?v=-BBrqil1alk

more changes to text and a couple images will be coming soon

**Comment by heamart** [comment]
Number of new changes to images, text, embedded map. 
If possible to make the video, embedded map smaller (not full page width) that would be great - suggestions are welcome in how set it up without looking odd. 

- New embedded map, with legend image:<iframe src="https://geoportal.arctic-sdi.org/?lang=en&uuid=cfa6a8ae-099e-408b-8e38-af3f0d3f844b" allow="geolocation" style="border: none; width: 800px; height: 800px;"></iframe>

- New header image: Same as photo for the "Arctic SDI Strategic Documents" under Resources
- New graphic with hyperlink in the Arctic SDI Geoportal section
- Resources section: text updates to all the cards

All changes available in the doc.
[ArcticSDI_EN_Changes_V2.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14222281/ArcticSDI_EN_Changes_V2.docx)

Translation and final approval still required. Easier for them to review when in dev.

**Comment by jaredkinger** [comment]
I've hidden the Arctic SDI page temporarily until we push the upcoming release to production. I also removed the mentions of Arctic SDI from the Initiatives page.

I did make some adjustments to the video and I found centering it with a smaller width produced the best outcome. Putting the video side by side with the text while doable doesn't provide a great user experience if you're interacting with the transcript. Centering the embed with a reduced width would likely also work here.

I'll make the new changes to Arctic SDI after the release and follow up once they are complete.

**Comment by jaredkinger** [comment]
The [Arctic SDI page](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/arctic-spatial-data-infrastructure/) is back up on dev including the new updates along with the changes to the [CGDI page](https://wordpress.dev.geo.ca/initiatives/canadian-geospatial-data-infrastructure/).

Let me know if the sizing/positioning of the video and embedded  map works or if additional changes are needed.

**Comment by heamart** [comment]
text changes under embedded maps:
- move the paragraph under the map to above
- then small updates to the text for that section:
  Using the Arctic SDI Geoportal you can create dynamic interactive maps, known as embedded maps, for your website in just a 
  few easy steps. 
  The example below shows the [permafrost](https://natural-resources.canada.ca/environment/science/indicators- 
  change/permafrost/11011) extent in the Arctic which is being impacted by the effects of Climate Change. For example, 
  melting permafrost that heaves buildings and roads while also releasing stores of methane gas that have been locked up for thousands of years.

Formatting changes:
- I'm not sure what the specs on the embedded map, but can we add a border or background to where the map is so it doesn't feel like it's floating? 
- Move the "Create you own Arctic SDI maps" to the left rather than the right.

**Comment by jaredkinger** [comment]
I've made the requested text updates. Let me know if got that correct.

I've changed the alignment of the "Create your own Arctic SDI maps" button to the left.

For the embedded map I can add a border but I can't change the map background color from my end. I've noticed that the map permafrost layers disappear depending on the size of the map and it looks like this is dependent on the zoom level. Zooming out one level seems to give a consistent experience across device sizes. Can we get the default zoom level of the embed changed?

**Comment by heamart** [comment]
on hold. will not be ready for march release

**Comment by jaredkinger** [comment]
@heamart Have you had any updates on this? Will we have the French translations in time for the release?

**Comment by heamart** [comment]
@jaredkinger no updates. It will not be for this release - no known timeline now

**Comment by heamart** [comment]
@jaredkinger starting up this page again to be published

First change:
- It will not be under CGDI page, but rather right under initiatives
- I can't remember if a "card" was made for the CGDI page, if there was this can be used to add to the initiative page and under Initiatives section on the homepage (replace Maps for HTML)

I'm just comparing a new wireframe they sent me to see if it still matches the dev page.
Translation should be in by Monday/Tuesday next week

**Comment by jaredkinger** [comment]
@heamart I've made the initial adjustments as follows:

- [Arctic SDI](https://wordpress.dev.geo.ca/initiatives/arctic-spatial-data-infrastructure/) page updated to be directly under Initiatives
- Arctic SDI card added to [Initiatives](https://wordpress.dev.geo.ca/initiatives/) and [Home](https://wordpress.dev.geo.ca/home/) page

I put the Arctic SDI card as the last card on the initiatives pages but I can reorder this if you would like.

I will keep an eye out for the rest of the content changes and update as soon as possible so we can get this reviewed, tested and launched on time.

**Comment by heamart** [comment]
The map will be changed. Here is the new iframe code:

<iframe src="https://geoportal.arctic-sdi.org/?lang=en&uuid=b692ea70-214e-4d5d-b400-fc95feca6c38" allow="geolocation" style="border: none; width: 100%; height: 100%;"></iframe>

**1. Map title:** 
Average Pan-Arctic Sea Ice Extent (1979 to 2007)
**2. Legend:** 
![arcticSDI_legend](https://github.com/user-attachments/assets/bb72906c-e6b8-4d69-a4dd-c2765ee211e8)
**3. Map Caption (however this can be formatted):**
Move the centre slider on the map to compare sea ice extent between January and July.
Data sources: 
- Sea ice extent: [National Snow & Ice Data Center](https://nsidc.org/data)
- Arctic SDI topographic basemap: [Arctic SDI](https://arctic-sdi.org/)

Map projection: EPSG:3573 – WGS 84 / North Pole LAEA Canada

**4. Then right under the map will be the following text:**

Developed through collaborative efforts and data sharing among Arctic nations, this map is an insightful comparison of the Arctic's [sea ice extent](https://natural-resources.canada.ca/environment/resources/publications/impacts-adaptation/reports/assessments/2008/ch3/10325). It distinguishes between the average conditions in January and July from the years 1979 to 2007. The sea ice extent is layered on top of the [Arctic SDI topographic basemap](https://arctic-sdi.org/services/topografic-basemap/), which provides a detailed depiction of the underlying geographical features and elevations.
The layer on the left illustrates the average sea ice extent for January, the peak of the Arctic winter, showcasing the maximum reach of the ice. The layer on the right illustrates the average sea ice extent for July, capturing the minimum ice coverage during the height of summer. This contrast highlights the seasonal fluctuations in sea ice and the dynamic nature of polar environments.

**Comment by heamart** [comment]
update to the text right under "embedded map" header, change those 2 paragraphs before the map to:

The custom map below is being delivered via the Arctic SDI Geoportal. Web developers can create dynamic interactive maps, known as embedded maps, for delivery through their own website without any coding and in just a few quick steps. This is a unique service that is delivered to the public through the Geoportal

**Comment by heamart** [comment]
and last text change. Next to the map, the short instructions on using the slider can be change to:

Move the vertical slider left to right to compare sea ice extent between January and July

**Comment by heamart** [comment]
small change for the card on the initiative and homepage:
- can the image be changed to that used in the banner for the Arctic SDI page (the mountain background image)?

**Comment by heamart** [comment]
slightly modified for the "visit the Arctic SDI Geoportal":

![arcticSDI_geoportal_EN](https://github.com/user-attachments/assets/fdc7f9b0-9d8c-4a3f-9dac-1dd05cee2c80)

**Comment by jaredkinger** [comment]
@heamart I've made the requested text changes and updated the Geoportal image on the [Arctic SDI](https://wordpress.dev.geo.ca/initiatives/arctic-spatial-data-infrastructure/) page. I adjusted the formatting/styling of the content to the right of the map to create a sidebar. I added headings to the legend and the short instructions here so I hope that's okay.

I've updated the images for the cards on the [Home](https://wordpress.dev.geo.ca/home/) and [Initiatives](https://wordpress.dev.geo.ca/initiatives/) pages. Good catch here, not sure why I chose that other image.

**Comment by heamart** [comment]
French translation for the homepage and initiative page card:

**L’infrastructure de données spatiales pour l’Arctique (IDS-Arctique)**
Découvrez les données géographiques de l’Arctique grâce à cette collaboration entre les agences cartographiques nationales de l’Arctique.

French translation for arctic sdi page:
[Arctic SDI_FR.docx](https://github.com/user-attachments/files/17048912/Arctic.SDI_FR.docx)

**Comment by heamart** [comment]
updated fr doc, just a phrasing change to the last sentence in the second paragraph
[Arctic SDI_FR.docx](https://github.com/user-attachments/files/17074536/Arctic.SDI_FR.docx)

**Comment by jaredkinger** [comment]
@heamart The [IDS Arctique](https://wordpress.dev.geo.ca/fr/initiatives-fr/linfrastructure-de-donnees-spatiales-pour-larctique-ids-arctique/) page is up on dev now. The cards on the French [Home](https://wordpress.dev.geo.ca/fr/accueil/) and [Initiatives](https://wordpress.dev.geo.ca/fr/initiatives-fr/) pages have been updated.
