### ISSUE TITLE
Critical Mineral Pages

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#293]
@jennywilsonsewell @jaredkinger @heamart 
Hi Jenny,
The Critical Mineral page in EN and FR is ready for implementation on DEV. Here are the links to the files and the images.  Let me know if you have any questions.
Thank you,
Andrea
2023_CMGD_Website_v06.docx  EN
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/88656331
2023_CMGD_Website_v06_French.docx 
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/88652806
Critical Minerals Images 
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/88716424

**Comment by jennywilsonsewell** [comment]
@Andrea-Merry @jaredkinger @heamart
The Critical Mineral pages are ready for review on DEV.
EN: https://wordpress.dev.geo.ca/initiatives/critical-minerals/
FR: https://wordpress.dev.geo.ca/fr/initiatives-fr/mineraux-critiques/
Thank you,
Jenny

**Comment by Andrea-Merry** [comment]
@jennywilsonsewell @heamart @jaredkinger 
Looks great! Thank you Jenny. I will send the links to the Critical Minerals team for their review.
Thank you,
Andrea

**Comment by jennywilsonsewell** [comment]
[like]  Wilson Sewell, Jenny (she, her... reacted to your message:
________________________________

**Comment by jennywilsonsewell** [comment]
[0]     Wilson Sewell, Jenny (she, her... reacted to your message:
________________________________

**Comment by Andrea-Merry** [comment]
@jaredkinger @jennywilsonsewell @heamart 
Hi Jared,
There is an issue regarding the French links to the Critical Minerals maps on GEO.ca. When I am on the English map(s) below and click Francais to switch languages it goes to the French map(s) as it should, but when I copy the French link(s) from the French page into another browser it goes to the English map(s). It is strange that it is doing this. We need the correct French links for the Critical minerals French page.

If you are not the right person to look into this please let me know who I should contact.
Thank you,
Andrea
English links:
https://app.geo.ca/map?rvKey=d6407ecb-5989-1376-8b3b-a2c354275cf1
https://app.geo.ca/map?rvKey=2854b1c2-ac15-5e8d-c76d-a0805c56d0b2
https://app.geo.ca/map?rvKey=84d566ad-42a4-938d-ae39-277bee3281be

**Comment by bo-lu** [comment]
Hi Andrea,

I received this ticket in my mailbox. To hard link a language, please add the &lang=en or &lang=fr to the URL path.

For example: 
French: https://app.geo.ca/map?rvKey=d6407ecb-5989-1376-8b3b-a2c354275cf1&lang=fr
English: https://app.geo.ca/map?rvKey=d6407ecb-5989-1376-8b3b-a2c354275cf1&lang=en

Hope this helps!
Bo

**Comment by Andrea-Merry** [comment]
@bo-lu 
Hi,
Thank you. I updated the links. 
Andrea

**Comment by Andrea-Merry** [comment]
@jaredkinger @jennywilsonsewell  @heamart 
Good morning,
I have approval from the Critical Minerals group for the implementation of the EN and FR pages for the upcoming release.
Thank you,
Andrea 
EN: [https://wordpress.dev.geo.ca/initiatives/critical-minerals/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwordpress.dev.geo.ca%2Finitiatives%2Fcritical-minerals%2F&data=05%7C02%7Candrea.merry%40NRCan-RNCan.gc.ca%7C067f500d21aa4d255ab708dc192d53b8%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638412929664771052%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=7NXVKz%2BR%2FpHqFQl8lVt3i5hb6WpHJ%2B%2BZdxpFFO13XX4%3D&reserved=0)
FR: [https://wordpress.dev.geo.ca/fr/initiatives-fr/mineraux-critiques/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwordpress.dev.geo.ca%2Ffr%2Finitiatives-fr%2Fmineraux-critiques%2F&data=05%7C02%7Candrea.merry%40NRCan-RNCan.gc.ca%7C067f500d21aa4d255ab708dc192d53b8%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638412929664927315%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BPJyZPN34sw2UcN2Uc7098MPQGnO7MBGk2iY%2F90KyAE%3D&reserved=0)

**Comment by Andrea-Merry** [comment]
QC completed on staging
