### ISSUE TITLE
Flood Mapping updates

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#294]
- Text updates to the pages: Flood Mapping, Flood Map and Dataset Gallery, Historical Flood Events
- Remove map page Active Floods in Canada and replace with Floods in Canada - Current Year

**Comment by heamart** [comment]
will send the content soon

**Comment by heamart** [comment]
1. On the english [Flood Mapping](https://geo.ca/flood-mapping/) page: **remove** the paragraph "Canadian federal, provincial and territorial geospatial data providers...." under the first paragraph in the main body.

2. On the [Flood Mapping](https://geo.ca/flood-mapping/) page (fr & en) change the "Active Floods in Canada" in the gallery section to:
     - EN:
     Title: Floods in Canada - Current Year
     Text: Explore floods for the current year as monitored by Natural Resources Canada.
     - FR:
     Title: Inondations au Canada - Année courante
     Text: Explorez les inondations de l'année en cours tel que cartographiées par Ressources naturelles Canada.
     - Links on this card will be updated to a new map page for that map

3. On the [Flood Map and Dataset Gallery](https://geo.ca/flood-mapping/flood-map-gallery/) page, change the Active Flood in Canada to the same as listed above (i.e. Floods in Canada - Current Year)

4. Archive/remove the Active Floods in Canada map page, add new map page Floods in Canada - Current Year:
     - EN draft:
[Floods in Canada - Current Year_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13976890/Floods.in.Canada.-.Current.Year_EN.docx)

     - EN config file:
[floods-in-canada-current-year-en-V02.json](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13976893/floods-in-canada-current-year-en-V02.json)

     - FR draft:
[Floods in Canada - Current Year_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13976896/Floods.in.Canada.-.Current.Year_FR.docx)

     - FR config file:
[inondations-au-canada-annee-courante-fr-V06.json](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13976901/inondations-au-canada-annee-courante-fr-V06.json)


5. On the [Historical Flood Events](https://geo.ca/flood-mapping/flood-map-gallery/historical-flood-events/) page, add disclaimer, if possible in an accordion (text in tracked changes in docs below)
     - EN:
[Historical Flood Events_EN_v3.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13976938/Historical.Flood.Events_EN_v3.docx)
     - FR:
[Historical Flood Events_FR_v2.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/13976941/Historical.Flood.Events_FR_v2.docx)

**Comment by jaredkinger** [comment]
I have made the following changes to dev:

- [Flood Mapping](https://wordpress.dev.geo.ca/flood-mapping/) page has been updated to remove paragraph and replace active floods with current floods
- [Flood Map and Dataset Gallery](https://wordpress.dev.geo.ca/flood-mapping/flood-map-gallery/) page has been updated to replace active floods with current floods
- Active Flood pages have been archived
- [Floods in Canada  - Current Year](https://wordpress.dev.geo.ca/flood-mapping/flood-map-gallery/floods-in-canada-current-year/) page added
- [Historical Flood Events](https://wordpress.dev.geo.ca/flood-mapping/flood-map-gallery/historical-flood-events/) disclaimer added

**Comment by heamart** [comment]
on the [Floods in Canada - Current Year](https://wordpress.dev.geo.ca/flood-mapping/flood-map-gallery/floods-in-canada-current-year/) page, the subtitle needs to be changed from **Active Floods in Canada** to **Floods in Canada - Current Year**

**Comment by jaredkinger** [comment]
@heamart Good catch. I've updated the subtitle to the correct text.

**Comment by Andrea-Merry** [comment]
QC completed for the release
