### ISSUE TITLE
Water Pollutants by Facility Map is Blank

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#295]
The Water Pollutants by Facility map featured on the [Map Gallery](https://geo.ca/map-gallery/) page links to a blank map. I tried looking up the uuids in app.geo.ca and it looks like those records are no longer available. Have those records been moved or should we be removing/replacing this map?

@heamart @Andrea-Merry

**Comment by heamart** [comment]
they seemed to have been moved/changed. the new records are:

1. [Releases of Cadmium to Water by Facility](https://app.geo.ca/result/en/releases-of-harmful-substances-to-water-%E2%80%93-releases-of-cadmium-to-water-by-facility,-canada?id=28ec1eaa-2291-4152-9f57-1f5c91eea21a&lang=en)
   - UUID: 28ec1eaa-2291-4152-9f57-1f5c91eea21a
   - service EN: https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/36
   - service FR: https://maps-cartes.ec.gc.ca/arcgis/rest/services/ICDE/MapServer/36

2. [Releases of Lead to water by facility](https://app.geo.ca/result/en/releases-of-harmful-substances-to-water-%E2%80%93-releases-of-lead-to-water-by-facility,-canada?id=eebd2686-22f0-446e-b375-6d090276919a&lang=en)
   - UUID: eebd2686-22f0-446e-b375-6d090276919a
   - service EN: https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/38
   - service FR: https://maps-cartes.ec.gc.ca/arcgis/rest/services/ICDE/MapServer/38

3. [Release of mercury to water by facility](https://app.geo.ca/result/en/releases-of-harmful-substances-to-water-%E2%80%93-releases-of-mercury-to-water-by-facility,-canada?id=15cd9dc7-756b-4d78-b01b-221880f1bf7f&lang=en)
   - UUID: 15cd9dc7-756b-4d78-b01b-221880f1bf7f
   - service EN: https://maps-cartes.ec.gc.ca/arcgis/rest/services/CESI/MapServer/37
   - service FR: https://maps-cartes.ec.gc.ca/arcgis/rest/services/ICDE/MapServer/37

**Comment by jaredkinger** [comment]
@heamart Thanks for sending over the updated records. I've made these changes on dev for both English and French.

**Comment by Andrea-Merry** [comment]
QC completed on staging
