### ISSUE TITLE
Homepage content updates

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#296]
For February 2024 release
If content owner for critical minerals does not get back with their final okay in time for february release, we'll keep GeoAI up under In the Spotlight.
 
Changes to "In the Spotlight"
1. Remove flood mapping, replace with Maps for HTML
    image: https://geo.ca/wp-content/uploads/2023/09/charlesdeluvio-pjAH2Ax4uWk-unsplash-768x432.jpg
    - Title EN: Maps for HTML
    - Text EN: Learn how to use and contribute to a standard for simple, accessible, and programmable web maps.
    
    - Title FR: Cartes pour HTML
    - Text FR: Apprenez à utiliser et à contribuer à une norme pour des cartes Web simples, accessibles et programmables.
 
3. Remove GeoAI, replace with Critical Minerals
    image: https://wordpress.dev.geo.ca/wp-content/uploads/2024/01/tetrahedrite_low-scaled.jpg
    - Title EN: Critical Minerals
    - Text EN: Discover tools and resources to help strengthen the supply chains of critical minerals.
    
    - Title FR: Minéraux critiques
    - Text FR: Découvrez des outils et des ressources qui contribueront à renforcer les chaînes d’approvisionnement en minéraux critiques.

drafts for reference:
 EN: [https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/89091243](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgcdocs.gc.ca%2Fnrcan-rncan%2Fllisapi.dll%2Flink%2F89091243&data=05%7C02%7Cheather.martin%40NRCan-RNCan.gc.ca%7C45aad23983194bdbd44508dc1d085bb2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638417168929424154%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DVnCKB%2FxQn%2FfvR%2B4YhIWSs3iMmQngBYd4rQTHi55hDk%3D&reserved=0)
 FR: [https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/89082395](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgcdocs.gc.ca%2Fnrcan-rncan%2Fllisapi.dll%2Flink%2F89082395&data=05%7C02%7Cheather.martin%40NRCan-RNCan.gc.ca%7C45aad23983194bdbd44508dc1d085bb2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638417168929433869%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SwGIq5yQidEQIXZrcD%2FJIk6lTo37PMOAMdEvrzz8TRw%3D&reserved=0)

**Comment by jaredkinger** [comment]
[Homepage](https://wordpress.dev.geo.ca/home/) has been updated on dev.

**Comment by Andrea-Merry** [comment]
QC completed on staging
