### ISSUE TITLE
GEO News content update

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#297]
For February release

Add GeoAI Urban Use Case as first "card"

Image: https://geo.ca/wp-content/uploads/2023/12/urban-development-768x432.jpg

Date EN: December 19, 2023
Title EN: [Urban Development Use Case](https://geo.ca/initiatives/geobase/geoai/urban-development-use-case/)
Text EN: Learn about and download time-enabled data created using Artificial Intelligence (AI) and explore the results of a change detection analysis in Québec City.

Date FR: 19 décembre 2023
Title FR: [Cas d'utilisation du développement urbain](https://geo.ca/fr/initiatives-fr/geobase/geoia/cas-dutilisation-du-developpement-urbain/)
Text FR: Découvrez et téléchargez les données temporelles créées à l'aide de l'intelligence artificielle (IA) et explorez les résultats d’une analyse de détection des changements pour la ville de Québec.

Drafts for reference:
EN: [https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/89099520](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgcdocs.gc.ca%2Fnrcan-rncan%2Fllisapi.dll%2Flink%2F89099520&data=05%7C02%7Cheather.martin%40NRCan-RNCan.gc.ca%7C45aad23983194bdbd44508dc1d085bb2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638417168929440814%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fA2DSIRo0r6ORJF%2FhswM01fdHJSrar39xTSYaZ41InE%3D&reserved=0)
FR: [https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/89098995](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgcdocs.gc.ca%2Fnrcan-rncan%2Fllisapi.dll%2Flink%2F89098995&data=05%7C02%7Cheather.martin%40NRCan-RNCan.gc.ca%7C45aad23983194bdbd44508dc1d085bb2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638417168929447738%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NM6L4883%2BzNyD4X76F1WOl0a7ZX3aiW8ZnSgTZr9kO0%3D&reserved=0)

**Comment by jaredkinger** [comment]
The [Geo News](https://wordpress.dev.geo.ca/geo-in-the-news/) page has been updated on dev.

**Comment by Andrea-Merry** [comment]
QC completed on staging
