### ISSUE TITLE
Initiative page update

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#298]
For February release (as long as critical minerals gets final ok)

Add Critical Minerals "card" under Featured Geospatial Initiatives

image: The header image on the [critical minerals page](https://wordpress.dev.geo.ca/initiatives/critical-minerals/) or any of the mineral images if the size doesn't work

Title EN: Critical Minerals
Text EN: Canadian geological survey organizations are collaborating to provide tools and resources to help strengthen the supply chains of critical minerals.

Title FR: Minéraux critiques
Text FR: Les organisations canadiennes responsables des levés géologiques collaborent afin d’offrir des outils et des ressources qui contribueront à renforcer les chaînes d’approvisionnement en minéraux critiques.

drafts for reference:
EN: [https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/89078982](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgcdocs.gc.ca%2Fnrcan-rncan%2Fllisapi.dll%2Flink%2F89078982&data=05%7C02%7Cheather.martin%40NRCan-RNCan.gc.ca%7C45aad23983194bdbd44508dc1d085bb2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638417168929454655%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=RLp%2BL7HS3dbDcVfUg6YmhDUOH%2FAPtWpsrVWsEWKjcdE%3D&reserved=0)
FR: [https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/89089891](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgcdocs.gc.ca%2Fnrcan-rncan%2Fllisapi.dll%2Flink%2F89089891&data=05%7C02%7Cheather.martin%40NRCan-RNCan.gc.ca%7C45aad23983194bdbd44508dc1d085bb2%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638417168929461549%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UNEGyrklFtfMwE1DWctW0rAmOzwQzfsL6KXzFAOFIHI%3D&reserved=0)

**Comment by jaredkinger** [comment]
I've updated the [Initiatives](https://wordpress.dev.geo.ca/initiatives/) page in both English and French.

**Comment by heamart** [comment]
small spelling correction:
"Critical" for the critical mineral card is spelled wrong on the english page

**Comment by Andrea-Merry** [comment]
QC completed on staging
