### ISSUE TITLE
Flood mapping page changes

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#300]
Please change the first paragraph

EN
https://geo.ca/flood-mapping/

OLD: Flooding is Canada’s most costly natural disaster. Each year, it causes an average of over $1 billion in direct damage to homes, property, and infrastructure. Natural disasters are increasing in frequency and severity.

Canadian federal, provincial and territorial geospatial data providers are collaborating to provide tools and resources to help Canadians plan and prepare for floods.

NEW: Flooding is Canada’s most common and most costly natural disaster. Overall, the estimated average annual cost of residential flooding in Canada is $2.9 billion. Natural disasters are increasing in frequency and severity. For more information, please visit: [Adapting to Rising Flood Risk](https://www.publicsafety.gc.ca/cnt/rsrcs/pblctns/dptng-rsng-fld-rsk-2022/index-en.aspx)

FR
https://geo.ca/fr/cartographie-inondations/

OLD: Les inondations sont la catastrophe naturelle la plus coûteuse au Canada. Chaque année, elles causent en moyenne plus d’un milliard de dollars de dommages directs aux habitations, aux biens et aux infrastructures. Les catastrophes naturelles sont de plus en plus fréquentes et de plus en plus graves.

NEW: Les inondations sont la catastrophe naturelle la plus fréquente et la plus coûteuse au Canada. Globalement, le coût annuel moyen des inondations résidentielles au Canada est estimé à 2,9 milliards de dollars. Les catastrophes naturelles sont de plus en plus fréquentes et de plus en plus intenses. Pour plus d'informations, veuillez consulter: [S'adapter à la hausse des risques d'inondation](https://www.securitepublique.gc.ca/cnt/rsrcs/pblctns/dptng-rsng-fld-rsk-2022/index-fr.aspx)

**Comment by jaredkinger** [comment]
These changes are now on dev.

EN: https://wordpress.dev.geo.ca/flood-mapping/
FR: https://wordpress.dev.geo.ca/fr/cartographie-inondations/
