### ISSUE TITLE
Homepage update - In the Spotlight

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#302]
Immediate changes to In the Spotlight:

- expand to 6 cards (2 rows of 3)
- add "purple button" under that will go to the GEO New page. "Read more GEO news"

The 6 cards will be:
- Flood Mapping
- GeoAI
- GeoBase Initiative
- Maps for HTML
- Canadian Geospatial Data Infrastructure (to be replaced with ArcticSDI once ready)
- Critical Minerals

Some of these cards are expected to change with new content for march release and later in the spring.

@jennywilsonsewell will prep the changes

[In the Spotlight_update_2024-02.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14375533/In.the.Spotlight_update_2024-02.docx)
[In the Spotlight_update_2024-02_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14375534/In.the.Spotlight_update_2024-02_FR.docx)

**Comment by jennywilsonsewell** [comment]
@heamart 
[EN page on dev](https://wordpress.dev.geo.ca/home/)
[FR page on dev](https://wordpress.dev.geo.ca/fr/accueil/)

**Comment by jaredkinger** [comment]
I've pushed the homepage changes over to staging. [English](https://stage.geo.ca/home/) and [French](https://stage.geo.ca/fr/accueil/)

**Comment by heamart** [comment]
If possible can we switch the Critical Minerals and Geobase Initiative cards?

**Comment by jaredkinger** [comment]
I switched the card placements on dev and pushed this change over to staging.

**Comment by heamart** [comment]
Looks good - it's good to go
