### ISSUE TITLE
Critical Minerals Page - Add description for each mineral

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#303]
@jaredkinger @jennywilsonsewell @heamart 
Hi, 
Based on our discussion yesterday, I asked Chris to provide a short description of each mineral in EN and FR. 

Manufacturing electrical wires requires copper minerals like tetrahedrite. 
La fabrication de fils électriques nécessite des minéraux de cuivre comme la tétraédrite.
 
Rutile is a major source of titanium for the aerospace industry.
Le rutile est une source majeure de titane pour l'industrie aérospatiale.
 
Potash is an essential fertilizer that is sourced from sylvite.  
La potasse est un fertilisant essentiel qui provient de la sylvite.

Jenny has updated Wordpress in DEV and the word documents on gcdocs. It can be pushed to PROD at the same time as the homepage.

As for the size of the images, Chris really wants to keep the size of the images as they are or at least close to it. 
Jared, is it possible to decrease the size a little without changing the quality of the image? If not, I suggest we leave the images as they are.
Thank you
Andrea
https://wordpress.dev.geo.ca/initiatives/critical-minerals/
https://wordpress.dev.geo.ca/fr/initiatives-fr/mineraux-critiques/

2023_CMGD_Website_v06.docx 
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90002673
2023_CMGD_Website_v06_French.docx 
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90005014

**Comment by jaredkinger** [comment]
I've pushed these changes over to staging. Can I get a quick QA on this?

EN: https://stage.geo.ca/initiatives/critical-minerals/
FR: https://stage.geo.ca/fr/initiatives-fr/mineraux-critiques/

**Comment by Andrea-Merry** [comment]
QA completed on staging in EN and FR. Good to go.

**Comment by jennywilsonsewell** [comment]
A minor detail - there is a larger space between the last line of text and the sylvite image than there is with the tetrahedrite and rutile images.

**Comment by Andrea-Merry** [comment]
Good catch Jenny!

**Comment by jaredkinger** [comment]
I've fixed the spacing issue on staging. You may need to refresh to the see the change.

**Comment by Andrea-Merry** [comment]
@jaredkinger @jennywilsonsewell @heamart 
Hi Jared,
This is not urgent, but the fourth anchor link [Collaborations géoscientifiques](https://geo.ca/fr/initiatives-fr/mineraux-critiques/#collbaorations) on the FR Critical Page does not work. All of the others are ok.
https://stage.geo.ca/fr/initiatives-fr/mineraux-critiques/
Thank you,
Andrea

**Comment by jaredkinger** [comment]
I've fixed the link on dev. This change will get pushed in the March release.

**Comment by Andrea-Merry** [comment]
Thank you :)
