### ISSUE TITLE
Canadian Hydrospatial Network page

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#304]
New content for GeoBase
CHN landing page and map page

**Comment by heamart** [comment]
English content ready:
- New CHN page which will be linked from the GeoBase page
[Canadian Hydrospatial Network (CHN)_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14572694/Canadian.Hydrospatial.Network.CHN._EN.docx)
- CHN map page (like previously done with flood maps, geoai etc.)
[Canadian Hydrospatial Network map_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14572654/Canadian.Hydrospatial.Network.map_EN.docx)
[CHN-map-en (1).json](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14572671/CHN-map-en.1.json)
- updates to homepage In the Spotlight, Map Gallery, and GeoBase page to add CHN info
[Other page updates to go with CHN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14572661/Other.page.updates.to.go.with.CHN.docx)

Currently in translation and finals approval to come soon

**Comment by heamart** [comment]
French content:
1. In the Spotlight:
Title: Réseau hydrospatial canadien
Text: Découvrez le nouveau réseau hydrographique canadien à plus haute résolution. Les données du Réseau hydrospatial canadien (RHC) permettent de modéliser l’écoulement des eaux de surface au Canada. 

2. Map Gallery:
Title: Réseau hydrospatial canadien

3. CHN card in geobase gallery
[Réseau hydrospatial canadien](https://app.geo.ca/result/fr/r%C3%A9seau-hydrospatial-canadien---rhc?id=ae385105-e48c-4b54-bd0f-dfb7303301cb&lang=fr)
Le Réseau hydrospatial canadien (RHC) est un réseau géospatial d'entités prêtes à l'analyse qui permet de modéliser l'écoulement des eaux de surface au Canada.

3. Landing page and Map page:
[Canadian Hydrospatial Network (CHN)_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14619595/Canadian.Hydrospatial.Network.CHN._FR.docx)
[Canadian Hydrospatial Network map_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14619597/Canadian.Hydrospatial.Network.map_FR.docx)
[CHN-map-fr (1).json](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/14619599/CHN-map-fr.1.json)

**Comment by heamart** [comment]
can move to patch release in April (TBD)

**Comment by jaredkinger** [comment]
These changes are up on dev now, links are below.

**English**
- [CHN](https://wordpress.dev.geo.ca/initiatives/geobase/canadian-hydrospatial-network/) In the last paragraph under "What's next for the CHN?" I believe there is a comma and space missing where is says "userswill" in the doc. I've updated this on the page, if it should be something else please let me know
- [CHN Map](https://wordpress.dev.geo.ca/initiatives/geobase/canadian-hydrospatial-network/canadian-hydrospatial-network-map/) I added a heading above the first paragraph to be consistent with what we have done on the other map pages for GeoAI and FHIMP
- [Home](https://wordpress.dev.geo.ca/home/) Spotlight and Map Gallery sections updated to include CHN
- [Map Gallery](https://wordpress.dev.geo.ca/map-gallery/) CHN card added
- [GeoBase](https://wordpress.dev.geo.ca/initiatives/geobase/) CHN card updated

**French**
- [CHN](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/reseau-hydrospatial-canadien/)
- [CHN Map](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/reseau-hydrospatial-canadien/carte-du-reseau-hydrospatial-canadien/)
- [Home](https://wordpress.dev.geo.ca/fr/accueil/) In the map gallery card we use the abbreviation in the title for English but not French. Do we want to add it for consistency?
- [Map Gallery](https://wordpress.dev.geo.ca/fr/galerie-de-cartes/) Same comment regarding the title as above
- [GeoBase](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/)

**Comment by heamart** [comment]
Thanks! 

1, For CHN page (english) last paragraph, it's just missing an "and". Please update to "...maintain data quality, improve access for users, and will advance hydrographic data standards..."
2. Yes, for the Map gallery card on the french page, include the abbreviation. It will be (RHC).

**Comment by heamart** [comment]
one more little spelling edit. On the French CHN page, in the first paragraph, the CHN in brackets needs to be changed to RHC :

À propos du RHC
Le [Réseau hydrospatial canadien](https://ressources-naturelles.canada.ca/reseau-hydrospatial-canadien) **(RHC)** est un progrès dans.....

**Comment by heamart** [comment]
Missed this earlier. But the [french map page](https://stage.geo.ca/fr/initiatives-fr/geobase/reseau-hydrospatial-canadien/carte-du-reseau-hydrospatial-canadien/) uses the english viewer instead of french

**Comment by jaredkinger** [comment]
The viewer should be displaying in French now on staging.
