### ISSUE TITLE
FHIMP - Phase 2 Report - add general education elements

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#309]
There were many suggestions as to how the sector can make flood mapping/flood risk sites more relevant for users: Some general education elements should be introduced more noticeable as many aspects of flood mapping are confusing for some audiences.  For example, use simple explanations, wikis, FAQs, and video infographic explanations

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/360
