### ISSUE TITLE
Proposed EIF CCMEO Web Presence workplan: Geo-CCMEO-Atlas Branding

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#31]
Initiate the development of a cohesive branding strategic integrating GEO.ca, CCMEO and the Atlas of Canada. Produce a Web Presence Framework document (modus operandi) supporting the logic behind the branding.
*Output of CCMEO Atlas-Web Presence Task team.

**Comment by jvanulde** [comment]
@Andrea-Merry can this be moved to Redmine as it's a content development activity?

**Comment by Andrea-Merry** [comment]
@jvanulde https://redmine.gcgeo.gc.ca/redmine/issues/28445
