### ISSUE TITLE
FHIMP - Phase 4 Report - Digital Collaboration Tool (Jupyter Hub)

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#310]
Jupyter Hub (Option 1 - Phase 4)
The functionality for the Digital Collaboration Tool (Jupyter Hub) is as follows:

[ ] download files, layers and data
[ ] upload files, layers and data
[ ] interoperability between platforms
[ ] image upload (jpg., .png, other)
[ ] work in a shared digital space with collaborators
[ ] file storage capability

for a full explanation of offering and context, please read the document for Phase 4 found here:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90540394

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/363
