### ISSUE TITLE
FHIMP - Phase 4 Report - 3D Visualization Client (Cesium)

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#311]
3D Visualization Client - Cesium (Option 2 - Phase 4)
The functionality for the 3D Visualization Client is as follows:

[ ] Visualization
[ ] Interoperability between platforms
[ ] Geolocation
[ ] address/coordinate look-up/visualization of address/coordinate

The minimum initially supported data types are as follows:
[ ] OGC API - Features
[ ] OGC API - Coverages
[ ] OGC API - Maps
[ ] OGC Sensor Things
[ ] WMS/WMTS
[ ] ArcGIS Map Services
[ ] GeoJSON
[ ] NORAD TLE
[ ] Shapefiles
[ ] 3D Tiles

mockups suggest:
[ ] Button to view 3D datasets in a 3D visualization tool (Cesium) (1st Image)
[ ] example of how a 3D visualization client may work (2nd Image)

for a full explanation of offering and context, please read the document for Phase 4 found here:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90540394

Image 1
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/7eeaa70c-d3ec-442d-990d-97f182a1e5bf)

Image 2
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/d5813401-cbe7-4963-b538-2d298ee000ca)

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/363
