### ISSUE TITLE
FHIMP - Phase 4 Report - Flood Mapping Processing Services

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#312]
Flood mapping processes to support predictive model generation utilizing OGC APIs.  Image 1 is an example how a "Tools" section would provide access to Flood Mapping Processing Services from GEO.ca.  
The functionality for the Predictive Model Generation is as follows:

[ ] Visualization
[ ] Interoperability between platforms
[ ] Work in a shared digital space with collaborators
[ ] suggested Tools placement link (Image 1)
[ ] Tool Mockup/wireframe (Image 2)
[ ] add sea level rise and tide levels (Image 3)

for a full explanation of offering and context, please read the document for Phase 4 found here:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90540394

Image 1
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/f52c6b7f-9e1b-4b58-9311-13744406ced0)

Image 2
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/58b66545-6add-441a-ac02-fd142c624a91)

Image 3
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/af60b65d-35cf-4bae-906b-1cce39b510bd)

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/363
