### ISSUE TITLE
FHIMP - Phase 2 Wireframes and Mockups Report - Placename search

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#313]
A painpoint for users interacting with the app.geo.ca mapping interphase was using the placename search on the map.  SPecifically, the search is not enabled by default, leaving an empty bar that appears to be a search bar, without functionality.  Additionaly the placename search itself does not parse locations properly.  The solutions:

[ ] Placename search is enabled by default
[ ] Placename search can parse regions from search text

To see more text and explanation on wireframes and mock-ups please access the report on GCDocs, link below:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90190560

![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/00fdac7a-a89a-45f8-bf90-b60eea3178d7)

**Comment by elatsis** [comment]
Resolved in GeoView
