### ISSUE TITLE
FHIMP - Legend should always shown for specific layers

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#318]
As part of the user journeys for the Curious Public and Engaged Media, when accessing maps from a featured spotlight or through the search function, there was a challenge regarding the legend not always being visible with the map for Flood Susceptibility Index datasets.  

[ ] legend always shown with specific legends (eg. Flood Susceptibility Index)
[ ] legend- more information explaining the percentage information with a tooltip

To see more text and explanation on wireframes and mock-ups please access the report on GCDocs, link below:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90190560

example below:
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/7c684d51-922b-45e6-ac65-518b4e7a1e26)

**Comment by JeffreyAshtonNRCan** [comment]
This issue covered with #364.  closed
