### ISSUE TITLE
FHIMP - Phase 2 Wireframes and Mockups Report - Map automatically shown on dataset page

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#319]
The wireframe below in Figure 3-5 showcases improvements to the dataset page/metadata page by having the full map available on this page, removing the "Back to search" link when a user reaches the dataset from outside the search function, and moving the dataset information to tabs rather than having it stacked.  Content in this wireframe was capture from the geo.ca low fidelity wireframes (internal)

Proposed changes

[ ] Back to Search removed when page is reached from direct links
[ ] full sized map, similar to spotlight pages' embedded map
[ ] Dataset information moved to tabs for easier navigation instead of being stacked on top of each other

To see more text and explanation on wireframes and mock-ups please access the report on GCDocs, link below:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90190560

![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/c78d0e5a-4cfb-4f14-9597-689e885cd3be)

**Comment by elatsis** [comment]
Resolved in GeoView
