### ISSUE TITLE
Proposed EIF CCMEO Web Presence workplan: Content Development and Coordination

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#32]
Creation of a content strategy that aligns to short-term and long-term implementation plans, and is used to guide the development of CCMEO content across all CCMEO web sites-that comprise the CCMEO Web Presence.
Content creation will include coordinating the creation of polished, harmonious and integrated content documents. This will require touchpoints with all CCMEO Divisions.
A content coordination governance will be established to support horizontal content creation and development across the Branch.
*This work was not part of the original EIF ask.

**Comment by jvanulde** [comment]
@Andrea-Merry this is content development related. Did you want to move to Redmine? If so please close this with note stating where it went.

**Comment by Andrea-Merry** [comment]
@jvanulde https://redmine.gcgeo.gc.ca/redmine/issues/28444
