### ISSUE TITLE
"View on Map" button directly on search results page

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#320]
For user journeys that bring users to the search results after using the search function on the main page of geo.ca, one suggestion for improvement is to allow the user to view the search results on the map with one click of a "View on Map" button, rather than having to go to the dataset page.

[ ] "View on Map" button directly on search results page

To see more text and explanation on wireframes and mock-ups please access the report on GCDocs, link below:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90190560

![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/c8b7099f-d10f-449e-8406-1352a0b0680e)

**Comment by JeffreyAshtonNRCan** [comment]
Pascal can add the "View on Map" button

**Comment by pvautour** [comment]
I believe this becomes less relevant if we look at the new wireframes from vlad. We should probably close this issue if we are satisfied by the new wireframe.

**Comment by JeffreyAshtonNRCan** [comment]
Met with Vlad and determined a View on Map button not needed with the new prototype, as the map can be viewed directly from the search results.  Closing issue.
