### ISSUE TITLE
FHIMP - Phase 2 Wireframes and Mockups Report - Homepage improvements

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#323]
Suggested changes to GEO.ca homepage:

[ ] Search Filter options as drop down to search bar, so users can select multiple filters to perform a search rather than keywords and themes only
[ ] "View More Initiatives" button making it consistent with other sections 

To see more text and explanation on wireframes and mock-ups please access the report on GCDocs, link below:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90190560

![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/bb5492f8-e333-40b9-946a-bb43a447ff03)

**Comment by elatsis** [comment]
Not aligned with our plans
