### ISSUE TITLE
FHIMP - Phase 2 Wireframes and Mockups Report - Legend on Map and Search improvement

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#325]
The below mock-up indicates a location on GEO.ca where improved place name searching will be implemented through Natural Language Processing.  A proposal for its functionality has been provided in a separate document.

Suggested changes:

[ ] Improved placename search processing
[ ] Legend with a pop-up description to relevant datasets

To see more text and explanation on wireframes and mock-ups please access the report on GCDocs, link below:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90190560

![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/463d3fe9-8232-4e4a-805b-cc07aa2a3f42)

**Comment by elatsis** [comment]
Resolved
