### ISSUE TITLE
FHIMP - Phase 2 Wireframes and Mockups Report - Collaboration space

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#326]
The makeup of a collaboration space is still in flux, here Compusult gives a recommendation as to where the collaboration space could be linked and how it could be accessed.

[ ] link added to megamenu for collaboration space (1st image)
[ ] Collaboration Space signin page (2nd image)
[ ] Suggested collaboration space was to use Jupyter Hub (3rd image)

To see more text and explanation on wireframes and mock-ups please access the report on GCDocs, link below:
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/90190560

Image 1
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/9563914b-816c-4414-b4be-d5a90325825f)

Image 2
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/da1c946d-24b8-404e-8ab7-2d8a5a428a4b)

Image 3
![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/112004392/bdd74392-4f24-480b-8d3e-21643fbcde9b)

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/363
