### ISSUE TITLE
FHIMP - Phase 2 User Journeys report - SEO

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#327]
Some issues came up during the User Journeys that may be able, over time to improve SEO:

[ ] Add tags using SEO tools to get results more frequently in Google
[ ] Add provincial, regional and territorial SEO
[ ] improve SEO by including provinces and territory names in tags: Canada wetlands flood mapping includes geo.ca in the first page of results
[ ] Keyword search in Google does not return results from GEO.ca

**Comment by elatsis** [comment]
Resolved - As of now we have the correct tags / SEO for the site.
