### ISSUE TITLE
FHIMP - Phase 2 User Journeys report - Tour for Guidance

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#329]
When moving through flood information it may be wise to show the user how to use the site.

[ ] Create a tour or provide guidance on how to use GEO.ca and flood presence.

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/360

**Comment by JeffreyAshtonNRCan** [comment]
Jean-Samuel from FHIMP replied:
We discussed this idea within our teams, and we decided we wouldn’t go ahead for the moment. We have another project on the line that might accomplish the same result and could be put on geo.ca. We will keep it in mind for a future potential project though.
