### ISSUE TITLE
FHIMP - Phase 2 User Journeys report - Metadata Entries

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#330]
When browsing through GEO.ca it was noticed that some instances of datasets have less information than others.  Having metadata that has required tags versus optional tags may explain this:

[ ] Check dataset metadata entries are fully complete

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/362

**Comment by JeffreyAshtonNRCan** [comment]
From Bo:
For #330, the information in a metadata varies. I’ve attached the minimum information coming from HNAP. If there is something specific that is missing, we can investigate with the data team.
The metadata minimum info doesn’t apply for STAC records coming from Datacube and EODMS, but something we should work toward.

**Comment by JeffreyAshtonNRCan** [comment]
[HNAP_Metadata_Minimum_Information_V24.xlsx](https://github.com/user-attachments/files/16101690/HNAP_Metadata_Minimum_Information_V24.xlsx)

**Comment by JeffreyAshtonNRCan** [comment]
Out of scope.  Optional metadata records beyond the minimum are not required.
