### ISSUE TITLE
FHIMP - Phase 2 User Journeys report - Historical Flood Events information

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#334]
A user journey of Curious Public looking for a work project in Smithers, BC, looking in particular for detailed cartographic information, on GEO.ca it was suggested that:

[ ] Add more details to the historical flood events information

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/361
