### ISSUE TITLE
FHIMP - Add links to flood safety guides for each province

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#339]
In the province and territories sections on flooding in GEO.ca it is suggested that we:

[ ] have links to flood safety guides for each province in the modal window.

**Comment by elatsis** [comment]
Closed, see updated issue: https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/360

**Comment by jaredkinger** [comment]
Is this covered under #322 or is this a separate issue?

**Comment by JeffreyAshtonNRCan** [comment]
Yes this is covered with #322.  Closing this issue.

**Comment by JeffreyAshtonNRCan** [comment]
Included with #322
