### ISSUE TITLE
FHIMP - Phase 1: Milestone 2 Report - CDS study suggestions

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#341]
A study by CDS defined several relevant objectives that align with the objectives of this study:

[ ] align on a single federal flood mapping mandate that includes examining opportunities and limitations for the federal fovernment to share this data with the public
[ ] Complete a skills assessment of the team and fill gaps by reassigning, recruiting or contracting talent, to stand up a multidisciplinary service delivery team to build, test, and iterate upon the service.

**Comment by elatsis** [comment]
Duplicate - addressed in other issues
