### ISSUE TITLE
FHIMP - Phase 1: Milestone 2 Report - Academic research studies (Mayer et al. (2012))

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#342]
Authors argue that:

[ ] Inundation extent and depth information for different events are critical for public users and should be presented on flood maps as the most important hazard information.  As many public users are not familiar with technical or statistical concepts such expressions should be avoided and replaced with terms like "small, medium or extreme event".
[ ] The extend and depth of recent and/or historical events need to be shown since it helps users to relate the modelled information to their personal experience and helps them create a better contextualization of the flood hazard.
[ ] The public does not necessarily need information on the potential consequences of flooding in terms of damages.  However, all buildings and roads should be shown on the map.  This helps users to orient themselves and to identify if their property would be affected in the case of a certain flood event.  Highlighting those building located within the flood extent, and that are likely to be affected during flooding, should be suggested.
[ ] Selected information on emergency management is useful for map users of the general public, such as information on evacuation routes and assembly points that can guide people on how to behave in case of emergency. 

Mayer et al.  suggested that the visualization of maps for the public should be kept as simple as possible.  They provide the following recommendations on the visualization of flood maps for this group:

[ ] Classifications in the legends should have a maximum of three classes, self explanatory symbols and text within the map.
[ ] The complexity and density of information should be reduced, and only the most important contents such as flood extent, depth, affected building and evacuation routes should be shown and visualized.

**Comment by elatsis** [comment]
Duplicate - addressed in other issues
