### ISSUE TITLE
FHIMP -  Suggested features for NRCan's future Flood Mapping Presence

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#343]
Participants in the survey were also asked what features should NRCan's future flood mapping web presence include that would enhance their ability to collaborate with various partners (Such as NRCan, other federal departments, provinces, territories, municipalities and indigenous communities).  They provided the following suggestions of features to include, percentage of users that want this functionality also included:

[ ] Download files, layers, data (85.71 %)
[ ] Upload filed, layers, data (57.14%)
[ ] Visualization (52.38%)
[ ] Search feature (45.24%)
[ ] Interoperability between platforms (42.86%)
[ ] Geolocation (33.33%)
[ ] Image upload (.jpg, .png, other) (28.57%)
[ ] Work in a shared digital space with collaborators (26.19%)
[ ] Address/coordinate look up/Visualization of address/coordinate (23.81%)
[ ] File storage capability (21.43%)
[ ] Mobile application capability (19.05%)
[ ] Sale or purchase of data or other geomatics information (19.05%)
[ ] Other (please specify): 1. a wider variety of REST API integration options such as those based on Open API, OGC API (16.67%)
[ ] Data connection to/from GPS (14.29%)
[ ] Secure user or group profiles (14.29%)
[ ] Char features, bulletin boards, and/or discussion groups (11.90%)
[ ] Private sections (4.76%)
[ ] Links to social media (4.76%)

**Comment by JeffreyAshtonNRCan** [comment]
Closed not needed at this time.
