### ISSUE TITLE
FHIMP - Phase 1: Milestone 2 Report - Survey user suggestion for federal mapping geospatial resources

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#344]
Survey participants provided some additional suggestions related to federal flood mapping geospatial resources, as follows:
[ ] When enhancing flood mapping geospatial resources, consider the integration of climate projections when estimating potential future flood risk rather than simply updating risk models based on the latest historical data.
[ ] Consider developing a richer data model for vector-based feature data along with persistent IDs, categories, and code lists where appropriate that take into consideration international standards for hydrological, hazard, environmental, population and infrastructure data (EU INSPIRE etc...), while still striving for pragmatic simplicity since some of these standards may tend towards the overly complex.
[ ] Include more up-to-date, standardized, detailed and accurate metadata.
[ ] Include more cloud-based resources that leverage native formats to improve performance on cloud-based platforms.  For example, while FTP resources should remain as they are useful for some use cases, other cloud-based applications would benefit from wider deployment of cloud-native services and formats such as STAC, COG, ZARR, COPC, GeoParquet etc...
[ ] The resolution on the flood index maps must be high enough to be useful at the property scale.  Broad brush interpretation of a flood index map will be very costly in terms of insurance costs and land values.
[ ] Consider inclusion of 3D flood visualization tools.
[ ] Include a portal for indigenous communities to access funding oppertunities (government-wide not limited to NRCan) to help them create flood and risk management maps.
[ ] Integrate socioeconomic data from Stats Canada, which could be used by emergency management during a flood event

**Comment by elatsis** [comment]
Duplicate - addressed in other issues
