### ISSUE TITLE
FHIMP - Phase 1: Milestone 2 Report - Flood Mapping Specialist Survey suggestions

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#345]
Among the key insights found from these interviews were:

[ ] There is not currently a robust gap analysis of data availability and deata sources in Canada as required by partners and/or users
[ ] Many maps that are developed based on engineering specifications are not particularly helpful for a general public user.
[ ] A distinct inconsitency across various departments and jurristrictions, relating to maps and data.  This also includes a lack of continuity in the development of guidelines on specific topics such as LiDAR acquisition.
[ ] Many of the regional and municipal sources are under-resources and do not have as much oppertunity to regularly update their content.
[ ] In general, finding a balance between trusted "official" data resources and consumer friendly maps, videos and infographics is key for a successful flood mapping online ecosystem.

**Comment by elatsis** [comment]
Duplicate - addressed in other issues
