### ISSUE TITLE
FHIMP - Phase 1: Milestone 2 Report - over all conclusion suggestions

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#346]
In summary, for many or most official sites, there are:
- significant inconsistencies (nomenclature, information, hierarchy);
- Some difficulties for non-geomatics users to use;
- Opportunities for some new visualization/tools' opportunities
In addition, there were many suggestions as to how the sector can make flood mapping/flood risk sites more relevant for users - based on information from Milestone 2:

[ ] Many/most flood hazard maps are located across multiple locations - there is an opportunity to centralize some of them more, or use consistent standards.
[ ] Big opportunity to showcase scenarios/predictive technology, animated modelling tools, sliding scales, risk map gradients.
[ ] Climate / flooding are important to current and potential users, but other related topics such as fire, extreme heat, general weather are relevant to many of the same people.
[ ] Some general education elements should be introduced more noticeably as many aspects of flood mapping are confusing for some audiences: for example, use simple explanations, wikis, FAQs, video/infographic explanations

**Comment by elatsis** [comment]
Duplicate - addressed in other issues
