### ISSUE TITLE
OSDP initiative page

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#347]
Draft content being reviewed by OSDP team.
Will include:
- OSDP page under Initiatives
- In The Spotlight card

**Comment by heamart** [comment]
Draft EN page ready.
Images in the doc but just waiting for confirmation on using them
[OSDP_EN_052024.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/15131101/OSDP_EN_052024.docx)

**Comment by jaredkinger** [comment]
The [English OSDP](https://wordpress.dev.geo.ca/initiatives/open-science-and-data-platform/) page is up on dev. I've used the images that were in the doc for now so if we need to change them we can swap them out.

**Comment by heamart** [comment]
Few small updates:
- change "About the OSDP" header to "Find out more about the Open Science and Data Platform"
- Under Visit the OSDP section
  - change the link in the "About the OSDP" card to https://osdp-psdo.canada.ca/en/about-osdp
  - change the link in the "take a quick tour" card to https://www.youtube.com/watch?v=zAM_HpKm2Ks; and the text to "Watch this video for helpful hints to search and navigate the platform.

**Comment by heamart** [comment]
Could the first graphic/image be switched to this one? I think it's better resolution
<img width="546" alt="new 2023 themes banner (2)" src="https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/107938467/5bbc70a5-adbb-426f-b00b-355cd2e69d87">

**Comment by heamart** [comment]
@jaredkinger @elatsis Content owner no longer wants to move forward with the page. It can be removed from the release plan

**Comment by jaredkinger** [comment]
Okay, I have archived the page for now. If they decide they want to revisit it we can bring back at that time.
