### ISSUE TITLE
GeoBase Initiative page announcement update

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#348]
Updated announcement on [GeoBase Initiative](https://geo.ca/initiatives/geobase/) page, to replace "New LiDAR-derived data available on GEO.ca...":

117,000 square kilometers added to the [GeoAI Data Series](https://geo.ca/initiatives/geobase/geoai/)! Explore data depicting roads, forested areas, hydrography and building footprints extracted from aerial photography provided by the Province of New Brunswick.  With this latest update, the [GeoAI Data Series](https://app.geo.ca/result/en/geoai---geobase-series?id=74738ff5-5367-5958-9aee-98fffdcd1876&lang=en)  now covers 170,000 square kilometers across Canada.

**Comment by jaredkinger** [comment]
Did we want to include a title with this or is it just going to be the paragraph posted above?

**Comment by heamart** [comment]
To replace the text in the purple box on that page.
The title: **117,000 square kilometers added to the [GeoAI Data Series](https://geo.ca/initiatives/geobase/geoai/)!**
Paragraph: Explore data depicting roads, forested areas, hydrography and building footprints extracted from aerial photography provided by the [Province of New Brunswick](https://www2.gnb.ca/). With this latest update, the [GeoAI Data Series](https://app.geo.ca/result/en/geoai---geobase-series?id=74738ff5-5367-5958-9aee-98fffdcd1876&lang=en) now covers 170,000 square kilometers across Canada.

**Comment by jaredkinger** [comment]
I've updated the announcement on dev for the English [GeoBase Page](https://wordpress.dev.geo.ca/initiatives/geobase/). Let me know when you have the French version and I will update that too.

**Comment by heamart** [comment]
translation:
**Ajout de 117 000 kilomètres carrés à la [série de données GéoIA](https://geo.ca/fr/initiatives-fr/geobase/geoia/)!** 
Explorez des données représentant les routes, les zones forestières, l'hydrographie et les empreintes de bâtiments du [Nouveau-Brunswick](https://www2.gnb.ca/content/gnb/fr.html) à partir d'une collection de photographies aériennes fournies par la province. Avec sa dernière mise à jour, la [série de données GéoIA](https://app.geo.ca/result/fr/g%C3%A9oia---s%C3%A9rie-g%C3%A9obase?id=74738ff5-5367-5958-9aee-98fffdcd1876&lang=fr) fournit désormais des données pour 170 000 kilomètres carrés d’un bout à l’autre du Canada.

**Comment by jaredkinger** [comment]
Announcement has been updated on dev for [English](https://wordpress.dev.geo.ca/initiatives/geobase/) and [French](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/)
