### ISSUE TITLE
GeoAI update - geobase page and homepage thumbnails

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#349]
The following thumbnail and text updates to the geoai card:
- under the Explore GeoBase Gallery on: https://geo.ca/initiatives/geobase/
- on the homepage under In the Spotlight

New thumbnail: 
![geoai_thumbnail_bg_smallscale_95dpi](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/107938467/c31bb11c-e0fc-44a6-a672-6fc8b63aa871)

New text: 
Discover the GeoAI Data Series, the time enabled geospatial features created using artificial intelligence (AI).

**Comment by jaredkinger** [comment]
What should the alt text be for this image?

**Comment by heamart** [comment]
alt text: Digitized roads, buildings, forested areas and water overlaying an elevation model in Woodstock, New Brunswick.

**Comment by heamart** [comment]
Translation:
**New text:** Découvrez la série de données GéoIA, soit des données géospatiales spatiotemporelles créées à l'aide de l'intelligence artificielle (IA). 
**image alt text:** Données numériques représentant les routes, les bâtiments, les zones forestières et l'hydrographie superposant un modèle d’élévation à Woodstock, au Nouveau-Brunswick.

**Comment by jaredkinger** [comment]
[Homepage](https://wordpress.dev.geo.ca/home/) and [GeoBase](https://wordpress.dev.geo.ca/initiatives/geobase/) pages are updated on dev along with the [Home FR](https://wordpress.dev.geo.ca/fr/accueil/) and [GeoBase FR](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/) pages.
