### ISSUE TITLE
GeoAI update - banner

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#350]
New banner image for the [GeoAI page](https://geo.ca/initiatives/geobase/geoai/)
Just need to make sure the attribution statement is not cut-off

![geoAI_sherbrooke_banner](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/107938467/3a25cdd0-1af0-4703-a8a0-3f84dfc6acf2)

**Comment by heamart** [comment]
French banner:
![geoAI_sherbrooke_banner_FR](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/107938467/cacaf1e4-3c96-4b62-9c88-ea28fb918b4f)

**Comment by jaredkinger** [comment]
Banners are updated on dev. [English Page](https://wordpress.dev.geo.ca/initiatives/geobase/geoai/) and [French Page](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/geoia/)
