### ISSUE TITLE
Page accueil Geo.ca

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#351]
Is it possible to change the title for this section:

https://geo.ca/fr/accueil/
![Accueil](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/142411247/00501a78-3403-4c76-840b-2945bb09bc3f)

Change: Cartographie des inondations

Replace with: Cartographie des zones inondables

Thanks

**Comment by jaredkinger** [comment]
I've applied this change to the dev site. You can view it here: https://wordpress.dev.geo.ca/fr/accueil/
