### ISSUE TITLE
homepage - minor updates

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#353]
Addition of Initiatives section on homepage
May release

1. In the spotlight down back down to three cards: Flood Mapping, GeoAI, CHN
2. Initiatives section added: 

En:
- section header: Initiatives
- 3 cards: Maps for HTML, Critical Minerals, GeoBase Initiative
- Link/button below: [Find more initiatives](https://geo.ca/initiatives/)

Fr:
- section header: Initiatives
- 3 cards: Cartes pour HTML, Minéraux critiques, L'initiative GéoBase
- Link/button below: [Retrouvez plus d'initiatives](https://geo.ca/fr/initiatives-fr/)

Attached are wireframes with the edits. It's mostly just re-arranging content
[GEO Home Page_EN_2024_05 (1).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/15099752/GEO.Home.Page_EN_2024_05.1.docx)
[GEO Home Page_FR_2024_05.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/15099753/GEO.Home.Page_FR_2024_05.docx)

**Comment by jaredkinger** [comment]
I've made this update to the home page in both [English](https://wordpress.dev.geo.ca/home/) and [French](https://wordpress.dev.geo.ca/fr/accueil/) on dev.

One thing to note is that FHIMP had asked (#351) to have the French Flood Mapping card title on the home page updated to "Cartographie des zones inondables".

**Comment by heamart** [comment]
French home page, the L'initiative Géobase links to the wrong page. Should be changed to: https://stage.geo.ca/fr/initiatives-fr/geobase/

**Comment by jaredkinger** [comment]
I've fixed the link for Geobase and pushed those changes over to staging.
