### ISSUE TITLE
FHIMP: Add links, educational content and resources 

### ISSUE THREAD

**Issue by elatsis** [Canadian-Geospatial-Platform/geo.ca#360]
Former issues, for reference:
https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/339
https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/337
https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/329
https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/322
https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/321
https://github.com/Canadian-Geospatial-Platform/geo.ca/issues/309

**Comment by JeffreyAshtonNRCan** [comment]
Issue #321 ( Link to publicly available data) - need to contact Geoview team for implementation.

To discuss with Johann
Contact Eleni for user tour

**Comment by JeffreyAshtonNRCan** [comment]
For issue #329, Tour for Guidance, Jean-Samuel from FHIMP replied:
We discussed this idea within our teams, and we decided we wouldn’t go ahead for the moment. We have another project on the line that might accomplish the same result and could be put on geo.ca. We will keep it in mind for a future potential project though.

**Comment by JeffreyAshtonNRCan** [comment]
Contact Jean-Samuel to see if any interest in wikis or FAQs.

**Comment by JeffreyAshtonNRCan** [comment]
Contact Johann for issue #321, link to publicly available data and issue #337, easier access to public links.
