### ISSUE TITLE
FHIMP - Geo.ca homepage improvements

### ISSUE THREAD

**Issue by JeffreyAshtonNRCan** [Canadian-Geospatial-Platform/geo.ca#365]
From Phase 2: Wireframes and Mock-ups:

- View more initiatives button

![image](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/97985025/1933648f-31da-47bf-b32c-26b2732a1feb)

**Comment by elatsis** [comment]
Edited - we only need the **New Initiatives button**. Team decided against the added search filters on the homepage. Thanks!

**Comment by jaredkinger** [comment]
The initiatives button was already added as part of this issue: #353

**Comment by elatsis** [comment]
@JeffreyAshtonNRCan @jaredkinger closing this issue again, everything is completed.
