### ISSUE TITLE
Historical Flood Events page update

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#368]
Hello!
In this site: 
EN: https://geo.ca/flood-mapping/flood-map-gallery/historical-flood-events/
FR: https://geo.ca/fr/cartographie-inondations/galerie-cartes-inondations/evenements-historiques-inondations/

Please add the sentence at the end of the last paragraph: 

EN: [Flood extents generated in near real time (4 hours) and for the current year ](https://geo.ca/flood-mapping/flood-map-gallery/floods-in-canada-current-year/) developed by the emergency geomatics services using satellite imagery are also available. 

FR: [Des étendues des inondations générées en temps quasi réel (4 heures) et de l’année en cours](https://geo.ca/fr/cartographie-inondations/galerie-cartes-inondations/inondations-au-canada-annee-courante/) créées par les services de géomatique d’urgence à partir d’imagerie satellitaire sont également disponibles.

**Comment by jaredkinger** [comment]
[EN](https://wordpress.dev.geo.ca/flood-mapping/flood-map-gallery/historical-flood-events/) and [FR](https://wordpress.dev.geo.ca/fr/cartographie-inondations/galerie-cartes-inondations/evenements-historiques-inondations/) pages both updated on DEV.

**Comment by heamart** [comment]
Doing small review of this addition to see if there is a better way to incorporate the hyperlink.

**Comment by heamart** [comment]
@NatFonSeg 
Would advise to use this instead as it is simpler for users to read and understand and added as a separate line under the last paragraph.

Also available:  [Flood extents generated in near real time for the current year](https://wordpress.dev.geo.ca/flood-mapping/flood-map-gallery/floods-in-canada-current-year/), as monitored by Natural Resources Canada.
