### ISSUE TITLE
Proposed EIF CCMEO Web Presence work plan: Geo.ca themes Geonames API

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#37]
OGC API compliant endpoint for GNBC placenames

**Comment by jvanulde** [comment]
@jolevesq I think we need to rewrite this as a User Story and create some feature specifications. Perhaps it lives in another repo?

**Comment by jvanulde** [comment]
This appears to be addressed in [geoview-api-geolocator](https://github.com/Canadian-Geospatial-Platform/geoview-api-geolocator) so closing.
