### ISSUE TITLE
GeoBase - Link off to CCOG in presence

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#38]
Suggestion from steering committee presentation.  Would there be somewhere to link off to the CCOG web presence somewhere in the community (most likely in resources).  Keep in mind that CCOG is linked to from GEO.ca through the Community homepage.

**Comment by jvanulde** [comment]
@sean-eagles I believe you mocked something up for this?

**Comment by sean-eagles** [comment]
@jvanulde we haven't officially inserted it on a page yet, but maybe this is something that we can bring up in our meeting with Cindy on Wednesday.

**Comment by sean-eagles** [comment]
Mocked up on the main page for GeoBase.  Can demo to GeoBase next week.

**Comment by jvanulde** [comment]
@sean-eagles can we task @vgulyy and/or @jaredkinger for this now?

**Comment by sean-eagles** [comment]
@jaredkinger @vgulyy if you have questions about this please let me know.

**Comment by jaredkinger** [comment]
@sean-eagles What is the relationship between the Canadian Council on Geomatics(CCOG) and GeoBase?

Do we want to mention CCOG in the accordion and link off to it there? Or should it be listed as an Additional Resource at the bottom of the GeoBase page.

**Comment by sean-eagles** [comment]
@jaredkinger A mention in the Accordion with a linkoff would be best.  If you need content please contact Cindy Mitchell.  Cindy can also explain how CCOG fills in.  From what I understand it is a consultative body for GeoBase.

**Comment by jaredkinger** [comment]
A link to the CCOG is in the accordions on the https://wordpress.dev.geo.ca/communities/geobase/ page. CCOG is also linked off to at the bottom of the page .
