### ISSUE TITLE
CHN map page - updated config file

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#382]
Update configuration file for the [CHN map page](https://geo.ca/initiatives/geobase/canadian-hydrospatial-network/canadian-hydrospatial-network-map/) to include the HRDEM.

EN json:
[CHN_HRDEM_EN.json](https://github.com/user-attachments/files/15676426/CHN_HRDEM_EN.json)

FR json:
[CHN_HRDEM_FR.json](https://github.com/user-attachments/files/15676489/CHN_HRDEM_FR.json)

**Comment by Andrea-Merry** [comment]
@jaredkinger Hi. I was wondering if the update to the Canadian Hydrospatial Network map to include the HRDEM hillshade layer is done? If so, has Colleen Fuss had an opportunity to review and approve it? She will need to before publishing on PROD.
Thank you
Andrea

**Comment by jaredkinger** [comment]
@Andrea-Merry Thanks for following up. I forgot to post an update here... The CHN maps have been updated to include the HRDEM hillshade layer. They've also been updated to use geoview. Links are below.

EN: https://wordpress.dev.geo.ca/initiatives/geobase/canadian-hydrospatial-network/canadian-hydrospatial-network-map/
FR: https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/reseau-hydrospatial-canadien/carte-du-reseau-hydrospatial-canadien/

If they need any changes, please let me know.
