### ISSUE TITLE
Contributeurs Page - EN Only Pages Link Fix

### ISSUE THREAD

**Issue by jennywilsonsewell** [Canadian-Geospatial-Platform/geo.ca#385]
@Andrea-Merry @heamart
The [Contributeurs Page ](https://geo.ca/fr/contributeurs/) currently has the "en anglais seulement" specification as plain text next to each EN only page link:
[Gouvernement de l’Alberta](https://www.alberta.ca/index.aspx) (en anglais seulement)

As per the [Canada Style Guide](https://design.canada.ca/style-guide/#wp7-2:~:text=Add%20parentheses%20inside,en%20anglais%20seulement), these language specifications are required to be inside each link, and the title of the linked content is **not** to be translated:
[Government of Alberta (en anglais seulement)](https://www.alberta.ca/index.aspx)

The AB, BC, NS, SK, and NL page links all need to be updated to this effect.

**Comment by jaredkinger** [comment]
I've made these updates on [dev](https://wordpress.dev.geo.ca/fr/contributeurs/) and pushed them over to [staging](https://stage.geo.ca/fr/contributeurs/) so they can be included in the upcoming release.
