### ISSUE TITLE
Behind the Scenes GeoView update EN/FR

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#387]
@heamart 
Good morning,
The Map Viewer section on the Behind the Scenes and dans les coulisses pages requires updating. I will send an email with the required changes.
Thank you,
Andrea

**Comment by jaredkinger** [comment]
Geoview description and features table updated for both [EN](https://wordpress.dev.geo.ca/behind-the-scenes/) and [FR](https://wordpress.dev.geo.ca/fr/dans-les-coulisses/).

**Comment by Andrea-Merry** [comment]
Thank you @jaredkinger
