### ISSUE TITLE
Flood Mapping Resources by P/T - Translated titles of linked content

### ISSUE THREAD

**Issue by jennywilsonsewell** [Canadian-Geospatial-Platform/geo.ca#388]
@jaredkinger @Andrea-Merry @heamart

I noticed that for both the EN and FR [Flood Mapping in your Province or Territory](https://geo.ca/flood-mapping/province-territory/) pages, the link titles under the [Flood Mapping Resources by Province/Territory](https://geo.ca/flood-mapping/province-territory/#:~:text=Flood%20Mapping%20Resources%20by%20Province/Territory) section have been translated when specifying "(French Only)" and "(en anglais seulement)". 

As per the [Canada Style Guide](https://design.canada.ca/style-guide/#wp7-2:~:text=Do%20not%20translate,en%20anglais%20seulement), the titles of the linked content should **not** be translated. 

**The English titles to be adjusted to French are:**

1. QC
- Flood Map Database (French only)
- Geo-Floods interactive map (French only)  

**The French titles to be adjusted to English are:**

1. YT
- Développement d’un outil d’évaluation des risques d’inondation dans les communautés du Yukon (anglais seulement)

2. NT
- Portail de cartographie ATLAS (en anglais seulement)

3. NL
- Inondations (en anglais seulement)
- Études de cartographie des risques d'inondation et cartes d'information publique (en anglais seulement)
- Application de cartographie des risques d'inondation (en anglais seulement)

4. PE
- Système d’information sur les aléas et les risques climatiques (CHRIS) (en anglais seulement)
- Guide des inondations à l’IPE : Une ressource pour l'aménagement du territoire local (en anglais seulement)

5. NS
- Inondations (en anglais seulement)
- Application de cartographie des risques d'inondation du littoral maritime (en anglais seulement)
- Être inondé (guide, en anglais seulement)

6. ON
- Cartographie des terres protégées (en anglais seulement)

7. SK
- Programme de réduction des dommages causés par les inondations (en anglais seulement)
- Surveillance des inondations (en anglais seulement)
- Préparez-vous à une urgence (Guide, en anglais seulement))

8. AB
- Inondation (en anglais seulement)
- Application de carte de sensibilisation aux inondations (en anglais seulement)
- Cartographie des bassins et rivières en Alberta (en anglais seulement)

9. BC
- Préparez-vous aux inondations (en anglais seulement)
- Cartographie des zones inondables (en anglais seulement)
- Gestion intégrée des aléas d’inondation (en anglais seulement)

Thank you,
Jenny

**Comment by JeffreyAshtonNRCan** [comment]
Completed on dev.  Will go with next release.
