### ISSUE TITLE
GeoBase - Layers that have not been updated in a long time

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#39]
from the Steering Committee meeting, we should figure out a strategy for layers that have not been updated lately.  Administrative Boundaries as an example hasn't been updated since 2005.  Do we feature them to push for renewal, do we minimize them, etc...

**Comment by jvanulde** [comment]
Could this be handled or addressed by #63 @indiciumx? I don't think the updated date should impact how content is sorted by default. Rather default sort should be determined by popularity.

**Comment by sean-eagles** [comment]
Yes, I would leave it in @indiciumx's hands and I agree that popularity is a good way to go.

**Comment by sean-eagles** [comment]
No traction left on this.  Closed.
