### ISSUE TITLE
Review new accessibility standard 301 549 from Europe.

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#402]
Here is the general information page on the standard. Link to the latest version is in the third last paragraph on the page. This is based strictly on WCAG 2.1 A & AA criteria. By July 2025 it will be updated to incorporate WCAG 2.2 A & AA.

Treasury board is looking at implementing new accesibility requirements including an implementation of the 301-549 standard found here: https://www.etsi.org/human-factors-accessibility/en-301-549-v3-the-harmonized-european-standard-for-ict-accessibility

If we could get a review of section 9, or the whole document, that would be great.

**Comment by jaredkinger** [comment]
I reviewed the entire document and while it provides great information on accessibility in wide variety of environments and scenarios impacting everyday life for those with accessibility needs, only section 9 applies to geo.ca. Section 9 is focused on web content and the EN 301-549 standard defers to WCAG 2.1 AA standards and doesn't add anything new on top of those standards. 

During the last accessibility review I performed on geo.ca I was testing for WCAG 2.1 AA which puts us above the required WCAG 2.0 AA. We're in good shape here and I don't see any additional steps we can take at this time.
