### ISSUE TITLE
Text update in the CHN page

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#406]
https://app.geo.ca/result/en/canadian-hydrospatial-network---chn?id=ae385105-e48c-4b54-bd0f-dfb7303301cb&lang=en
https://app.geo.ca/result/fr/r%C3%A9seau-hydrospatial-canadien---rhc?id=ae385105-e48c-4b54-bd0f-dfb7303301cb&lang=fr

Change in the text. I tracked the changes in the documents. Thanks!

For the FR version: 
[Réseau hydrospatial canadien - À propos de cet ensemble de données.docx](https://github.com/user-attachments/files/16752842/Reseau.hydrospatial.canadien.-.A.propos.de.cet.ensemble.de.donnees.docx)

For the EN version:
[Canadian Hydrospatial Network - About this dataset.docx](https://github.com/user-attachments/files/16752843/Canadian.Hydrospatial.Network.-.About.this.dataset.docx)
@heamart @Andrea-Merry

**Comment by heamart** [comment]
@NatFonSeg this is the metadata of the dataset as submitted through FGP/gcgeo/open maps. It has to be changed on that end by the data owner. It is not editable geo.ca content on this end.
