### ISSUE TITLE
Text to change in the NHN page

### ISSUE THREAD

**Issue by NatFonSeg** [Canadian-Geospatial-Platform/geo.ca#407]
https://app.geo.ca/result/en/national-hydro-network---nhn---geobase-series?id=a4b190fe-e090-4e6d-881e-b87956c07977&lang=en
https://app.geo.ca/result/fr/r%C3%A9seau-hydro-national---rhn---s%C3%A9rie-g%C3%A9obase?id=a4b190fe-e090-4e6d-881e-b87956c07977&lang=fr

Change in the text. I tracked the changes in the documents. Thanks!

For the FR version:
[Réseau hydro national - À propos de cet ensemble de données.docx](https://github.com/user-attachments/files/16752894/Reseau.hydro.national.-.A.propos.de.cet.ensemble.de.donnees.docx)

For the EN version:
[National Hydro Network - About this dataset.docx](https://github.com/user-attachments/files/16752895/National.Hydro.Network.-.About.this.dataset.docx)

@heamart @Andrea-Merry

**Comment by heamart** [comment]
@NatFonSeg this is the metadata of the dataset as submitted through FGP/gcgeo/open maps. It has to be changed on that end by the data owner. It is not editable geo.ca content on this end.

**Comment by NatFonSeg** [comment]
@heamart  oh thanks for letting me know!!!
