### ISSUE TITLE
Remove Item from GeoBase Gallery

### ISSUE THREAD

**Issue by heamart** [Canadian-Geospatial-Platform/geo.ca#408]
Remove the Automatically Extracted Buildings dataset under the [Explore GeoBase Gallery](https://geo.ca/initiatives/geobase/)

- There is no replacement
- Can be added to the October release

**Comment by jaredkinger** [comment]
@heamart I've removed this from the gallery on the [English](https://wordpress.dev.geo.ca/initiatives/geobase/) and [French](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/) GeoBase pages .
