### ISSUE TITLE
Critical Minerals - Image Captions

### ISSUE THREAD

**Issue by jennywilsonsewell** [Canadian-Geospatial-Platform/geo.ca#409]
@jaredkinger @heamart @Andrea-Merry 

Hi Jared,

On the [Critical Minerals](https://geo.ca/initiatives/critical-minerals/) page, please remove the italics from the captions for the Tetrahedrite, Rutile, and Sylvite images.

Thank you,
Jenny

**Comment by jaredkinger** [comment]
@jennywilsonsewell I've removed the italics on the [English](https://wordpress.dev.geo.ca/initiatives/critical-minerals/) and [French](https://wordpress.dev.geo.ca/fr/initiatives-fr/mineraux-critiques/) Critical Mineral pages.
