### ISSUE TITLE
Add card on home page under Foundation Data EN and FR

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#412]
@jaredkinger @heamart 
Good morning,
Please replace the Federal Electoral Districts - Canada 2019 card on the EN and FR homepages with the following image, title and link.
Let me know if you have any questions.

Title EN 
[Satellite Land Surface Mapping of Canada](https://app.geo.ca/result/en/canada-wide-vegetation-biophysical-parameters-from-medium-resolution-satellite-imagery?id=033ac0b8-653c-43b2-a843-171fa1c9ace4&lang=en)
![CanadaVegetationCoverAugust2021](https://github.com/user-attachments/assets/0a96525b-fe78-485c-8702-bcd6a2380a2b)
Alt text
Canada Vegetation Cover August 2021

Title FR
[Cartographie satellitaire de la surface terrestre du Canada](https://app.geo.ca/result/fr/param%C3%A8tres-biophysiques-de-la-v%C3%A9g%C3%A9tation-pancanadienne-%C3%A0-partir-d'images-satellitaires-%C3%A0-moyenne-r%C3%A9solution?id=033ac0b8-653c-43b2-a843-171fa1c9ace4&lang=fr)
Same image as EN
Alt text FR
La végétation pancanadienne août 2021

**Comment by jaredkinger** [comment]
@Andrea-Merry I've updated the [English](https://wordpress.dev.geo.ca/home/) and [French](https://wordpress.dev.geo.ca/fr/accueil/) home page with this new card.

**Comment by Andrea-Merry** [comment]
@jaredkinger 
Looks awesome! Thank you.
