### ISSUE TITLE
Canadian Hydrospatial Spatial Network Page changes

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#413]
@jaredkinger @heamart 
Good morning,
Natacha updated the CHN pages in EN and FR. Let me know if you prefer the track changes versions instead. 
Thank you,
Andrea
[Canadian Hydrospatial Network EN Updated.docx](https://github.com/user-attachments/files/17259797/Canadian.Hydrospatial.Network.EN.Updated.docx)
[Réseau hydrospatial canadien FR Updated.docx](https://github.com/user-attachments/files/17259835/Reseau.hydrospatial.canadien.FR.Updated.docx)

**Comment by jaredkinger** [comment]
@Andrea-Merry I've updated the [English](https://wordpress.dev.geo.ca/initiatives/geobase/canadian-hydrospatial-network/) and [French](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/reseau-hydrospatial-canadien/) CHN pages.

I noticed a couple really minor things in the Word Docs:

- EN: Under Additional information, there was no space before the email address here: "...please contact:[geoinfo@nrcan-rncan.gc.ca](mailto:geoinfo@nrcan-rncan.gc.ca)" and no period at the end so I've added those
- FR: Under Informations supplémentaires the first sentence had no period so I've added that

If those changes aren't correct please let me know and I will remove those.

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart 
Hi Jared,
There are a few minor changes that are highlighted in yellow to be done on the EN and FR pages. Please see attached.
Thank you,
Andrea
[Canadian Hydrospatial Network.docx](https://github.com/user-attachments/files/17478273/Canadian.Hydrospatial.Network.docx)
[Réseau hydrospatial canadien.docx](https://github.com/user-attachments/files/17478274/Reseau.hydrospatial.canadien.docx)

**Comment by jaredkinger** [comment]
@Andrea-Merry I've made those corrections for both the [English](https://wordpress.dev.geo.ca/initiatives/geobase/canadian-hydrospatial-network/) and [French](https://wordpress.dev.geo.ca/fr/initiatives-fr/geobase/reseau-hydrospatial-canadien/) CHN pages.

**Comment by Andrea-Merry** [comment]
@jaredkinger @heamart 
Hi Jared,
Sorry for the last minute change. Natacha noticed that she made a mistake in the title and that the image needed to be updated. Please replace the current thumbnail on the CHN Data card with the one I attached in EN and FR.
The EN version is perfect. For the French, all the modifications are correct but the titles below.
Thank you. Hopefully that is it.
Andrea
The 2 titles should be: Réseau hydrospatial canadien

1- À propos du réseau hydrographique canadien should be : À propos du réseau hydrospatial canadien

2- Quelles sont les prochaines étapes pour le réseau hydrographique canadien ? should be : Quelles sont les prochaines étapes pour le réseau hydrospatial canadien?


![CHN_First7WorkUnits_Oct2024](https://github.com/user-attachments/assets/0fba80c8-2df1-421f-946b-12b147c27519)

**Comment by jaredkinger** [comment]
@Andrea-Merry These changes are up on staging now: https://stage.geo.ca/fr/initiatives-fr/geobase/reseau-hydrospatial-canadien/

Let me know if I missed anything or if there are any other changes.

**Comment by Andrea-Merry** [comment]
@jaredkinger 
Looks great to me. Thank you for getting all of the changes done before the release.
Andrea
