### ISSUE TITLE
Add Permafrost card under In the Spotlight on the homepage

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#415]
@jaredkinger @heamart @jennywilsonsewell
Hi Jared,
Hopefully we can add this before the freeze. Please remove the CHN card under In the Spotlight and replace it with a Permafrost Community Card on the EN and FR pages. Use the banner image from the Permafrost Community Page as the thumbnail with the following EN and FR description(s). 
I also noticed that there is not a Permafrost card on the Community main page in French. Please verify. 
https://wordpress.dev.geo.ca/fr/communautes/
https://wordpress.dev.geo.ca/communities/

English:
Permafrost Community
Image
A central hub for permafrost information in Canada. Featuring data and tools from contributing provinces and territories.

French:
Communauté du pergélisol
Image
Une plateforme réunissant de l’information sur le pergélisol au Canada. Vous y trouverez des données et des outils des provinces et des territoires participants.

Let me know if you have any questions. 
Thank you,
Andrea

**Comment by jaredkinger** [comment]
Hi @Andrea-Merry I've added the permafrost card to the [English](https://wordpress.dev.geo.ca/home/) and [French](https://wordpress.dev.geo.ca/fr/accueil/) home pages. 

I've also updated the [French Community Page](https://wordpress.dev.geo.ca/fr/communautes/) to include the permafrost card.
