### ISSUE TITLE
404 Error: Atlas of Canada - The World 

### ISSUE THREAD

**Issue by jaredkinger** [Canadian-Geospatial-Platform/geo.ca#416]
The link to the[ Atlas of Canada World map](https://natural-resources.canada.ca/maps-tools-publications/tools/geodetic-reference-systems/wall-maps/16870#inter) located on the [Geo in the News](https://geo.ca/geo-in-the-news/) page generates a 404.

I've found this link to replace it with: https://natural-resources.canada.ca/maps-tools-and-publications/maps/atlas-canada/wall-maps/26109#details-panelinternational2

@Andrea-Merry or @heamart can you confirm if the link above is the correct replacement? If not, please advise what link this should be updated to.

Thanks!

**Comment by heamart** [comment]
Yes that is the correct link. Thank you !
