### ISSUE TITLE
Ensure content is not duplicated

### ISSUE THREAD

**Issue by sean-eagles** [Canadian-Geospatial-Platform/geo.ca#46]
_Source: GeoBase Steering Committee_

Ensure that content that appears in the community, and external sites, are not duplicated.

**Comment by jvanulde** [comment]
Not sure how we can deliver on this. At a minimum, duplication will occur with Open Maps.

**Comment by sean-eagles** [comment]
After bringing this up with Sebastien he said that some redundancy is okay and sometimes needed.
