### ISSUE TITLE
Administrative Theme Map Issue

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#50]
Theme Administration >> map: Limites législatives des parcs nationaux et des réserves à vocation de parc national du Canada >> preview working, full map: layer do not load

**Comment by indiciumx** [comment]
Issue is with the french service and not the application. Question for Data Team or Johann

**Comment by jvanulde** [comment]
@jolevesq can you take a look an reassign/move the issue as required, please? Thx.

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/50?planning-poker) with Zenhub @jolevesq
