### ISSUE TITLE
Emergency Theme Issue

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#51]
Theme Urgences >> map: Tremblements de terre au Canada >> "VOIR EN PLEIN ÉCRAN" still links to the Dataset page, not to the map directly

**Comment by indiciumx** [comment]
Fixed.

**Comment by jvanulde** [comment]
@indiciumx does this need review or can we push it to production?

**Comment by sean-eagles** [comment]
Fixed, goes to proper map for both languages, title and full screen links.
