### ISSUE TITLE
Environment Theme Issue

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#52]
Theme Environment >> map: Critical Habitat — Species at Risk — Canada >> map and preview not the same layer shown
Same issue with the French version

**Comment by indiciumx** [comment]
Fixed.

**Comment by jvanulde** [comment]
@indiciumx does this need review or can we push it to production?

**Comment by sean-eagles** [comment]
Fixed in French and English.
