### ISSUE TITLE
Society Theme Issue

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#53]
Theme Société >> under map: ActionGrippe >> there is an extra graphic (map) displayed following the map description. Need to be deleted.

**Comment by indiciumx** [comment]
Fixed.

**Comment by jvanulde** [comment]
@indiciumx does this need review or can we push it to production?

**Comment by sean-eagles** [comment]
I don't see the issue anymore on English or  French pages.
