### ISSUE TITLE
Economy Theme Issue

### ISSUE THREAD

**Issue by indiciumx** [Canadian-Geospatial-Platform/geo.ca#54]
Theme Economy >> map: Indigenous Mining Agreements (Active)  >> preview shows only the (Inactive) layer, the (Active) layer is not displayed. Inconsistent with the full map display. Same issue for the French preview >> It is up to you to decide if change is required.

**Comment by indiciumx** [comment]
Fixed to active.

**Comment by jvanulde** [comment]
@indiciumx was this a bug or an enhancement? Please label appropriately. As well, please assign this issue to the reviewer if it's ready.

**Comment by sean-eagles** [comment]
https://app-dev.geo.ca/result?id=488faf70-b50b-4749-ac1c-a1fd44e06f11&lang=en
That shows the Indigenous Mining Agreements, both active and expired.  This has the proper title for the map, I don't see one in the catalogue for just active.  Suggest changing the titles to Indigenous Mining Agreements.
