### ISSUE TITLE
The Bâtiments extraits automatiquement is missing from the French map gallery on Geo.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#58]
An email was sent by Mykhailo on October 17th indicating the Bâtiments extraits automatiquement map is missing from the French map gallery page on Geo.ca. It needs to be added to the map gallery.
Thank you,
Andrea

**Comment by elatsis** [comment]
@indiciumx can you please provide an update on this?

**Comment by sean-eagles** [comment]
Automatically extracted building show up on the English gallery, but not on the French side, issue still open.
