### ISSUE TITLE
Update Theme Maps titles and descriptions as per attached document on Geo.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#6]
[GEO_Updates.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/9470415/GEO_Updates.docx)
email sent September 1st, 2022
Please update map titles and descriptions for Mykhailo’s three maps as listed in attached document.

Patty, Mykhailo and I had discussed in our meeting on Tuesday, all curated maps created by Geo-Insights team use CCMEO’s basemaps hosted under this folder: [https://geoappext.nrcan.gc.ca/arcgis/rest/services/BaseMaps/](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeoappext.nrcan.gc.ca%2Farcgis%2Frest%2Fservices%2FBaseMaps%2F&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C2efd5de846b04724e5d508da8c315741%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637976440786074936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Vt1TWTeEJQ%2BrYgNqv2f32KSMyuxtETipMaTKJLb%2BzAs%3D&reserved=0). Recently these basemaps have moved/recreated to a new location: [https://maps-cartes.services.geo.ca/server2_serveur2/rest/services/BaseMaps](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmaps-cartes.services.geo.ca%2Fserver2_serveur2%2Frest%2Fservices%2FBaseMaps&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C2efd5de846b04724e5d508da8c315741%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637976440786074936%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vRcWLKgagvBObxMIGJQkWWn7YTRFJBYMV3sLrx7mmDU%3D&reserved=0) and basemaps in the old folder will be removed later on. This will affect all existing maps that are in publication and using these basemaps. Basemap urls in configuration files need to be updated before the old folder get removed.
Rory, Mykhailo and I had updated all 36 configuration files (for 18 maps in geo.ca). All updated json files are stored in this folder: [\\NRONK1AWVASP036\geoanalytics\geo.ca\FGPV_allMaps_basemapUrlUpdated](file://nronk1awvasp036/geoanalytics/geo.ca/FGPV_allMaps_basemapUrlUpdated)  
Please also copy all updated configuration files over and replace them for these 18 maps (E&F) that are published in geo.ca accordingly.

Prior to all these updates get published to geo.ca, could we get a chance to review them on geo.ca staging server

**Comment by jvanulde** [comment]
@indiciumx can you update the status of this issue in https://github.com/orgs/Canadian-Geospatial-Platform/projects/5 please.

**Comment by indiciumx** [comment]
@Andrea-Merry I don't have access to that folder. Can someone grab the configs and either put them here or on GCDocs?

**Comment by jvanulde** [comment]
@Andrea-Merry please provide @indiciumx with access to GCDocs or if the information is not protected just add the docs here.

**Comment by Andrea-Merry** [comment]
I think this issue is done. I sent Chris the files awhile ago.

**Comment by jvanulde** [comment]
@Andrea-Merry can you please review on DEV and suggest changes or approve for PROD.

**Comment by Andrea-Merry** [comment]
Approved for PROD.

**Comment by jvanulde** [comment]
@indiciumx please push to PROD and close this issue when done. Thx.

**Comment by sean-eagles** [comment]
@indiciumx  I am looking to put extra eyes on this issue, could you please send me a link where the maps have changed please?

**Comment by sean-eagles** [comment]
Reviewed on Public site/prod, all changes have been done.
