### ISSUE TITLE
Geo.ca survey

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#61]
Please go ahead and put the following survey on GEO.ca. Having a pop-up box on the main page with the survey is the preference. Second choice would be under In the Spotlight on the main page.
You can go ahead and move Heather’s survey to prod as well. 
Let me know when both are up on production. 
Thank you,
Andrea
English
Your feedback is important to us. In order to improve our platform and your experience using it, we invite you to complete a short 10 minute survey.   
[https://www.surveymonkey.ca/r/2MW7KJK](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.ca%2Fr%2F2MW7KJK&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C9c4ac5ab43d24b0257f608dab202468d%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638018020087788696%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=tGZD5FRShGOZ8yIXj%2F1sSLmJfSXW7kRO%2F2vJuWu5FJs%3D&reserved=0)
French
Vos commentaires sont importants pour nous. Afin d'améliorer notre plateforme et votre expérience d'utilisation, nous vous invitons à répondre à [un court sondage de 10 minutes.](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.ca%2Fr%2F2MW7KJK%3Flang%3Dfr&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C3199aa2ee1434133188908dab2a74f78%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638018728911703063%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3N6zasu4ZYkQhVjvVtRpFI5AvdTNl7VGXy9avXFitL8%3D&reserved=0)
https://www.surveymonkey.ca/r/2MW7KJK?lang=fr

DUPLICATION OF ISSUE #7 [
Basemap survey to be pushed to prod
English
[https://dev.geo.ca/geo-in-the-news/index.html](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.geo.ca%2Fgeo-in-the-news%2Findex.html&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C9c4ac5ab43d24b0257f608dab202468d%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638018020087944946%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=AMXUzbN3NDGi74L4Uvt9Ks5Z3FQWpGNWykg%2F1%2FOvvTY%3D&reserved=0)
French
https://dev.geo.ca/fr/geo-dans-actualite/index.html
]

**Comment by jvanulde** [comment]
This appears to duplicate in part issue #7. @Andrea-Merry please confirm and perhaps it makes sense to make this issue about the Geo.ca survey?

**Comment by ehfounder** [comment]
@Andrea-Merry do you have access to the survey monkey account? Sometimes they have a "Add a popup survey" code already provided. If they do, it would be better to use that as they would have made sure it was accessible compared to making one ourselves.

**Comment by Andrea-Merry** [comment]
@indiciumx I do not have access. Isabelle Paradis is the one who coordinated it with Rob Thorpe from comms.

**Comment by Andrea-Merry** [comment]
@jvanulde This issue is about the GEO.ca survey from Isabelle Paradis that Steve would like in a pop up box on the home page of GEO.ca. Issue #7 is to put the Basemap Survey provided by Heather Martin on the GEO in the news page.
Two different surveys asked by two separate people at different times.

**Comment by jvanulde** [comment]
@indiciumx implement as a banner. @Andrea-Merry will send you the links.

**Comment by Andrea-Merry** [comment]
@indiciumx 
Here are the links for the GEO.ca survey. Let me know when it is ready for review.
Thank you,
Andrea
EN: [https://www.surveymonkey.ca/r/2MW7KJK](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.ca%2Fr%2F2MW7KJK&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7Cfbfed6481fc74931133008dabd003ee6%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638030106001850306%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=8JgnPugmqw%2FAPeiUx2TvLGI7FGM9ezepdWjbUriLDwA%3D&reserved=0)
FR: [https://www.surveymonkey.ca/r/2MW7KJK?lang=fr](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.ca%2Fr%2F2MW7KJK%3Flang%3Dfr&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7Cfbfed6481fc74931133008dabd003ee6%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638030106001850306%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=CTuOZ9B82wN8YJN0vBErckVhuPeAKqlZfUlNo59G%2B04%3D&reserved=0)

**Comment by sean-eagles** [comment]
Banner working and redirecting to survey for GEO.ca survey.

**Comment by jvanulde** [comment]
Pushed to PROD and functioning.
