### ISSUE TITLE
 Incorrect value for the meta data property

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#66]
The meta property `<meta name="dcterms.service" content="NRCan-RNCan">` has an incorrect value. Would it be possible to have this updated to:

`<meta name="dcterms.service" content="NRCan-RNCan_FGP">`

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/66?planning-poker) with Zenhub @indiciumx

**Comment by jaredkinger** [comment]
Metadata updated on https://wordpress.dev.geo.ca/wordpress/
