### ISSUE TITLE
New logo on GEO.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#68]
NRCan comms designed a new logo to be implemented on GEO.ca. 

@indiciumx ,
What do you need in order for you to implement the new logo on GEO.ca? I will ask comms to provide what you need.
Resolution? Format? etc
Thank you,
Andrea

**Comment by jvanulde** [comment]
@Andrea-Merry please check with @sean-eagles to see if he can update the logo in the header.

**Comment by sean-eagles** [comment]
@jvanulde and @Andrea-Merry; sorry, unfortunately I'm not sure how to alter the main header to all pages.

**Comment by Andrea-Merry** [comment]
@indiciumx @jvanulde @sean-eagles 
Here is what you need to update the logo on GEO.ca. Let me know if you need anything else.
https://drive.google.com/file/d/1aIacOwJUZp5grcksAEEkZQntPvOuSlD5/view

**Comment by jvanulde** [comment]
Pushed to PROD.
