### ISSUE TITLE
GEO.ca Infected message

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#69]
Andre Pregent messaged me last night saying that when he was looking for old NAPL pictures on GEO.ca he kept getting a message that said GEO.ca was infected. See attached screenshot.
Thanks,
Andrea
<img width="603" alt="NAPLError" src="https://user-images.githubusercontent.com/112396545/200933720-b4f40bc7-81aa-4e4c-83f4-54718afb271f.PNG">

**Comment by jvanulde** [comment]
This issue has been identified by J.F. Bourgon as originating with the data cube and as such, there isn't anything that we can do on our end. Action has been taken at GeoBase to resolve this.
