### ISSUE TITLE
Add Canadian Basemap survey to Geo.ca 

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#7]
Email sent to Chris September 1, 2022
Please see Heather’s request below to put the Canadian Basemap survey on Geo.ca. I was thinking on the main page under In the Spotlight title for maximum exposure. The other place could be on the Geo in the News page. However, I don’t think it will get a lot of traffic there.

We can have a short meeting if you want to discuss when you are back.
Thank you,
Andrea

From: Martin, Heather <[heather.martin@NRCan-RNCan.gc.ca](mailto:heather.martin@NRCan-RNCan.gc.ca)> 
Sent: September 1, 2022 11:14
To: Merry, Andrea <[andrea.merry@NRCan-RNCan.gc.ca](mailto:andrea.merry@NRCan-RNCan.gc.ca)>
Cc: Avard, Bruno <[bruno.avard@NRCan-RNCan.gc.ca](mailto:bruno.avard@NRCan-RNCan.gc.ca)>; Durand, Sébastien <[sebastien.durand@NRCan-RNCan.gc.ca](mailto:sebastien.durand@NRCan-RNCan.gc.ca)>
Subject: RE: Basemap Survey for GCGEO

Hi Andrea,

We can use the following text:

English page: We need your feedback! Please take our survey of the Canadian Basemap.  
if possible, with “survey of the Canada Basemap” being a hyperlink to the survey, English: [https://www.surveymonkey.com/r/KMH8JWN?site=[ge](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.com%2Fr%2FKMH8JWN%3Fsite%3D%255bge&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C93f480b75a664cc8bb3508da8c2c8c64%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637976420197511611%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=D0iI89p%2FE4r6hy0ZOkclzJJ%2BanExCqBHYib2wsEtJRc%3D&reserved=0)o] 

French page: Nous avons besoin de vos commentaires! Veuillez répondre à notre sondage sur la carte de base du Canada.  
If possible, with « sondage sur la carte de base du Canada » being a hyperlink to the survey, French: [https://www.surveymonkey.com/r/KMH8JWN?site=[geo]&lang=fr](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.surveymonkey.com%2Fr%2FKMH8JWN%3Fsite%3D%255bgeo%255d%26lang%3Dfr&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C93f480b75a664cc8bb3508da8c2c8c64%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C637976420197511611%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oT6bT04WH6owc3owrljVXx2cWaCBcXUJDQdPTwICN58%3D&reserved=0)

**Comment by jvanulde** [comment]
@indiciumx can you update the status of this in https://github.com/orgs/Canadian-Geospatial-Platform/projects/5 please.

**Comment by jvanulde** [comment]
@Andrea-Merry please review on DEV and provide feedback.

**Comment by Andrea-Merry** [comment]
Looks good! Please push to production.

**Comment by jvanulde** [comment]
@indiciumx let's move to production.

**Comment by sean-eagles** [comment]
I see it well on DEV.

**Comment by jvanulde** [comment]
Pushed to PROD and functioning.
