### ISSUE TITLE
User Story: STAC on geo.ca 

### ISSUE THREAD

**Issue by xinli-cai** [Canadian-Geospatial-Platform/geo.ca#70]
As a user, I would like to search open datasets from the SpatialTemporalAssetCatalog (STAC) on geo.ca, so that I can view STAC data at the item level. 
An example EO STAC: 
-  [CCMEO Datacube ](https://datacube.services.geo.ca/en/index.html)
- [Collection level example](https://datacube.services.geo.ca/api/collections/napl-ottawa)
- [Item level example](https://datacube.services.geo.ca/api/collections/napl-ottawa/items/napl-ottawa-1950)

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/70?planning-poker) with Zenhub @bo-lu @dennisfu @indiciumx @jvanulde @PVautour @sean-eagles @xinli-cai

**Comment by xinli-cai** [comment]
Update: The technical stuff is completed. Currently, @bo-lu and I are working on a 2 page proposed way forward to address concerns from the Content Team and Data Team.

**Comment by xinli-cai** [comment]
Based on the feedback from the content review, we are currently working on issue Canadian-Geospatial-Platform/geo.ca#133 and issue Canadian-Geospatial-Platform/app.geo.ca#132 to address the concerns. Additionally, it will be nice to set up the minimial standards to onobarding STAC records as addressed by issue Canadian-Geospatial-Platform/geo.ca#123.
