### ISSUE TITLE
[MVP] Recommend similar records on geo.ca

### ISSUE THREAD

**Issue by xinli-cai** [Canadian-Geospatial-Platform/geo.ca#72]
When I search and enter the metadata page for a record, I would like to be recommended for the top five similar records, so that I can review related records on geo.ca. 

Requirements: 
- [x] Create Jupyter Notebooks for data visualization and comparison of vector-based text similarity models.
- [x] Develop a data preprocessing lambda to facilitate text cleaning for natural language modeling. 
- [x] Implement a word2vec lambda that utilizes the Genism Word2Vec model for performing similarity modeling.
- [x] Setup dev environment
- [x] Design and create a User Interface to display similarity records.
- [ ] Create cloud formations and establish staging and production environments.

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/72?planning-poker) with Zenhub @xinli-cai

**Comment by xinli-cai** [comment]
@johnweng001 FYI, the mock up for similarity records. 
On geo.ca metadata details page: 
1.Add a section for Similair Records, displaying the titles of the top 5 similar records, and each title is clickable that points to the records
2.Add a clickable button labeled 'View More' to reveal an additional 5 similar records when clicked.

![Untitled](https://github.com/Canadian-Geospatial-Platform/geo.ca/assets/103012417/b41e0913-177c-463c-be7b-795b0f00df50)
