### ISSUE TITLE
User Story: Publicly available development build 

### ISSUE THREAD

**Issue by elatsis** [Canadian-Geospatial-Platform/geo.ca#73]
As an external collaborator, I would like to have access to a development build of Geo.ca, so that I can review progress and provide feedback for improvements.

**Comment by jvanulde** [comment]
@elatsis lets set up an engineering meeting with @bo-lu, @indiciumx, @PVautour and @jolevesq to discuss options.

**Comment by ehfounder** [comment]
Due to security rules, it can't happen.

**Comment by jvanulde** [comment]
This is a requirement so we need to find a workaround outside of our current constraints. I will point everyone to the [Policy on Digital](https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=32603) which clearly states that design and development are to be user-driven. Our stakeholders are now external to the Government of Canada.

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/73?planning-poker) with Zenhub @bo-lu @indiciumx @PVautour @jvanulde @jolevesq
