### ISSUE TITLE
In iOS logo is distorted

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#79]
Using iOS 16 on iPhone 13:

![IMG_3664E99EE1A3-1](https://user-images.githubusercontent.com/2255248/202261419-17a261f4-0dc9-47ac-bc8d-22d67667e679.jpeg)

**Comment by bo-lu** [comment]
Appears fine on my iPhone, did you increase the font size on your phone?

**Comment by jvanulde** [comment]
No but I do have Display Zoom enabled.

**Comment by jaredkinger** [comment]
This isn't limited to iOS but appears on screens with a width of about 420px or less. The height of the logo is set to 70px via CSS which breaks the responsiveness of the image when it's width drops below it's natural width of 164px. Width, height and alt attributes also need to be added here for the image. Please feel free to assign to me.

**Comment by jaredkinger** [comment]
Logo distortion is fixed on WordPress Dev
- Added width, height and alt attributes
- Updated cgp-mega-menu.css to fix logo responsiveness
