### ISSUE TITLE
Wording on GEO.ca home page needs to be updated 

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#88]
Source: Steve Dunning is requesting that the GEO.ca home page wording be changed to reflect the updated tagline.

Currently it reads: 

**ENGLISH:** [Home - GEO.CA](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeo.ca%2Fhome%2Findex.html&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C82c13d67ec3545681c1008dacd731146%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638048191329636888%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Y7tPEGTjgeGJ2iGv4%2B3PKgjQeJ26rof6g2RcWC9nQ2c%3D&reserved=0)  : GEO.ca is the definitive source for Canada’s open geospatial resources.
**FRENCH:** [Accueil - GEO.CA](https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgeo.ca%2Ffr%2Faccueil%2Findex.html&data=05%7C01%7Candrea.merry%40NRCan-RNCan.gc.ca%7C82c13d67ec3545681c1008dacd731146%7C05c95b3390ca49d5b644288b930b912b%7C0%7C0%7C638048191329793125%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=BGHmv%2BUxCX%2FA4C2Bgc4eHvDZCqsJdD29f4fJLeM9ycs%3D&reserved=0) : GEO.ca est l’ultime source des ressources géospatiales ouvertes du Canada.

In English and French it should reflect the following:
The definitive source for Canada’s open geospatial information / La source officielle d’information géospatiale ouverte au Canada
So :
•	ENGLISH : GEO.ca is the definitive…
•	FRENCH : GEO.ca est la…

**Comment by jvanulde** [comment]
@jaredkinger @sean-eagles I would like to see this addressed as soon as possible. @elatsis we should try to get this into the mid-February release. When it's on DEV please assign @Andrea-Merry for review.

**Comment by sean-eagles** [comment]
@jaredkinger if you need anything from me Jared to get this done please let me know

**Comment by jaredkinger** [comment]
This is a great change. Having descriptive page titles is something I will be recommending as part of my SEO review.

**English:** https://wordpress.dev.geo.ca/wordpress/home/
**French:** https://wordpress.dev.geo.ca/wordpress/fr/accueil/

@sean-eagles Please assign to @Andrea-Merry for review.

**Comment by Andrea-Merry** [comment]
@jaredkinger I reviewed dev and it has not changed. It should read:
**English: GEO.ca is the definitive source for Canada’s open geospatial information**
Not this: GEO.ca is the definitive source for Canada’s open geospatial resources. 
**French: GEO.ca est la source officielle d’information géospatiale ouverte au Canada**
Not this: GEO.ca est l’ultime source des ressources géospatiales ouvertes du Canada.

**Comment by jaredkinger** [comment]
@Andrea-Merry my apologies. I thought this was referencing updating the `<title>` tags which are Home - GEO.CA / Accueil - GEO.CA. I've gone ahead and updated the `<h1>` text and reverted the changes to the `<title>` tags

Please have another look:
English: https://wordpress.dev.geo.ca/wordpress/home/
French: https://wordpress.dev.geo.ca/wordpress/fr/accueil/

**Comment by Andrea-Merry** [comment]
@jaredkinger @sean-eagles Thanks Jared! Reviewed. Ready to push.

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/88?planning-poker) with Zenhub @jaredkinger
