### ISSUE TITLE
Copyright information needs to be updated on GEO.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#89]
Source: email from Sean Hanna on November 24th, 2022.
Hi,
I was just looking at your viewer and noticed that the copyright information needs to be updated from:   
![image](https://user-images.githubusercontent.com/112396545/203855054-bb5af943-d5a0-48d7-a00d-441ce19a00f4.png)

To:
© His Majesty the King in Right of Canada, as represented by the Minister of Natural Resources Canada, 2022
© Sa Majesté le Roi du chef du Canada, représenté par le ministre de Ressources naturelles Canada, 2022

Thanks
Sean Hanna

**Comment by bo-lu** [comment]
Leaflet viewer still has Queen (scroll to the bottom): https://geo.ca/infrastructure/index.html

**Comment by bo-lu** [comment]
From TBS website (scroll to bottom): https://www.tbs-sct.canada.ca/pol/doc-eng.aspx?id=12510

Her Majesty the Queen in Right of Canada, represented by the President of the Treasury Board
Sa Majesté la Reine du chef du Canada, représentée par le président du Conseil du Trésor

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/89?planning-poker) with Zenhub @bo-lu @dennisfu @indiciumx @jolevesq @jvanulde @PVautour @sean-eagles @xinli-cai

**Comment by pvautour** [comment]
A few things to mention about this:

- It would be good to know what map he is talking about. Do you have the info @Andrea-Merry.
- The maps are not hosted on geo.ca. We simply link to them. 
- It may be hard to fix some remaining maps as I already updated the licenses to all the maps I seem to have access to. But there is some files I do not have write access to. Tried to troubleshoot the issue already with the people responsible for the server but we never figured out why.

**Comment by Andrea-Merry** [comment]
@PVautour When you are using the application on GEO.ca, at the bottom of the results pane on the left hand side it has the copyright to the Queen. See attached. v.1.0.5
<img width="771" alt="Queen" src="https://user-images.githubusercontent.com/112396545/208989799-7694b5ef-afcb-4be1-acc5-4d7aec1a453c.PNG">

**Comment by pvautour** [comment]
Omg sorry about that I take back what I said it's very possibly set in app.geo.ca.

Ill look into it immediately it may be a very easy fix.

**Comment by pvautour** [comment]
Ok fix pushed to master branch. Will be applied on next prod deployment.

**Comment by Andrea-Merry** [comment]
Thank you.

**Comment by pvautour** [comment]
This is the commit in app.geo.ca: https://github.com/Canadian-Geospatial-Platform/app.geo.ca/commit/d92293b40c6ea8134427fd89bb552b8d7b7baa1f

**Comment by johnweng001** [comment]
Thanks @PVautour 
Hi @bo-lu, the change made by Pascal is in master branch but not in dev branch. 
I guess we should do dev first before push into master in future. 
There is no action until we merge this change from master to dev.

**Comment by pvautour** [comment]
Okk ill bring it into dev. Sorry about that.

**Comment by pvautour** [comment]
Ok the commit is pushed to dev.

**Comment by johnweng001** [comment]
Thanks Pascal.
Verified that the copyright updated in dev branch.

**Comment by elatsis** [comment]
@Andrea-Merry can you please confirm if this is good to go?

**Comment by Andrea-Merry** [comment]
@elatsis Yes it is good to go.
