### ISSUE TITLE
GeoBase Initiative 

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#9]
As a CCGOG member, I would like to have a GeoBase community on Geo.ca, so that I can catalogue and share my data.

**Comment by jvanulde** [comment]
@sean-eagles can you provide links to the relevant pages in this issue as a comment. Might be a good to attach the PDF representation as well.

**Comment by sean-eagles** [comment]
Here are links to the relevant pages for GeoBase:
1 - GeoBase - Homepage: https://wordpress.dev.geo.ca/wordpress/geobase-homepage-2/

2 - GeoBase - History: https://wordpress.dev.geo.ca/wordpress/geobase-history/
3 - GeoBase - About: https://wordpress.dev.geo.ca/wordpress/geobase-about/
4 - GeoBase - Principles: https://wordpress.dev.geo.ca/wordpress/geobase-principles/
5 - GeoBase-Aboriginal Lands: https://wordpress.dev.geo.ca/wordpress/geobase-aboriginal-lands
6 - GeoBase-Administrative Boundaries: https://wordpress.dev.geo.ca/wordpress/geobase-administrative-boundaries/

**Comment by jvanulde** [comment]
@sean-eagles to follow up with GeoBase

**Comment by sean-eagles** [comment]
Scheduled a meeting for November 9, 2022 for follow up and next steps.

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/9?planning-poker) with Zenhub @sean-eagles

**Comment by sean-eagles** [comment]
Launched in 2023.
