### ISSUE TITLE
Request for mock-up: About Us page on GEO.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#90]
Source: Steve Dunning will be doing a presentation to Eric about our content strategy and the edited About Us page. Steve would like to have the edited page done in Wordpress on DEV to showcase the content to Eric. Currently the page is in English only until approved by Eric.
I have provided the links to gcdocs below and I attached the files for your convenience.
Please do not hesitate to contact me if you have any questions.
Thank you,
Andrea
 [2022-11-23 AboutUs_Wireframe v.1.1.pptx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10087114/2022-11-23.AboutUs_Wireframe.v.1.1.pptx)
[2022-11-23 AboutUs v1.1.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10087113/2022-11-23.AboutUs.v1.1.docx)
**About Us**
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/76832678

**Comment by jvanulde** [comment]
@elatsis can you follow up on this? We need a timeline. I think perhaps it needs to be added to this sprint.

@SebastienDurand @sean-eagles

**Comment by jvanulde** [comment]
@Andrea-Merry if this is an urgent request please use the `priority: urgent` label 🙏

**Comment by Andrea-Merry** [comment]
Steve is requesting to have this completed by December 9th, 2022.

**Comment by elatsis** [comment]
@Andrea-Merry @jvanulde Great - I've assigned this to our current sprint.

**Comment by jvanulde** [comment]
@sean-eagles please update this issue with links to mock-ups

**Comment by sean-eagles** [comment]
Here is the link to the edited About Us page.:
https://wordpress.dev.geo.ca/wordpress/about-us-demo/

**Comment by sean-eagles** [comment]
Hi there @vgulyy could you please visit the design that has been built in WordPress and give recommendations once you have access to telework please. also post here when you start to work on this.

**Comment by vgulyy** [comment]
@sean-eagles sounds good to me, will do, could you please add my name to this ticket in the mean time?

**Comment by sean-eagles** [comment]
@vgulyy your name has been added as an assignee.

**Comment by elatsis** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/90?planning-poker) with Zenhub @indiciumx @sean-eagles

**Comment by ehfounder** [comment]
> Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/90?planning-poker) with Zenhub @indiciumx @sean-eagles

This is for @sean-eagles and @vgulyy

**Comment by jvanulde** [comment]
@sean-eagles @Andrea-Merry is this still under review?

**Comment by Andrea-Merry** [comment]
@jvanulde I mentioned it to Steve yesterday. Still waiting for approval.

**Comment by vgulyy** [comment]
@heamart I noticed that we are missing On This Page module. I suggest we add one in to be consistent as I believe we are planning to keep this approach going forward. (Example Attached)
![Example](https://user-images.githubusercontent.com/121049163/222182163-4d5a8a94-bcb7-4ca2-9f4a-66533b65c88b.png)

**Comment by heamart** [comment]
Here are the required changes (see doc for the content)
- Addition of On This Page
- Move "Helping Canadians harness..." phrase somewhere outside of Geo.ca Partners heading (so it's representative more of the whole page.)
- rewording of the CCOG section to incorporate GeoBase link

[About Us 1.2_EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10883051/About.Us.1.2_EN.docx)

**Comment by jaredkinger** [comment]
I've implemented these changes. You can view the updated page here: https://wordpress.dev.geo.ca/wordpress/about-us-demo/

**Comment by sean-eagles** [comment]
Page was sent off to Translation.

**Comment by heamart** [comment]
Got the translation back. French version attached:
[À propos de nous 1.2_FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11054944/A.propos.de.nous.1.2_FR.docx)

**Comment by jaredkinger** [comment]
Updated About Us pages can be seen here:

- [About Us](https://wordpress.dev.geo.ca/wordpress/about-us/)
- [À propos de nous](https://wordpress.dev.geo.ca/wordpress/fr/a-propos-de-nous/)

We need French alt text for all 3 images. English alt text is as follows:

**Coordination Image**: A hand searching on the map
**Curating Image**: People with laptops working on the meeting
**Collaborating Image**: Several people sit in chairs in front of a window overlooking the Parliament of Canada

**Comment by heamart** [comment]
**Coordination Image:** Un main cherchant sur la carte.
**Curating Image:** Des personnes, avec leur ordinateur portable, en réunion
**Collaborating Image:** Plusieurs personnes sont assises sur des chaises devant une fenêtre avec vue sur le Parlement du Canada.

**Comment by jaredkinger** [comment]
@heamart Thanks for the alt text. All three images have been updated.
