### ISSUE TITLE
Request for mock-up: NRCan/CCMEO page on GEO.ca

### ISSUE THREAD

**Issue by Andrea-Merry** [Canadian-Geospatial-Platform/geo.ca#91]
Source: Steve Dunning will be doing a presentation to Eric about our content strategy and the new NRCan/CCMEO partner page. Steve would like to have the new page done in Wordpress on DEV to showcase the content to Eric. Currently the page is in English only until approved by Eric.
I have provided the link to gcdocs below and I attached the files for your convenience.
Please do not hesitate to contact me if you have any questions.
Thank you,
Andrea
**NRCan**
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/76832680 
 
[2022-11-23 NRCan Page v1.1.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10087132/2022-11-23.NRCan.Page.v1.1.docx)
[2022-11-23 NRCan Wireframe v.1.1.pptx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10087134/2022-11-23.NRCan.Wireframe.v.1.1.pptx)

**Comment by jvanulde** [comment]
@elatsis can you follow up on this? We need a timeline. I think perhaps it needs to be added to this sprint.

@SebastienDurand @sean-eagles

**Comment by jvanulde** [comment]
@Andrea-Merry if this is an urgent request please use the `priority: urgent` label 🙏

**Comment by Andrea-Merry** [comment]
Steve is requesting to have this completed by December 9th, 2022.

**Comment by elatsis** [comment]
@Andrea-Merry @jvanulde Great - I've assigned this to our current sprint.

**Comment by SebastienDurand** [comment]
Due date is friday the 9th

**Comment by jvanulde** [comment]
@sean-eagles please update this issue with links to mock-ups

**Comment by sean-eagles** [comment]
Here is the link to the Natural Resources Canada page:
https://wordpress.dev.geo.ca/wordpress/about-us-demo/natural-resources-canada/

**Comment by elatsis** [comment]
@Andrea-Merry @stevendunning have we had any feedback from DG on this?

**Comment by Andrea-Merry** [comment]
Steve has not presented the content strategy to Eric yet. It is currently in the hands of Allison. I will ask Steve if he has the date of the presentation yet.

**Comment by sean-eagles** [comment]
Hi there @vgulyy could you please visit the design that has been built in WordPress and give recommendations once you have access to telework please.  also post here when you start to work on this.

**Comment by vgulyy** [comment]
@sean-eagles , sounds good, will do. Could you please add my name to this ticket in the mean time?

**Comment by sean-eagles** [comment]
@vgulyy you have been added as an assignee.

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/91?planning-poker) with Zenhub @sean-eagles

**Comment by elatsis** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/91?planning-poker) with Zenhub @indiciumx

**Comment by ehfounder** [comment]
> Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Canadian-Geospatial-Platform-62d04ca87c442300145c51fa/issues/Canadian-Geospatial-Platform/geo.ca/91?planning-poker) with Zenhub @indiciumx

This is for Vlad and Sean.

**Comment by sean-eagles** [comment]
New mockups with information from OSDP being worked on by @jaredkinger to be done by COB February 14, 2023

**Comment by heamart** [comment]
**Still waiting on comments from Director-level, so more changes than this are likely to come.

New changes requested to the NRCan page:
- addition of an "On This Page" section, like in the GeoBase page (we like this content piece)
- Add new heading above "Canada Centre for Mapping and Earth Observation"
- Thumbnails for each box under "Products"

attached is a draft with comments for the changes. If there are improved design suggestions for these additions, please provide.

[Natural Resources Canada v1.3- EN.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10796801/Natural.Resources.Canada.v1.3-.EN.docx)

**Comment by heamart** [comment]
@sean-eagles @jaredkinger, in addition to the changes in my comment above:
- Received new text to update the paragraph under "Open Science and data to inform cumulative effects"
- There is a hyperlink in the paragraph (see comments in attached document for url)

[Natural Resources Canada v1.3- EN (1).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10850970/Natural.Resources.Canada.v1.3-.EN.1.docx)

**Comment by jaredkinger** [comment]
@heamart Page has been updated here: https://wordpress.dev.geo.ca/wordpress/about-us/nrcan/ 

@sean-eagles can you please add me as an assignee? Thanks!

**Comment by sean-eagles** [comment]
Done

**Comment by vgulyy** [comment]
@heamart, Is there a chance we can keep the thumbnail descriptions to maximum 5 lines and truncate the rest? Currently we are looking at quite many thumbnails with long descriptions for some vs others which affects scan-ability of the page (see attached example of the current view)
![Example](https://user-images.githubusercontent.com/121049163/222179570-0b675fb6-f301-4ea2-9090-0a841a7d102e.png)

**Comment by vgulyy** [comment]
@heamart I am also suggesting to keep the contextual link descriptions (On This Page) matching the page headings. Please let us know if we are good to update that as well (Example attached)
![Example](https://user-images.githubusercontent.com/121049163/222181289-d3fca4f4-8c29-444d-b6f5-101aa093cfb4.png)

**Comment by heamart** [comment]
@vgulyy yes go ahead with that. Did you want me to change the thumbnail descriptions, or are you good to truncate basically where you have circled?

**Comment by heamart** [comment]
fyi @Andrea-Merry

**Comment by jaredkinger** [comment]
@heamart I can take care of the truncation. 

For the headings "NRCan’s Featured Geospatial Contributors" and "NRCan Featured Geospatial Initiatives". Should they both be possessive/non-possessive for consistency?

@vgulyy had also mentioned to me about adding an "On This Page" section to the About Us page. Would it be possible to get a short description for that page too?

**Comment by heamart** [comment]
@jaredkinger sorry, missed that. Have them both non-possessive

@jaredkinger @vgulyy I will draft up an "On This Page" section for about us and put it in issue #90

**Comment by vgulyy** [comment]
> @vgulyy yes go ahead with that. Did you want me to change the thumbnail descriptions, or are you good to truncate basically where you have circled?

@heamart Yep, as long as the user has the full description on the actual destination page then we are good to just truncate the rest.

**Comment by heamart** [comment]
@jaredkinger @vgulyy we just got notification that one of the "services" listed on this page already has to change. 
I will hopefully send something today, but feel free to hold off on the other changes until this comes in - so you don't keep having to go back and forth

**Comment by heamart** [comment]
status update, upper-management has until March 8th to provide feedback on this page. Will submit any changes then

**Comment by heamart** [comment]
Here are some updates to the page:
- replace "Geospatial Data Extraction Tool" under Services with "Toporama"
- A few spelling and grammar corrections
(See tracked changes in attached file)

[Natural Resources Canada v1.3- EN (4).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10910239/Natural.Resources.Canada.v1.3-.EN.4.docx)

**Comment by jaredkinger** [comment]
I've implemented these changes. You can view the updated page here: https://wordpress.dev.geo.ca/wordpress/about-us/nrcan/

**Comment by heamart** [comment]
Couple super small changes to remove the sentences that trail off in the boxes, they should be a good length now to fit completely within 5 lines. See tracked changes:

[Natural Resources Canada v1.3- EN (3).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10932253/Natural.Resources.Canada.v1.3-.EN.3.docx)

**Comment by jaredkinger** [comment]
I updated the descriptions but I'm not sure anything changed. Updated page is here: https://wordpress.dev.geo.ca/wordpress/about-us/nrcan/ If it doesn't look right, can you double check that you sent me the correct version of the document?

**Comment by heamart** [comment]
My mistake, it was the wrong version. Should be this:
[Natural Resources Canada v1.3- EN (5).docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/10935507/Natural.Resources.Canada.v1.3-.EN.5.docx)

**Comment by jaredkinger** [comment]
I've updated the descriptions for HRDEM, Toporama and Data Cube. The link for Toporama is updated now too.

**Comment by Andrea-Merry** [comment]
Good morning. @jaredkinger Please update the thumbnails from the documents on gcdocs. Thank you.
Natural Resources Canada v1.3- EN.docx 
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/80134071 
Thumbnails 
https://gcdocs.gc.ca/nrcan-rncan/llisapi.dll/link/80643064

**Comment by jaredkinger** [comment]
@Andrea-Merry Unfortunately I am not able to access the gcdocs links as I don't have the proper permissions. Are you able to send me a zip file containing the images to my nrcan email?

**Comment by Andrea-Merry** [comment]
@jaredkinger I zipped and sent via gcdocs. Let me know if you got it.

**Comment by jaredkinger** [comment]
@Andrea-Merry I got the images and I have updated the NRCan page here: https://wordpress.dev.geo.ca/wordpress/about-us/nrcan/

Are you able to provide me with alt text for each of the images? The images for Data Cube and Geocore also need alt text.

**Comment by jaredkinger** [comment]
@Andrea-Merry Just saw your email with the Word Doc that has the alt text. Thanks!

**Comment by sean-eagles** [comment]
Page was sent off for translation.

**Comment by heamart** [comment]
Translation received. Attached is the french file, with the hyperlinks for french. Only two images need to be change, the thumbnails for:

- l'Atlas du Canada (thumbnail already used on another page on geo.ca - https://geo.ca/fr/decouvrez-richesse-geo/)
- Toporama (french thumbnail should be in the folder that Andrea provided)

[Ressources naturelles Canada v1.3- FR.docx](https://github.com/Canadian-Geospatial-Platform/geo.ca/files/11054925/Ressources.naturelles.Canada.v1.3-.FR.docx)

**Comment by jaredkinger** [comment]
Updated NRCan pages can be seen here:

- [Natural Resources Canada](https://wordpress.dev.geo.ca/wordpress/about-us/nrcan/)
- [Ressources naturelles Canada](https://wordpress.dev.geo.ca/wordpress/fr/a-propos-de-nous/ressources-naturelles-canada/)

The French alt text for the geocore image was in English in the Word Doc. Do you have the French alt text for that image? English alt text is "Artistic visualization of a digital system"

**Comment by heamart** [comment]
alt text for that image:
Visualisation artistique d’un système numérique.

**Comment by jaredkinger** [comment]
@heamart Thanks for the alt text. This has been updated.
