### ISSUE TITLE
Add robots.txt

### ISSUE THREAD

**Issue by jvanulde** [Canadian-Geospatial-Platform/geo.ca#99]
It appears that the requests for the robots.txt resource are being redirected to the site root.

**Comment by pvautour** [comment]
Hmm ya the redirection is probably caused by #100. 

Might as well add an empty robots.txt as soon as possible.

**Comment by jaredkinger** [comment]
I would recommend the following syntax:

`User-agent: *`
`Disallow:`

This tells all crawlers to crawl all pages.

Once I have the sitemap ready and we have deployed it we can add an additional `Sitemap:` directive for the sitemap.

**Comment by pvautour** [comment]
Ok it's in prod. Do you think we would need another one for app.geo.ca? @jaredkinger

**Comment by jaredkinger** [comment]
@PVautour yes, every subdomain should have their own respective robots.txt.

Similarly when you relaunch the sitemap you would be able to add: `Sitemap: https://app.geo.ca/sitemap.xml` to the robots.txt for app.geo.ca.

**Comment by pvautour** [comment]
Ok it's done everywhere and pushed to the dev branch in the app.geo.ca git repo. I think I can close this.
